/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AssingPowerbiDatasetDTO } from './AssingPowerbiDatasetDTO';
import type { ResPowerbiDataset } from './ResPowerbiDataset';

/**
 * @description Dataset criado com sucesso
 */
export type PbindexControllerAssignDataset201 = ResPowerbiDataset;

/**
 * @description Erro ao criar o link do PowerBI
 */
export type PbindexControllerAssignDataset500 = any;

export type PbindexControllerAssignDatasetMutationRequest =
  AssingPowerbiDatasetDTO;

export type PbindexControllerAssignDatasetMutationResponse =
  PbindexControllerAssignDataset201;

export type PbindexControllerAssignDatasetMutation = {
  Response: PbindexControllerAssignDataset201;
  Request: PbindexControllerAssignDatasetMutationRequest;
  Errors: PbindexControllerAssignDataset500;
};
