/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Lista de usuários retornada com sucesso
 */
export type PbindexControllerGetOnlineUsers200 = string[];

export type PbindexControllerGetOnlineUsersQueryResponse =
  PbindexControllerGetOnlineUsers200;

export type PbindexControllerGetOnlineUsersQuery = {
  Response: PbindexControllerGetOnlineUsers200;
  Errors: any;
};
