/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RefreshPowerbiDatasetDto } from './RefreshPowerbiDatasetDto';
import type { ResRefreshPowerbi } from './ResRefreshPowerbi';

/**
 * @description Atualização iniciada com sucesso
 */
export type PbindexControllerRefreshDatasetAsAdmin200 = ResRefreshPowerbi;

/**
 * @description Dataset não encontrado
 */
export type PbindexControllerRefreshDatasetAsAdmin404 = any;

export type PbindexControllerRefreshDatasetAsAdminMutationRequest =
  RefreshPowerbiDatasetDto;

export type PbindexControllerRefreshDatasetAsAdminMutationResponse =
  PbindexControllerRefreshDatasetAsAdmin200;

export type PbindexControllerRefreshDatasetAsAdminMutation = {
  Response: PbindexControllerRefreshDatasetAsAdmin200;
  Request: PbindexControllerRefreshDatasetAsAdminMutationRequest;
  Errors: PbindexControllerRefreshDatasetAsAdmin404;
};
