/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RefreshPowerbiDatasetDto = {
  /**
   * @description ID do dataset a ser atualizado
   * @type number
   */
  datasetID: number;
};
