/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResPowerbiRefreshDate = {
  /**
   * @description Data e hora da última atualização do dataset
   * @type object
   */
  severTime: object | null;
};
