/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { ControlePortariaVideoControllerCreateSessionMutationResponse } from '../models/ControlePortariaVideoControllerCreateSession';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControlePortariaVideoControllerCreateSessionUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/controle-portaria/video/session` as const,
  };
  return res;
}

/**
 * @summary Cria uma sessao curta para consumir o stream de video no navegador
 * {@link /api/controle-portaria/video/session}
 */
export async function controlePortariaVideoControllerCreateSession(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControlePortariaVideoControllerCreateSessionMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'POST',
    url: getControlePortariaVideoControllerCreateSessionUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
