/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { ControlePortariaVideoControllerGetStatusQueryResponse } from '../models/ControlePortariaVideoControllerGetStatus';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControlePortariaVideoControllerGetStatusUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/controle-portaria/video/status` as const,
  };
  return res;
}

/**
 * @summary Retorna o status do pipeline de video da camera
 * {@link /api/controle-portaria/video/status}
 */
export async function controlePortariaVideoControllerGetStatus(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControlePortariaVideoControllerGetStatusQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControlePortariaVideoControllerGetStatusUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
