/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ControlePortariaVideoControllerGetSegmentQueryResponse,
  ControlePortariaVideoControllerGetSegmentPathParams,
} from '../models/ControlePortariaVideoControllerGetSegment';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControlePortariaVideoControllerGetSegmentUrl(
  filename: ControlePortariaVideoControllerGetSegmentPathParams['filename'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/controle-portaria/video/segments/${filename}` as const,
  };
  return res;
}

/**
 * @summary Retorna os segmentos HLS do stream em execucao
 * {@link /api/controle-portaria/video/segments/:filename}
 */
export async function controlePortariaVideoControllerGetSegment(
  filename: ControlePortariaVideoControllerGetSegmentPathParams['filename'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControlePortariaVideoControllerGetSegmentQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControlePortariaVideoControllerGetSegmentUrl(
      filename,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
