/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { ControleVeiculosWebHookControllerGetHeartbeatQueryResponse } from '../models/ControleVeiculosWebHookControllerGetHeartbeat';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControleVeiculosWebHookControllerGetHeartbeatUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/controle-portaria/veiculos/webhook` as const,
  };
  return res;
}

/**
 * @summary Heartbeat endpoint (GET)
 * {@link /api/controle-portaria/veiculos/webhook}
 */
export async function controleVeiculosWebHookControllerGetHeartbeat(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControleVeiculosWebHookControllerGetHeartbeatQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControleVeiculosWebHookControllerGetHeartbeatUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
