/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ControleVeiculosWebHookControllerHandleWebhookMutationRequest,
  ControleVeiculosWebHookControllerHandleWebhookMutationResponse,
  ControleVeiculosWebHookControllerHandleWebhook400,
} from '../models/ControleVeiculosWebHookControllerHandleWebhook';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControleVeiculosWebHookControllerHandleWebhookUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/controle-portaria/veiculos/webhook` as const,
  };
  return res;
}

/**
 * @summary Processa o evento de entrada ou saída de um veículo
 * {@link /api/controle-portaria/veiculos/webhook}
 */
export async function controleVeiculosWebHookControllerHandleWebhook(
  data: ControleVeiculosWebHookControllerHandleWebhookMutationRequest,
  config: Partial<
    RequestConfig<ControleVeiculosWebHookControllerHandleWebhookMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ControleVeiculosWebHookControllerHandleWebhookMutationResponse,
    ResponseErrorConfig<ControleVeiculosWebHookControllerHandleWebhook400>,
    ControleVeiculosWebHookControllerHandleWebhookMutationRequest
  >({
    method: 'POST',
    url: getControleVeiculosWebHookControllerHandleWebhookUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
