/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ControleVeiculosControllerGetKpisQueryResponse,
  ControleVeiculosControllerGetKpisQueryParams,
} from '../models/ControleVeiculosControllerGetKpis';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControleVeiculosControllerGetKpisUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/controle-portaria/veiculos/kpi` as const,
  };
  return res;
}

/**
 * @summary Retorna indicadores (KPIs) de movimentação de veículos
 * {@link /api/controle-portaria/veiculos/kpi}
 */
export async function controleVeiculosControllerGetKpis(
  params?: ControleVeiculosControllerGetKpisQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControleVeiculosControllerGetKpisQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControleVeiculosControllerGetKpisUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
