/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { ControlePortariaVideoControllerGetManifestQueryResponse } from '../models/ControlePortariaVideoControllerGetManifest';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControlePortariaVideoControllerGetManifestUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/controle-portaria/video/live.m3u8` as const,
  };
  return res;
}

/**
 * @summary Retorna o manifesto HLS ao cliente autenticado por sessao
 * {@link /api/controle-portaria/video/live.m3u8}
 */
export async function controlePortariaVideoControllerGetManifest(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControlePortariaVideoControllerGetManifestQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControlePortariaVideoControllerGetManifestUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
