/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ControleVeiculosControllerGetFotoQueryResponse,
  ControleVeiculosControllerGetFotoPathParams,
} from '../models/ControleVeiculosControllerGetFoto';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControleVeiculosControllerGetFotoUrl(
  filename: ControleVeiculosControllerGetFotoPathParams['filename'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/controle-portaria/veiculos/foto/${filename}` as const,
  };
  return res;
}

/**
 * @summary Stream da foto do veículo
 * {@link /api/controle-portaria/veiculos/foto/:filename}
 */
export async function controleVeiculosControllerGetFoto(
  filename: ControleVeiculosControllerGetFotoPathParams['filename'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControleVeiculosControllerGetFotoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControleVeiculosControllerGetFotoUrl(filename).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
