/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ControleVeiculosControllerFindAllQueryResponse,
  ControleVeiculosControllerFindAllQueryParams,
} from '../models/ControleVeiculosControllerFindAll';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getControleVeiculosControllerFindAllUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/controle-portaria/veiculos` as const,
  };
  return res;
}

/**
 * @summary Lista veículos de forma paginada com filtros avançados
 * {@link /api/controle-portaria/veiculos}
 */
export async function controleVeiculosControllerFindAll(
  params?: ControleVeiculosControllerFindAllQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ControleVeiculosControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getControleVeiculosControllerFindAllUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
