/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  WifiEthosControllerGerarCodigoWifiMethodMutationRequest,
  WifiEthosControllerGerarCodigoWifiMethodMutationResponse,
  WifiEthosControllerGerarCodigoWifiMethodPathParams,
} from '../models/WifiEthosControllerGerarCodigoWifiMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getWifiEthosControllerGerarCodigoWifiMethodUrl(
  id: WifiEthosControllerGerarCodigoWifiMethodPathParams['id'],
) {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/wifi/code/${id}` as const,
  };
  return res;
}

/**
 * {@link /api/wifi/code/:id}
 */
export async function wifiEthosControllerGerarCodigoWifiMethod(
  id: WifiEthosControllerGerarCodigoWifiMethodPathParams['id'],
  data: WifiEthosControllerGerarCodigoWifiMethodMutationRequest,
  config: Partial<
    RequestConfig<WifiEthosControllerGerarCodigoWifiMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    WifiEthosControllerGerarCodigoWifiMethodMutationResponse,
    ResponseErrorConfig<Error>,
    WifiEthosControllerGerarCodigoWifiMethodMutationRequest
  >({
    method: 'POST',
    url: getWifiEthosControllerGerarCodigoWifiMethodUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
