/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  WifiEthosControllerCheckarMagicLinkMethodMutationResponse,
  WifiEthosControllerCheckarMagicLinkMethodPathParams,
} from '../models/WifiEthosControllerCheckarMagicLinkMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getWifiEthosControllerCheckarMagicLinkMethodUrl(
  id: WifiEthosControllerCheckarMagicLinkMethodPathParams['id'],
) {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/wifi/check/${id}` as const,
  };
  return res;
}

/**
 * {@link /api/wifi/check/:id}
 */
export async function wifiEthosControllerCheckarMagicLinkMethod(
  id: WifiEthosControllerCheckarMagicLinkMethodPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    WifiEthosControllerCheckarMagicLinkMethodMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'POST',
    url: getWifiEthosControllerCheckarMagicLinkMethodUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
