/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { WifiEthosControllerGerarCodigoWifiMethodMutationRequest, WifiEthosControllerGerarCodigoWifiMethodMutationResponse, WifiEthosControllerGerarCodigoWifiMethodPathParams } from "../models/WifiEthosControllerGerarCodigoWifiMethod";

function getWifiEthosControllerGerarCodigoWifiMethodUrl(id: WifiEthosControllerGerarCodigoWifiMethodPathParams["id"]) {
  return `http://192.168.99.129:3000/api/wifi/code/${id}` as const
}

/**
 * {@link /api/wifi/code/:id}
 */
export async function wifiEthosControllerGerarCodigoWifiMethod(id: WifiEthosControllerGerarCodigoWifiMethodPathParams["id"], data: WifiEthosControllerGerarCodigoWifiMethodMutationRequest, config: Partial<RequestConfig<WifiEthosControllerGerarCodigoWifiMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<WifiEthosControllerGerarCodigoWifiMethodMutationResponse, ResponseErrorConfig<Error>, WifiEthosControllerGerarCodigoWifiMethodMutationRequest>({ method : "POST", url : getWifiEthosControllerGerarCodigoWifiMethodUrl(id).toString(), data, ... requestConfig })
return res.data
}