/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  WifiEthosControllerSolicitarCodigoWifiMutationRequest,
  WifiEthosControllerSolicitarCodigoWifiMutationResponse,
} from '../models/WifiEthosControllerSolicitarCodigoWifi';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getWifiEthosControllerSolicitarCodigoWifiUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/wifi/new` as const,
  };
  return res;
}

/**
 * {@link /api/wifi/new}
 */
export async function wifiEthosControllerSolicitarCodigoWifi(
  data: WifiEthosControllerSolicitarCodigoWifiMutationRequest,
  config: Partial<
    RequestConfig<WifiEthosControllerSolicitarCodigoWifiMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    WifiEthosControllerSolicitarCodigoWifiMutationResponse,
    ResponseErrorConfig<Error>,
    WifiEthosControllerSolicitarCodigoWifiMutationRequest
  >({
    method: 'POST',
    url: getWifiEthosControllerSolicitarCodigoWifiUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
