/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { WifiEthosControllerCheckarMagicLinkMethodMutationResponse, WifiEthosControllerCheckarMagicLinkMethodPathParams } from "../models/WifiEthosControllerCheckarMagicLinkMethod";

function getWifiEthosControllerCheckarMagicLinkMethodUrl(id: WifiEthosControllerCheckarMagicLinkMethodPathParams["id"]) {
  return `https://app.ethos.ind.br/api/wifi/check/${id}` as const
}

/**
 * {@link /api/wifi/check/:id}
 */
export async function wifiEthosControllerCheckarMagicLinkMethod(id: WifiEthosControllerCheckarMagicLinkMethodPathParams["id"], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<WifiEthosControllerCheckarMagicLinkMethodMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getWifiEthosControllerCheckarMagicLinkMethodUrl(id).toString(), ... requestConfig })
return res.data
}