/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { WifiEthosControllerSolicitarCodigoWifiMutationRequest, WifiEthosControllerSolicitarCodigoWifiMutationResponse } from "../models/WifiEthosControllerSolicitarCodigoWifi";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getWifiEthosControllerSolicitarCodigoWifiUrl() {
  return `https://app.ethos.ind.br/api/wifi/new` as const
}

/**
 * {@link /api/wifi/new}
 */
export async function wifiEthosControllerSolicitarCodigoWifi(data: WifiEthosControllerSolicitarCodigoWifiMutationRequest, config: Partial<RequestConfig<WifiEthosControllerSolicitarCodigoWifiMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<WifiEthosControllerSolicitarCodigoWifiMutationResponse, ResponseErrorConfig<Error>, WifiEthosControllerSolicitarCodigoWifiMutationRequest>({ method : "POST", url : getWifiEthosControllerSolicitarCodigoWifiUrl().toString(), data, ... requestConfig })
return res.data
}