/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  GetAlbumHistoryQueryResponse,
  GetAlbumHistoryQueryParams,
} from '../models/GetAlbumHistory';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getGetAlbumHistoryUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/report-fotos` as const,
  };
  return res;
}

/**
 * {@link /mobile/galeria/report-fotos}
 */
export async function getAlbumHistory(
  params: GetAlbumHistoryQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAlbumHistoryQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetAlbumHistoryUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
