/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  GetMediaUrlQueryResponse,
  GetMediaUrlQueryParams,
} from '../models/GetMediaUrl';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getGetMediaUrlUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/media` as const,
  };
  return res;
}

/**
 * {@link /mobile/galeria/media}
 */
export async function getMediaUrl(
  params: GetMediaUrlQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMediaUrlQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetMediaUrlUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
