/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  GetPackDetailUrlQueryResponse,
  GetPackDetailUrlPathParams,
} from '../models/GetPackDetailUrl';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getGetPackDetailUrlUrl(code: GetPackDetailUrlPathParams['code']) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/pack/${code}` as const,
  };
  return res;
}

/**
 * {@link /mobile/galeria/pack/:code}
 */
export async function getPackDetailUrl(
  code: GetPackDetailUrlPathParams['code'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPackDetailUrlQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetPackDetailUrlUrl(code).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
