/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  GetProductAlbumsQueryResponse,
  GetProductAlbumsQueryParams,
} from '../models/GetProductAlbums';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getGetProductAlbumsUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/report-fotos/app-names` as const,
  };
  return res;
}

/**
 * {@link /mobile/galeria/report-fotos/app-names}
 */
export async function getProductAlbums(
  params: GetProductAlbumsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProductAlbumsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetProductAlbumsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
