/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ResolveProductLabelQueryResponse,
  ResolveProductLabelPathParams,
} from '../models/ResolveProductLabel';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getResolveProductLabelUrl(
  pdiLabel: ResolveProductLabelPathParams['pdiLabel'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/scanner/label-pdi/${pdiLabel}` as const,
  };
  return res;
}

/**
 * {@link /mobile/scanner/label-pdi/:pdiLabel}
 */
export async function resolveProductLabel(
  pdiLabel: ResolveProductLabelPathParams['pdiLabel'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ResolveProductLabelQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getResolveProductLabelUrl(pdiLabel).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
