/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DesplanejarPedidoDto = {
  /**
   * @type array
   */
  pedidoIds: number[];
  /**
   * @type string
   */
  fabricaId: string;
};
