/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FabricaResponseDto } from './FabricaResponseDto';
import type { MergeFabricaDto } from './MergeFabricaDto';

export type FabricaControllerMergeFabricaMethodError = FabricaResponseDto;

export type FabricaControllerMergeFabricaMethodMutationRequest =
  MergeFabricaDto;

export type FabricaControllerMergeFabricaMethodMutationResponse = any;

export type FabricaControllerMergeFabricaMethodMutation = {
  Response: any;
  Request: FabricaControllerMergeFabricaMethodMutationRequest;
  Errors: any;
};
