/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SincronizarFabricaPrivadaDTO } from './SincronizarFabricaPrivadaDTO';

export type FabricaControllerSincronizarFabricaPrivadaMethodError =
  SincronizarFabricaPrivadaDTO;

export type FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest =
  SincronizarFabricaPrivadaDTO;

export type FabricaControllerSincronizarFabricaPrivadaMethodMutationResponse =
  any;

export type FabricaControllerSincronizarFabricaPrivadaMethodMutation = {
  Response: any;
  Request: FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest;
  Errors: any;
};
