/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReplanejarPedidoDTO } from "./ReplanejarPedidoDTO";

export type FabricaControllerReplanejarPedidoUseCase201 = any;

export type FabricaControllerReplanejarPedidoUseCaseMutationRequest = ReplanejarPedidoDTO;

export type FabricaControllerReplanejarPedidoUseCaseMutationResponse = FabricaControllerReplanejarPedidoUseCase201;

export type FabricaControllerReplanejarPedidoUseCaseMutation = {
    Response: FabricaControllerReplanejarPedidoUseCase201;
    Request: FabricaControllerReplanejarPedidoUseCaseMutationRequest;
    Errors: any;
};