/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FabricaForkDTO } from './FabricaForkDTO';

export type FabricaControllerForkFabricaMethod201 = any;

export type FabricaControllerForkFabricaMethodMutationRequest = FabricaForkDTO;

export type FabricaControllerForkFabricaMethodMutationResponse =
  FabricaControllerForkFabricaMethod201;

export type FabricaControllerForkFabricaMethodMutation = {
  Response: FabricaControllerForkFabricaMethod201;
  Request: FabricaControllerForkFabricaMethodMutationRequest;
  Errors: any;
};
