/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FabricaResponseDto } from './FabricaResponseDto';
import type { ResetaFabricaDTO } from './ResetaFabricaDTO';

export type FabricaControllerResetaFabricaMethodError = FabricaResponseDto;

export type FabricaControllerResetaFabricaMethodMutationRequest =
  ResetaFabricaDTO;

export type FabricaControllerResetaFabricaMethodMutationResponse = any;

export type FabricaControllerResetaFabricaMethodMutation = {
  Response: any;
  Request: FabricaControllerResetaFabricaMethodMutationRequest;
  Errors: any;
};
