/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtualizarPlanejamentoDTO } from './AtualizarPlanejamentoDTO';

export type FabricaControllerAtualizarPlanejamentoMethod200 = any;

export type FabricaControllerAtualizarPlanejamentoMethodMutationRequest =
  AtualizarPlanejamentoDTO;

export type FabricaControllerAtualizarPlanejamentoMethodMutationResponse =
  FabricaControllerAtualizarPlanejamentoMethod200;

export type FabricaControllerAtualizarPlanejamentoMethodMutation = {
  Response: FabricaControllerAtualizarPlanejamentoMethod200;
  Request: FabricaControllerAtualizarPlanejamentoMethodMutationRequest;
  Errors: any;
};
