/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GanttLegendaDto = {
  /**
   * @type string
   */
  legenda: string;
  /**
   * @type string
   */
  cor: string;
};
