/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GanttData } from "./GanttData";
import type { GanttLegendaDto } from "./GanttLegendaDto";

export type GetGanttInformationDto = {
    /**
     * @type array
    */
    data: GanttData[];
    /**
     * @type array
    */
    legenda: GanttLegendaDto[];
};