/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description The Health Check is successful
 */
export type HealthControllerCheck200 = {
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type object
   */
  info?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  } | null;
  /**
   * @type object
   */
  error?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  } | null;
  /**
   * @type object | undefined
   */
  details?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  };
};

/**
 * @description The Health Check is not successful
 */
export type HealthControllerCheck503 = {
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type object
   */
  info?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  } | null;
  /**
   * @type object
   */
  error?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  } | null;
  /**
   * @type object | undefined
   */
  details?: {
    [key: string]: {
      /**
       * @type string
       */
      status: string;
      [key: string]: unknown;
    };
  };
};

export type HealthControllerCheckQueryResponse = HealthControllerCheck200;

export type HealthControllerCheckQuery = {
  Response: HealthControllerCheck200;
  Errors: HealthControllerCheck503;
};
