/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConsultarTabelaCapabilidadeDTO } from './ConsultarTabelaCapabilidadeDTO';

export type ItemControllerGetItemCapabilidadeMethodError =
  ConsultarTabelaCapabilidadeDTO[];

export type ItemControllerGetItemCapabilidadeMethodQueryResponse = any;

export type ItemControllerGetItemCapabilidadeMethodQuery = {
  Response: any;
  Errors: any;
};
