/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtrasoSlimResponseDTO } from './AtrasoSlimResponseDTO';
import type { DividaSlimResponseDTO } from './DividaSlimResponseDTO';
import type { PedidoSlimResponseDTO } from './PedidoSlimResponseDTO';

export type PedidosPlanejadosResponseDTO = {
  /**
   * @type object
   */
  pedido: PedidoSlimResponseDTO;
  /**
   * @type array
   */
  dividas: DividaSlimResponseDTO[];
  /**
   * @type array
   */
  atrasos: AtrasoSlimResponseDTO[];
};
