/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SetorResDTO = {
    /**
     * @type object
    */
    codigo: object;
    /**
     * @type string
    */
    nome: string;
};