/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GerarPreviewNestingLegendDto = {
  /**
   * @type string
   */
  item: string;
  /**
   * @type string
   */
  color: string;
  /**
   * @type number
   */
  quantity: number;
};
