/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GerarPreviewNestingLegendDto } from './GerarPreviewNestingLegendDto';
import type { GerarPreviewNestingPartDto } from './GerarPreviewNestingPartDto';

export type GerarPreviewNestingResponseDto = {
  /**
   * @description SVG da chapa com a legenda visual.
   * @type string
   */
  svg: string;
  /**
   * @type number
   */
  table: number;
  /**
   * @type number
   */
  tables: number;
  /**
   * @type array
   */
  parts: GerarPreviewNestingPartDto[];
  /**
   * @description Legenda por item, cor usada no SVG e quantidade na chapa.
   * @type array
   */
  legend: GerarPreviewNestingLegendDto[];
};
