/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LaserControllerRemoveMachinePathParams = {
  /**
   * @type string
   */
  machineId: string;
};

export type LaserControllerRemoveMachine204 = any;

export type LaserControllerRemoveMachineMutationResponse =
  LaserControllerRemoveMachine204;

export type LaserControllerRemoveMachineMutation = {
  Response: LaserControllerRemoveMachine204;
  PathParams: LaserControllerRemoveMachinePathParams;
  Errors: any;
};
