/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LaserMachineDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
};
