/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LaserControllerBoardEvents200 = any;

export type LaserControllerBoardEventsQueryResponse =
  LaserControllerBoardEvents200;

export type LaserControllerBoardEventsQuery = {
  Response: LaserControllerBoardEvents200;
  Errors: any;
};
