/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedProgramaProducaoDtoDto } from './PaginatedProgramaProducaoDtoDto';
import type { _Object } from './_Object';

export type LaserControllerListProgramsQueryParams = {
  /**
   * @minLength 0
   * @default 0
   */
  page?: _Object;
  /**
   * @minLength 1
   * @maxLength 100
   * @default 10
   */
  limit?: _Object;
};

/**
 * @description Programas de produção retornados com sucesso.
 */
export type LaserControllerListPrograms200 = PaginatedProgramaProducaoDtoDto;

export type LaserControllerListProgramsQueryResponse =
  LaserControllerListPrograms200;

export type LaserControllerListProgramsQuery = {
  Response: LaserControllerListPrograms200;
  QueryParams: LaserControllerListProgramsQueryParams;
  Errors: any;
};
