/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateLaserMachineDto } from './CreateLaserMachineDto';
import type { LaserMachineDto } from './LaserMachineDto';

export type LaserControllerCreateMachine201 = LaserMachineDto;

export type LaserControllerCreateMachineMutationRequest = CreateLaserMachineDto;

export type LaserControllerCreateMachineMutationResponse =
  LaserControllerCreateMachine201;

export type LaserControllerCreateMachineMutation = {
  Response: LaserControllerCreateMachine201;
  Request: LaserControllerCreateMachineMutationRequest;
  Errors: any;
};
