/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GerarPreviewNestingDto } from './GerarPreviewNestingDto';
import type { GerarPreviewNestingResponseDto } from './GerarPreviewNestingResponseDto';

/**
 * @description SVG e legenda da mesa do programa gerados.
 */
export type LaserControllerGenerateNestingPreview201 =
  GerarPreviewNestingResponseDto;

export type LaserControllerGenerateNestingPreviewMutationRequest =
  GerarPreviewNestingDto;

export type LaserControllerGenerateNestingPreviewMutationResponse =
  LaserControllerGenerateNestingPreview201;

export type LaserControllerGenerateNestingPreviewMutation = {
  Response: LaserControllerGenerateNestingPreview201;
  Request: LaserControllerGenerateNestingPreviewMutationRequest;
  Errors: any;
};
