/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LaserBoardDto } from './LaserBoardDto';

export type LaserControllerBoardQueryParams = {
  /**
   * @description Busca por número do programa ou código da chapa.
   * @type string | undefined
   */
  search?: string;
};

/**
 * @description Quadro de produção do laser retornado com sucesso.
 */
export type LaserControllerBoard200 = LaserBoardDto;

export type LaserControllerBoardQueryResponse = LaserControllerBoard200;

export type LaserControllerBoardQuery = {
  Response: LaserControllerBoard200;
  QueryParams: LaserControllerBoardQueryParams;
  Errors: any;
};
