/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LaserMachineDto } from './LaserMachineDto';
import type { UpdateLaserMachineDto } from './UpdateLaserMachineDto';

export type LaserControllerUpdateMachinePathParams = {
  /**
   * @type string
   */
  machineId: string;
};

export type LaserControllerUpdateMachine200 = LaserMachineDto;

export type LaserControllerUpdateMachineMutationRequest = UpdateLaserMachineDto;

export type LaserControllerUpdateMachineMutationResponse =
  LaserControllerUpdateMachine200;

export type LaserControllerUpdateMachineMutation = {
  Response: LaserControllerUpdateMachine200;
  Request: LaserControllerUpdateMachineMutationRequest;
  PathParams: LaserControllerUpdateMachinePathParams;
  Errors: any;
};
