/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LaserBoardCardDto } from './LaserBoardCardDto';

export enum LaserBoardListDtoKindEnum {
  available = 'available',
  machine = 'machine',
  finished = 'finished',
}

export type LaserBoardListDto = {
  /**
   * @description Identificador da lista.
   * @type string
   */
  id: string;
  /**
   * @description Título exibido para a lista.
   * @type string
   */
  title: string;
  /**
   * @description Tipo da lista.
   * @type string
   */
  kind: LaserBoardListDtoKindEnum;
  /**
   * @type array
   */
  cards: LaserBoardCardDto[];
  /**
   * @description Paginação da primeira página da lista.
   * @type object
   */
  pagination: object;
};
