/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LaserBoardListDto } from './LaserBoardListDto';

export type LaserBoardDto = {
  /**
   * @type array
   */
  lists: LaserBoardListDto[];
};
