/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LaserMachineDto } from './LaserMachineDto';

export type LaserControllerListMachines200 = LaserMachineDto[];

export type LaserControllerListMachinesQueryResponse =
  LaserControllerListMachines200;

export type LaserControllerListMachinesQuery = {
  Response: LaserControllerListMachines200;
  Errors: any;
};
