/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MoveLaserBoardCardDto = {
  /**
   * @type string
   */
  targetListId: string;
  /**
   * @type string
   */
  expectedListId: string;
  /**
   * @description Posição baseada em zero dentro da máquina.
   * @type number | undefined
   */
  priority?: number;
};
