/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProgramaProducaoDto } from './ProgramaProducaoDto';

export type PaginatedProgramaProducaoDtoDto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ProgramaProducaoDto.
   * @type array
   */
  data: ProgramaProducaoDto[];
};
