/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProducaoFabricaResumoDto } from './ProducaoFabricaResumoDto';

export type PaginatedProducaoFabricaResumoDtoDto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ProducaoFabricaResumoDto.
   * @type array
   */
  data: ProducaoFabricaResumoDto[];
};
