/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProducaoFabricaResumoDto = {
  /**
   * @type string
   */
  numPrograma: string;
  /**
   * @type string
   */
  codItemCompon: string;
  /**
   * @type number
   */
  pesoTotal: number;
  /**
   * @type number
   */
  tempoCorteProg: number;
  /**
   * @type number
   */
  mmLinear: number;
};
