/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedProducaoFabricaResumoDtoDto } from './PaginatedProducaoFabricaResumoDtoDto';

export enum ProducaoFabricaControllerListQueryParamsTipRegistroEnum {
  N = 'N',
  P = 'P',
  C = 'C',
  A = 'A',
}

export type ProducaoFabricaControllerListQueryParams = {
  /**
   * @minLength 0
   * @default 0
   * @type number | undefined
   */
  page?: number;
  /**
   * @minLength 1
   * @maxLength 100
   * @default 10
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Número do programa de produção.
   * @type string | undefined
   */
  numPrograma?: string;
  /**
   * @description Código do item componente.
   * @type string | undefined
   */
  codItemCompon?: string;
  /**
   * @description Tipo do registro Logix.
   * @type string | undefined
   */
  tipRegistro?: ProducaoFabricaControllerListQueryParamsTipRegistroEnum;
  /**
   * @description Peso total exato.
   * @type number | undefined
   */
  pesoTotal?: number;
  /**
   * @description Peso total mínimo.
   * @type number | undefined
   */
  pesoTotalMin?: number;
  /**
   * @description Peso total máximo.
   * @type number | undefined
   */
  pesoTotalMax?: number;
  /**
   * @description Tempo de corte programado exato.
   * @type number | undefined
   */
  tempoCorteProg?: number;
  /**
   * @description Tempo de corte programado mínimo.
   * @type number | undefined
   */
  tempoCorteProgMin?: number;
  /**
   * @description Tempo de corte programado máximo.
   * @type number | undefined
   */
  tempoCorteProgMax?: number;
  /**
   * @description Milímetros lineares exatos.
   * @type number | undefined
   */
  mmLinear?: number;
  /**
   * @description Milímetros lineares mínimos.
   * @type number | undefined
   */
  mmLinearMin?: number;
  /**
   * @description Milímetros lineares máximos.
   * @type number | undefined
   */
  mmLinearMax?: number;
};

/**
 * @description Resumo de produção retornado com sucesso.
 */
export type ProducaoFabricaControllerList200 =
  PaginatedProducaoFabricaResumoDtoDto;

export type ProducaoFabricaControllerListQueryResponse =
  ProducaoFabricaControllerList200;

export type ProducaoFabricaControllerListQuery = {
  Response: ProducaoFabricaControllerList200;
  QueryParams: ProducaoFabricaControllerListQueryParams;
  Errors: any;
};
