/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProgramaProducaoDto = {
  /**
   * @description Número do programa de produção.
   * @type string
   */
  numPrograma: string;
};
