/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResCertificadosDto } from "./ResCertificadosDto";

export type PaginatedResCertificadosDtoDto = {
    /**
     * @type number
    */
    total: number;
    /**
     * @type number
    */
    page: number;
    /**
     * @type number
    */
    limit: number;
    /**
     * @type number
    */
    totalPages: number;
    /**
     * @description Lista de itens paginados do tipo ResCertificadosDto.
     * @type array
    */
    data: ResCertificadosDto[];
};