/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { BufferControllerSaveBufferLogMutationRequest, BufferControllerSaveBufferLogMutationResponse } from "../models/BufferControllerSaveBufferLog";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getBufferControllerSaveBufferLogUrl() {
  return `https://app.ethos.ind.br/api/buffer` as const
}

/**
 * {@link /api/buffer}
 */
export async function bufferControllerSaveBufferLog(data: BufferControllerSaveBufferLogMutationRequest, config: Partial<RequestConfig<BufferControllerSaveBufferLogMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<BufferControllerSaveBufferLogMutationResponse, ResponseErrorConfig<Error>, BufferControllerSaveBufferLogMutationRequest>({ method : "POST", url : getBufferControllerSaveBufferLogUrl().toString(), data, ... requestConfig })
return res.data
}