/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { ExcelControllerCompactBuffer2ExcelMethodMutationResponse } from "../models/ExcelControllerCompactBuffer2ExcelMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getExcelControllerCompactBuffer2ExcelMethodUrl() {
  return `https://app.ethos.ind.br/api/buffer/excel` as const
}

/**
 * {@link /api/buffer/excel}
 */
export async function excelControllerCompactBuffer2ExcelMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<ExcelControllerCompactBuffer2ExcelMethodMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getExcelControllerCompactBuffer2ExcelMethodUrl().toString(), ... requestConfig })
return res.data
}