/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  SetoresControllerGetSetorMercadoMethodQueryResponse,
  SetoresControllerGetSetorMercadoMethodPathParams,
} from '../models/SetoresControllerGetSetorMercadoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getSetoresControllerGetSetorMercadoMethodUrl(
  setorId: SetoresControllerGetSetorMercadoMethodPathParams['setorId'],
  dia: SetoresControllerGetSetorMercadoMethodPathParams['dia'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/buffer/setores/${setorId}/mercados/${dia}` as const,
  };
  return res;
}

/**
 * {@link /api/buffer/setores/:setorId/mercados/:dia}
 */
export async function setoresControllerGetSetorMercadoMethod(
  setorId: SetoresControllerGetSetorMercadoMethodPathParams['setorId'],
  dia: SetoresControllerGetSetorMercadoMethodPathParams['dia'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SetoresControllerGetSetorMercadoMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getSetoresControllerGetSetorMercadoMethodUrl(
      setorId,
      dia,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
