/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { SetoresControllerGetSetoresMethodQueryResponse } from "../models/SetoresControllerGetSetoresMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getSetoresControllerGetSetoresMethodUrl() {
  return `https://app.ethos.ind.br/api/buffer/setores` as const
}

/**
 * {@link /api/buffer/setores}
 */
export async function setoresControllerGetSetoresMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<SetoresControllerGetSetoresMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSetoresControllerGetSetoresMethodUrl().toString(), ... requestConfig })
return res.data
}