/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { SetoresControllerGetSetoresMethodQueryResponse } from '../models/SetoresControllerGetSetoresMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getSetoresControllerGetSetoresMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/buffer/setores` as const,
  };
  return res;
}

/**
 * {@link /api/buffer/setores}
 */
export async function setoresControllerGetSetoresMethod(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SetoresControllerGetSetoresMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getSetoresControllerGetSetoresMethodUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
