/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedAuditLogResponseDtoDto } from './PaginatedAuditLogResponseDtoDto';

export type AuditLogControllerFindAllQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Filtra pelo nome do servico que gerou o log.
   * @type string | undefined
   */
  serviceName?: string;
  /**
   * @description Filtra pelo metodo HTTP.
   * @type string | undefined
   */
  method?: string;
  /**
   * @description Filtra pela URL requisitada.
   * @type string | undefined
   */
  url?: string;
  /**
   * @description Filtra pelo login do usuario associado ao log.
   * @type string | undefined
   */
  userLogin?: string;
  /**
   * @description Filtra pelo usuario associado ao log (nome ou login).
   * @type string | undefined
   */
  user?: string;
  /**
   * @description Filtra logs a partir desta data/hora ISO-8601.
   * @type string | undefined
   */
  startDate?: string;
  /**
   * @description Filtra logs ate esta data/hora ISO-8601.
   * @type string | undefined
   */
  endDate?: string;
};

/**
 * @description Lista paginada dos logs de auditoria.
 */
export type AuditLogControllerFindAll200 = PaginatedAuditLogResponseDtoDto;

export type AuditLogControllerFindAllQueryResponse =
  AuditLogControllerFindAll200;

export type AuditLogControllerFindAllQuery = {
  Response: AuditLogControllerFindAll200;
  QueryParams: AuditLogControllerFindAllQueryParams;
  Errors: any;
};
