/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuditLogDto } from './AuditLogDto';

export type AuditLogControllerCreate202 = any;

export type AuditLogControllerCreateMutationRequest = AuditLogDto;

export type AuditLogControllerCreateMutationResponse =
  AuditLogControllerCreate202;

export type AuditLogControllerCreateMutation = {
  Response: AuditLogControllerCreate202;
  Request: AuditLogControllerCreateMutationRequest;
  Errors: any;
};
