/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateNotaPdiEtiquetaDTO = {
  /**
   * @type string
   */
  serialNumber: string;
  /**
   * @type string
   */
  orderNum: string;
};
