/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateImpressoraBluetoothDto = {
  /**
   * @description Nome da impressora
   * @type string
   */
  nome: string;
  /**
   * @description Endereço MAC da impressora
   * @type string
   */
  macAddress: string;
};
