/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImageRes } from './ImageRes';

export type ImagemPackRes = {
  /**
   * @description ID público do pack (8 caracteres novos; 6 legados)
   * @type string
   */
  _id: string;
  /**
   * @description Autor do pack
   * @type string
   */
  author: string;
  /**
   * @description Data do servidor
   * @type string, date-time
   */
  severTime: Date;
  /**
   * @description Lista de imagens no pack
   * @type array
   */
  images: ImageRes[];
};
