/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InspectionDetailedReasonResponseDto = {
  /**
   * @type number
   */
  EventID?: number | null;
  /**
   * @type number
   */
  NoteAnswerGroupID?: number | null;
  /**
   * @type string
   */
  Answer?: string | null;
  /**
   * @type string, date-time
   */
  ServerTimestamp?: Date | null;
  /**
   * @type string
   */
  ResourceCode?: string | null;
  /**
   * @type string
   */
  ResourceName?: string | null;
  /**
   * @type string
   */
  CostCenter?: string | null;
  /**
   * @type number
   */
  OperatorID?: number | null;
  /**
   * @type string
   */
  OperatorCode?: string | null;
  /**
   * @type string
   */
  OperatorName?: string | null;
  /**
   * @type number
   */
  ProductionID?: number | null;
  /**
   * @type string
   */
  OrderNum?: string | null;
  /**
   * @type string
   */
  Operation?: string | null;
  /**
   * @type number
   */
  Sequence?: number | null;
  /**
   * @type string
   */
  PartCode?: string | null;
  /**
   * @type string
   */
  PartName?: string | null;
  /**
   * @type string
   */
  Detalhamento?: string | null;
  /**
   * @type string
   */
  NSerie?: string | null;
  /**
   * @type string
   */
  Pedido?: string | null;
  /**
   * @type string
   */
  DataEntrega?: string | null;
  /**
   * @type string
   */
  Operador?: string | null;
  /**
   * @type string
   */
  Book?: string | null;
  /**
   * @type string
   */
  NewMissedFound?: string | null;
};
