/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MobileGaleriaControllerGetMediaQueryParams = {
  /**
   * @type string
   */
  path: string;
  /**
   * @type string
   */
  name: string;
};

export type MobileGaleriaControllerGetMedia200 = any;

export type MobileGaleriaControllerGetMediaQueryResponse =
  MobileGaleriaControllerGetMedia200;

export type MobileGaleriaControllerGetMediaQuery = {
  Response: MobileGaleriaControllerGetMedia200;
  QueryParams: MobileGaleriaControllerGetMediaQueryParams;
  Errors: any;
};
