/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateNotaPdiEtiquetaDTO } from './CreateNotaPdiEtiquetaDTO';

/**
 * @description Etiqueta PDI gerada com sucesso
 */
export type MobileEtiquetasControllerEtiquetaCreateMethod201 = any;

export type MobileEtiquetasControllerEtiquetaCreateMethodMutationRequest =
  CreateNotaPdiEtiquetaDTO;

export type MobileEtiquetasControllerEtiquetaCreateMethodMutationResponse =
  MobileEtiquetasControllerEtiquetaCreateMethod201;

export type MobileEtiquetasControllerEtiquetaCreateMethodMutation = {
  Response: MobileEtiquetasControllerEtiquetaCreateMethod201;
  Request: MobileEtiquetasControllerEtiquetaCreateMethodMutationRequest;
  Errors: any;
};
