/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MobileGaleriaControllerGetImagePackMethodPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description HTML renderizado com as imagens do pack
 */
export type MobileGaleriaControllerGetImagePackMethod200 = any;

export type MobileGaleriaControllerGetImagePackMethodQueryResponse =
  MobileGaleriaControllerGetImagePackMethod200;

export type MobileGaleriaControllerGetImagePackMethodQuery = {
  Response: MobileGaleriaControllerGetImagePackMethod200;
  PathParams: MobileGaleriaControllerGetImagePackMethodPathParams;
  Errors: any;
};
