/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MobileAppReleaseResDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  version: string;
  /**
   * @type number
   */
  versionCode: number;
  /**
   * @type string
   */
  apkUrl: string;
  /**
   * @type boolean
   */
  mandatory: boolean;
  /**
   * @type array
   */
  changelog: string[];
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type string | undefined, date-time
   */
  releasedAt?: Date;
};
