/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MobileVersionControllerDeleteReleasePathParams = {
  /**
   * @description ObjectId da versão
   * @type string
   */
  id: string;
};

/**
 * @description Versão excluída com sucesso
 */
export type MobileVersionControllerDeleteRelease204 = any;

export type MobileVersionControllerDeleteReleaseMutationResponse =
  MobileVersionControllerDeleteRelease204;

export type MobileVersionControllerDeleteReleaseMutation = {
  Response: MobileVersionControllerDeleteRelease204;
  PathParams: MobileVersionControllerDeleteReleasePathParams;
  Errors: any;
};
