/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImpressoraBluetoothResponseDto } from './ImpressoraBluetoothResponseDto';

export type MobileImpressoraControllerFindOnePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Impressora encontrada
 */
export type MobileImpressoraControllerFindOne200 =
  ImpressoraBluetoothResponseDto;

/**
 * @description Impressora não encontrada
 */
export type MobileImpressoraControllerFindOne404 = any;

export type MobileImpressoraControllerFindOneQueryResponse =
  MobileImpressoraControllerFindOne200;

export type MobileImpressoraControllerFindOneQuery = {
  Response: MobileImpressoraControllerFindOne200;
  PathParams: MobileImpressoraControllerFindOnePathParams;
  Errors: MobileImpressoraControllerFindOne404;
};
