/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedStickersPdiPendentesResDto } from './PaginatedStickersPdiPendentesResDto';

export type MobileEtiquetasControllerListarEtiquetasPdiQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Filtra pelo número da ordem de produção (busca parcial).
   * @type string | undefined
   */
  orderNum?: string;
  /**
   * @description Filtra pelos 8 dígitos do número de série ou pelo DataMatrix completo de 16 dígitos.
   * @type string | undefined
   */
  serialNumber?: string;
  /**
   * @description Filtra pelo status de reporte (0 = pendente, 1 = reportado).
   * @type number | undefined
   */
  reported?: number;
  /**
   * @description Busca genérica por orderNum ou serialNumber (busca parcial em ambos).
   * @type string | undefined
   */
  search?: string;
  /**
   * @description Filtra pelo uso da etiqueta na abertura de ordem (true = usada, false = não usada).
   * @type boolean | undefined
   */
  used?: boolean;
};

/**
 * @description Lista paginada de etiquetas PDI
 */
export type MobileEtiquetasControllerListarEtiquetasPdi200 =
  PaginatedStickersPdiPendentesResDto;

export type MobileEtiquetasControllerListarEtiquetasPdiQueryResponse =
  MobileEtiquetasControllerListarEtiquetasPdi200;

export type MobileEtiquetasControllerListarEtiquetasPdiQuery = {
  Response: MobileEtiquetasControllerListarEtiquetasPdi200;
  QueryParams: MobileEtiquetasControllerListarEtiquetasPdiQueryParams;
  Errors: any;
};
