/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MobileAppReleaseResDto } from './MobileAppReleaseResDto';

export type MobileVersionControllerGetReleasePathParams = {
  /**
   * @description ObjectId da versão
   * @type string
   */
  id: string;
};

export type MobileVersionControllerGetRelease200 = MobileAppReleaseResDto;

export type MobileVersionControllerGetReleaseQueryResponse =
  MobileVersionControllerGetRelease200;

export type MobileVersionControllerGetReleaseQuery = {
  Response: MobileVersionControllerGetRelease200;
  PathParams: MobileVersionControllerGetReleasePathParams;
  Errors: any;
};
