/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Versão do app
 */
export type MobileVersionControllerGetVersion200 = string;

export type MobileVersionControllerGetVersionQueryResponse =
  MobileVersionControllerGetVersion200;

export type MobileVersionControllerGetVersionQuery = {
  Response: MobileVersionControllerGetVersion200;
  Errors: any;
};
