/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MobileAppReleaseResDto } from './MobileAppReleaseResDto';

export type MobileVersionControllerListReleases200 = MobileAppReleaseResDto[];

export type MobileVersionControllerListReleasesQueryResponse =
  MobileVersionControllerListReleases200;

export type MobileVersionControllerListReleasesQuery = {
  Response: MobileVersionControllerListReleases200;
  Errors: any;
};
