/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GerarEtiquetaCatDTO } from './GerarEtiquetaCatDTO';

/**
 * @description Etiqueta Caterpillar gerada com sucesso
 */
export type MobileEtiquetasControllerGenerateStrickerMethod201 = any;

export type MobileEtiquetasControllerGenerateStrickerMethodMutationRequest =
  GerarEtiquetaCatDTO;

export type MobileEtiquetasControllerGenerateStrickerMethodMutationResponse =
  MobileEtiquetasControllerGenerateStrickerMethod201;

export type MobileEtiquetasControllerGenerateStrickerMethodMutation = {
  Response: MobileEtiquetasControllerGenerateStrickerMethod201;
  Request: MobileEtiquetasControllerGenerateStrickerMethodMutationRequest;
  Errors: any;
};
