/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateMobileAppReleaseDto } from './CreateMobileAppReleaseDto';
import type { MobileAppReleaseResDto } from './MobileAppReleaseResDto';

export type MobileVersionControllerCreateRelease201 = MobileAppReleaseResDto;

export type MobileVersionControllerCreateReleaseMutationRequest =
  CreateMobileAppReleaseDto;

export type MobileVersionControllerCreateReleaseMutationResponse =
  MobileVersionControllerCreateRelease201;

export type MobileVersionControllerCreateReleaseMutation = {
  Response: MobileVersionControllerCreateRelease201;
  Request: MobileVersionControllerCreateReleaseMutationRequest;
  Errors: any;
};
