/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReportQualidadeRes } from './ReportQualidadeRes';

export type MobileGaleriaControllerUploadProjectHeaderParams = {
  /**
   * @description react native version
   * @type string
   */
  version: string;
};

/**
 * @description Reporte criado com sucesso
 */
export type MobileGaleriaControllerUploadProject201 = ReportQualidadeRes;

export type MobileGaleriaControllerUploadProjectMutationRequest = {
  /**
   * @type array | undefined
   */
  files?: Blob[];
  /**
   * @type string | undefined
   */
  nSerie?: string;
  /**
   * @type string | undefined
   */
  gate?: string;
  /**
   * @type string | undefined
   */
  codItem?: string;
};

export type MobileGaleriaControllerUploadProjectMutationResponse =
  MobileGaleriaControllerUploadProject201;

export type MobileGaleriaControllerUploadProjectMutation = {
  Response: MobileGaleriaControllerUploadProject201;
  Request: MobileGaleriaControllerUploadProjectMutationRequest;
  HeaderParams: MobileGaleriaControllerUploadProjectHeaderParams;
  Errors: any;
};
