/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RegenerateEtiquetaPdiDTO } from './RegenerateEtiquetaPdiDTO';

/**
 * @description Etiqueta PDI regerada com sucesso
 */
export type MobileEtiquetasControllerRegenerateStrickerPDIMethod201 = any;

export type MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest =
  RegenerateEtiquetaPdiDTO;

export type MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationResponse =
  MobileEtiquetasControllerRegenerateStrickerPDIMethod201;

export type MobileEtiquetasControllerRegenerateStrickerPDIMethodMutation = {
  Response: MobileEtiquetasControllerRegenerateStrickerPDIMethod201;
  Request: MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest;
  Errors: any;
};
