/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PdiOrderOpeningRes } from './PdiOrderOpeningRes';

export type MobileEtiquetasControllerBuscarAberturaEtiquetaPdiPathParams = {
  /**
   * @description ID da etiqueta PDI
   * @type number
   */
  id: number;
};

/**
 * @description Detalhes da abertura de ordem
 */
export type MobileEtiquetasControllerBuscarAberturaEtiquetaPdi200 =
  PdiOrderOpeningRes;

/**
 * @description Etiqueta inexistente ou ainda não utilizada
 */
export type MobileEtiquetasControllerBuscarAberturaEtiquetaPdi404 = any;

export type MobileEtiquetasControllerBuscarAberturaEtiquetaPdiQueryResponse =
  MobileEtiquetasControllerBuscarAberturaEtiquetaPdi200;

export type MobileEtiquetasControllerBuscarAberturaEtiquetaPdiQuery = {
  Response: MobileEtiquetasControllerBuscarAberturaEtiquetaPdi200;
  PathParams: MobileEtiquetasControllerBuscarAberturaEtiquetaPdiPathParams;
  Errors: MobileEtiquetasControllerBuscarAberturaEtiquetaPdi404;
};
