/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ImpressoraBluetoothResponseDto } from './ImpressoraBluetoothResponseDto';

/**
 * @description Lista de impressoras
 */
export type MobileImpressoraControllerFindAll200 =
  ImpressoraBluetoothResponseDto[];

export type MobileImpressoraControllerFindAllQueryResponse =
  MobileImpressoraControllerFindAll200;

export type MobileImpressoraControllerFindAllQuery = {
  Response: MobileImpressoraControllerFindAll200;
  Errors: any;
};
