/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReportQualidadeRes } from './ReportQualidadeRes';

export type MobileGaleriaControllerUploadMontagemL1HeaderParams = {
  /**
   * @description react native version
   * @type string
   */
  version: string;
};

/**
 * @description Reporte da Montagem L1 criado com sucesso
 */
export type MobileGaleriaControllerUploadMontagemL1201 = ReportQualidadeRes;

export type MobileGaleriaControllerUploadMontagemL1MutationRequest = {
  /**
   * @type array | undefined
   */
  files?: Blob[];
  /**
   * @type string | undefined
   */
  nSerie?: string;
  /**
   * @type string | undefined
   */
  productionId?: string;
  /**
   * @type string | undefined
   */
  codItem?: string;
  /**
   * @type string | undefined
   */
  gate?: string;
};

export type MobileGaleriaControllerUploadMontagemL1MutationResponse =
  MobileGaleriaControllerUploadMontagemL1201;

export type MobileGaleriaControllerUploadMontagemL1Mutation = {
  Response: MobileGaleriaControllerUploadMontagemL1201;
  Request: MobileGaleriaControllerUploadMontagemL1MutationRequest;
  HeaderParams: MobileGaleriaControllerUploadMontagemL1HeaderParams;
  Errors: any;
};
