/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReportFotosRes } from './ReportFotosRes';

export type PaginatedReportFotosResDto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ReportFotosRes.
   * @type array
   */
  data: ReportFotosRes[];
};
