/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InspectionDetailedReasonResponseDto } from './InspectionDetailedReasonResponseDto';

export type PaginatedInspectionDetailedReasonResponseDtoDto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo InspectionDetailedReasonResponseDto.
   * @type array
   */
  data: InspectionDetailedReasonResponseDto[];
};
