/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PdiOrderOpeningRes = {
  /**
   * @description ID do evento que abriu a ordem
   * @type number
   */
  eventId: number;
  /**
   * @description ID da produção aberta
   * @type number
   */
  productionId: number;
  /**
   * @description Número da ordem aberta
   * @type string
   */
  orderNum: string;
  /**
   * @description Rodada da ordem aberta
   * @type object | undefined
   */
  prodrun?: object;
  /**
   * @description Número de série utilizado na abertura
   * @type string
   */
  serialNumber: string;
  /**
   * @description Data e hora de abertura da ordem
   * @type string, date-time
   */
  openedAt: Date;
  /**
   * @description Nome do operador que abriu a ordem, obtido pelo Resource
   * @type object | undefined
   */
  operator?: object;
  /**
   * @description Nome da máquina
   * @type object | undefined
   */
  machine?: object;
};
