/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReportQualidadeRes = {
  /**
   * @type string
   */
  _id: string;
  /**
   * @type string | undefined
   */
  productionId?: string;
  /**
   * @type string | undefined
   */
  serialNumber?: string;
  /**
   * @type string
   */
  codItem: string;
  /**
   * @type string
   */
  gate: string;
  /**
   * @type string
   */
  reportType: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type number
   */
  attempts: number;
  /**
   * @type array
   */
  media: any[];
  /**
   * @type string | undefined
   */
  perguntaParaQualidadeID?: string;
};
