/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReportFotosAlbumResDto = {
  /**
   * @description Nome do app/contexto do álbum.
   * @type string
   */
  nome: string;
  /**
   * @description Quantidade total de fotos e vídeos no álbum.
   * @type number
   */
  quantidadeFotos: number;
};
