/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ScannerOrderDataResDto = {
  /**
   * @description Código do tipo de dado da ordem.
   * @type number
   */
  typeDataId: number;
  /**
   * @description Valor associado ao tipo de dado.
   * @type string
   */
  value: string;
};
