/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StickersPdiPendentesRes } from './StickersPdiPendentesRes';

export type ScannerControllerGetLabelPathParams = {
  /**
   * @type string
   */
  code: string;
};

/**
 * @description Detalhes da etiqueta retornados com sucesso.
 */
export type ScannerControllerGetLabel200 = StickersPdiPendentesRes;

/**
 * @description Etiqueta não encontrada.
 */
export type ScannerControllerGetLabel404 = any;

export type ScannerControllerGetLabelQueryResponse =
  ScannerControllerGetLabel200;

export type ScannerControllerGetLabelQuery = {
  Response: ScannerControllerGetLabel200;
  PathParams: ScannerControllerGetLabelPathParams;
  Errors: ScannerControllerGetLabel404;
};
