/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type StickersPdiPendentesRes = {
  /**
   * @description DataMatrix da etiqueta
   * @type string
   */
  data: string;
  /**
   * @description ID da etiqueta
   * @type number
   */
  id: number;
  /**
   * @description Data de criação no servidor
   * @type string, date-time
   */
  serverTime: Date;
  /**
   * @description Número de série extraído
   * @type string
   */
  serialNumber: string;
  /**
   * @description Número da ordem de produção
   * @type string
   */
  orderNum: string;
  /**
   * @description ID da produção relacionada à etiqueta
   * @type number | undefined
   */
  productionId?: number;
  /**
   * @description Código da peça da ordem
   * @type string | undefined
   */
  partCode?: string;
  /**
   * @description Nome da peça da ordem
   * @type string | undefined
   */
  partName?: string;
  /**
   * @description Quantidade planejada da ordem
   * @type number | undefined
   */
  planQty?: number;
  /**
   * @description Data planejada para conclusão da ordem
   * @type string | undefined, date-time
   */
  plannedEndTimestamp?: Date;
  /**
   * @description Indica se a etiqueta já foi utilizada para abrir uma ordem.
   * @type boolean
   */
  usedToOpenOrder: boolean;
};
