/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type StickersCaterpillarRes = {
  /**
   * @description ID da etiqueta
   * @type number
   */
  id: number;
  /**
   * @description Tipo de produto
   * @type string
   */
  prodType: string;
  /**
   * @description Part number Caterpillar
   * @type string
   */
  pn: string;
  /**
   * @description Dígito verificador
   * @type string
   */
  dv: string;
  /**
   * @description Revisão técnica
   * @type string
   */
  rev: string;
  /**
   * @description Código Ethos
   * @type string
   */
  ethosCod: string;
  /**
   * @description Linha de montagem
   * @type string
   */
  assemblyLine: string;
  /**
   * @description Ano e dia juliano (YYDDD)
   * @type string
   */
  yyddd: string;
  /**
   * @description Serial da etiqueta
   * @type string
   */
  serial: string;
  /**
   * @description Serial number Ethos vinculado à etiqueta
   * @type string
   */
  serialNumber: string;
  /**
   * @description ID da ordem de produção utilizada
   * @type object | undefined
   */
  productionId?: object;
  /**
   * @description Número da ordem de produção utilizada
   * @type object | undefined
   */
  orderNum?: object;
  /**
   * @description DataMatrix completa
   * @type string
   */
  datamatrix: string;
  /**
   * @description Data de criação no servidor
   * @type string, date-time
   */
  serverTime: Date;
};
