/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateMobileAppReleaseDto = {
  /**
   * @description Versão semântica exibida no aplicativo.
   * @type string | undefined
   */
  version?: string;
  /**
   * @description Código numérico usado para comparar atualizações.
   * @type number | undefined
   */
  versionCode?: number;
  /**
   * @type string | undefined
   */
  apkUrl?: string;
  /**
   * @default false
   * @type boolean | undefined
   */
  mandatory?: boolean;
  /**
   * @type array | undefined
   */
  changelog?: string[];
  /**
   * @default true
   * @type boolean | undefined
   */
  active?: boolean;
};
