/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AuthControllerLoginMutationRequest,
  AuthControllerLoginMutationResponse,
  AuthControllerLogin401,
} from '../models/AuthControllerLogin';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuthControllerLoginUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/login` as const,
  };
  return res;
}

/**
 * @summary Login user and get JWT
 * {@link /api/auth/login}
 */
export async function authControllerLogin(
  data: AuthControllerLoginMutationRequest,
  config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerLoginMutationResponse,
    ResponseErrorConfig<AuthControllerLogin401>,
    AuthControllerLoginMutationRequest
  >({
    method: 'POST',
    url: getAuthControllerLoginUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
