/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { AuthControllerLoginMutationRequest, AuthControllerLoginMutationResponse, AuthControllerLogin401 } from "../models/AuthControllerLogin";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getAuthControllerLoginUrl() {
  return `https://app.ethos.ind.br/api/auth/login` as const
}

/**
 * @summary Login user and get JWT
 * {@link /api/auth/login}
 */
export async function authControllerLogin(data: AuthControllerLoginMutationRequest, config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AuthControllerLoginMutationResponse, ResponseErrorConfig<AuthControllerLogin401>, AuthControllerLoginMutationRequest>({ method : "POST", url : getAuthControllerLoginUrl().toString(), data, ... requestConfig })
return res.data
}