/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { AuthControllerLogoutMutationResponse } from '../models/AuthControllerLogout';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuthControllerLogoutUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/logout` as const,
  };
  return res;
}

/**
 * @summary Logout user by clearing JWT cookie
 * {@link /api/auth/logout}
 */
export async function authControllerLogout(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'POST',
    url: getAuthControllerLogoutUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
