/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { AuthControllerCheckTokenMutationResponse } from '../models/AuthControllerCheckToken';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuthControllerCheckTokenUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/auth/check-token` as const,
  };
  return res;
}

/**
 * @summary Check JWT validity
 * {@link /api/auth/check-token}
 */
export async function authControllerCheckToken(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AuthControllerCheckTokenMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'POST',
    url: getAuthControllerCheckTokenUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
