/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { AuthControllerDetailQueryResponse, AuthControllerDetail401 } from "../models/AuthControllerDetail";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getAuthControllerDetailUrl() {
  return `https://app.prod.ethos/api/auth/detail` as const
}

/**
 * @summary Get authenticated user details
 * {@link /api/auth/detail}
 */
export async function authControllerDetail(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AuthControllerDetailQueryResponse, ResponseErrorConfig<AuthControllerDetail401>, unknown>({ method : "GET", url : getAuthControllerDetailUrl().toString(), ... requestConfig })
return res.data
}