/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AuthControllerGenerateInviteMutationRequest,
  AuthControllerGenerateInviteMutationResponse,
} from '../models/AuthControllerGenerateInvite';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuthControllerGenerateInviteUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/register-link` as const,
  };
  return res;
}

/**
 * @summary Generate a registration invite link
 * {@link /api/auth/register-link}
 */
export async function authControllerGenerateInvite(
  data: AuthControllerGenerateInviteMutationRequest,
  config: Partial<
    RequestConfig<AuthControllerGenerateInviteMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerGenerateInviteMutationResponse,
    ResponseErrorConfig<Error>,
    AuthControllerGenerateInviteMutationRequest
  >({
    method: 'POST',
    url: getAuthControllerGenerateInviteUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
