/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { AuthControllerCheckTokenMutationRequest, AuthControllerCheckTokenMutationResponse } from "../models/AuthControllerCheckToken";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getAuthControllerCheckTokenUrl() {
  return `https://app.prod.ethos/api/auth/check-token` as const
}

/**
 * @summary Check JWT validity
 * {@link /api/auth/check-token}
 */
export async function authControllerCheckToken(data?: AuthControllerCheckTokenMutationRequest, config: Partial<RequestConfig<AuthControllerCheckTokenMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AuthControllerCheckTokenMutationResponse, ResponseErrorConfig<Error>, AuthControllerCheckTokenMutationRequest>({ method : "POST", url : getAuthControllerCheckTokenUrl().toString(), data, ... requestConfig })
return res.data
}