/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AuthControllerDetailQueryResponse,
  AuthControllerDetail401,
} from '../models/AuthControllerDetail';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuthControllerDetailUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/auth/detail` as const,
  };
  return res;
}

/**
 * @summary Get authenticated user details
 * {@link /api/auth/detail}
 */
export async function authControllerDetail(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AuthControllerDetailQueryResponse,
    ResponseErrorConfig<AuthControllerDetail401>,
    unknown
  >({
    method: 'GET',
    url: getAuthControllerDetailUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
