/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { AuthControllerRegisterMutationRequest, AuthControllerRegisterMutationResponse, AuthControllerRegister400 } from "../models/AuthControllerRegister";

function getAuthControllerRegisterUrl() {
  return `https://app.ethos.ind.br/api/auth/register` as const
}

/**
 * @summary Register a new user
 * {@link /api/auth/register}
 */
export async function authControllerRegister(data: AuthControllerRegisterMutationRequest, config: Partial<RequestConfig<AuthControllerRegisterMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AuthControllerRegisterMutationResponse, ResponseErrorConfig<AuthControllerRegister400>, AuthControllerRegisterMutationRequest>({ method : "POST", url : getAuthControllerRegisterUrl().toString(), data, ... requestConfig })
return res.data
}