/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CargoControllerSetUserCargoMethodMutationRequest,
  CargoControllerSetUserCargoMethodMutationResponse,
} from '../models/CargoControllerSetUserCargoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCargoControllerSetUserCargoMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/cargo/set` as const,
  };
  return res;
}

/**
 * {@link /api/auth/cargo/set}
 */
export async function cargoControllerSetUserCargoMethod(
  data: CargoControllerSetUserCargoMethodMutationRequest,
  config: Partial<
    RequestConfig<CargoControllerSetUserCargoMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CargoControllerSetUserCargoMethodMutationResponse,
    ResponseErrorConfig<Error>,
    CargoControllerSetUserCargoMethodMutationRequest
  >({
    method: 'POST',
    url: getCargoControllerSetUserCargoMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
