/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { CargoControllerSetUserCargoMethodMutationRequest, CargoControllerSetUserCargoMethodMutationResponse } from "../models/CargoControllerSetUserCargoMethod";

function getCargoControllerSetUserCargoMethodUrl() {
  return `https://app.ethos.ind.br/api/auth/cargo/set` as const
}

/**
 * {@link /api/auth/cargo/set}
 */
export async function cargoControllerSetUserCargoMethod(data: CargoControllerSetUserCargoMethodMutationRequest, config: Partial<RequestConfig<CargoControllerSetUserCargoMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<CargoControllerSetUserCargoMethodMutationResponse, ResponseErrorConfig<Error>, CargoControllerSetUserCargoMethodMutationRequest>({ method : "POST", url : getCargoControllerSetUserCargoMethodUrl().toString(), data, ... requestConfig })
return res.data
}