/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorGuardEvaluationControllerEvaluateMutationRequest,
  TwoFactorGuardEvaluationControllerEvaluateMutationResponse,
} from '../models/TwoFactorGuardEvaluationControllerEvaluate';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorGuardEvaluationControllerEvaluateUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/guard/evaluate` as const,
  };
  return res;
}

/**
 * @summary Evaluate whether the current request still requires 2FA
 * {@link /api/auth/2fa/guard/evaluate}
 */
export async function twoFactorGuardEvaluationControllerEvaluate(
  data: TwoFactorGuardEvaluationControllerEvaluateMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorGuardEvaluationControllerEvaluateMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorGuardEvaluationControllerEvaluateMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorGuardEvaluationControllerEvaluateMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorGuardEvaluationControllerEvaluateUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
