/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorControllerSendEmailCodeMutationRequest,
  TwoFactorControllerSendEmailCodeMutationResponse,
  TwoFactorControllerSendEmailCodePathParams,
} from '../models/TwoFactorControllerSendEmailCode';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorControllerSendEmailCodeUrl(
  challengeId: TwoFactorControllerSendEmailCodePathParams['challengeId'],
) {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/challenges/${challengeId}/email/send` as const,
  };
  return res;
}

/**
 * @summary Send an e-mail OTP for the current 2FA challenge
 * {@link /api/auth/2fa/challenges/:challengeId/email/send}
 */
export async function twoFactorControllerSendEmailCode(
  challengeId: TwoFactorControllerSendEmailCodePathParams['challengeId'],
  data: TwoFactorControllerSendEmailCodeMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorControllerSendEmailCodeMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorControllerSendEmailCodeMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorControllerSendEmailCodeMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorControllerSendEmailCodeUrl(challengeId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
