/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest,
  TwoFactorSelfServiceControllerSetServiceAccountBypassMutationResponse,
} from '../models/TwoFactorSelfServiceControllerSetServiceAccountBypass';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorSelfServiceControllerSetServiceAccountBypassUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/admin/service-account-bypass` as const,
  };
  return res;
}

/**
 * @summary Toggle service account bypass for a user
 * {@link /api/auth/2fa/admin/service-account-bypass}
 */
export async function twoFactorSelfServiceControllerSetServiceAccountBypass(
  data: TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorSelfServiceControllerSetServiceAccountBypassMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorSelfServiceControllerSetServiceAccountBypassUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
