/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorControllerVerifyChallengeMutationRequest,
  TwoFactorControllerVerifyChallengeMutationResponse,
  TwoFactorControllerVerifyChallengePathParams,
} from '../models/TwoFactorControllerVerifyChallenge';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorControllerVerifyChallengeUrl(
  challengeId: TwoFactorControllerVerifyChallengePathParams['challengeId'],
) {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/challenges/${challengeId}/verify` as const,
  };
  return res;
}

/**
 * @summary Verify a 2FA challenge and issue a short-lived assertion
 * {@link /api/auth/2fa/challenges/:challengeId/verify}
 */
export async function twoFactorControllerVerifyChallenge(
  challengeId: TwoFactorControllerVerifyChallengePathParams['challengeId'],
  data: TwoFactorControllerVerifyChallengeMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorControllerVerifyChallengeMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorControllerVerifyChallengeMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorControllerVerifyChallengeMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorControllerVerifyChallengeUrl(challengeId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
