/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest,
  TwoFactorSelfServiceControllerRotateRecoveryCodesMutationResponse,
} from '../models/TwoFactorSelfServiceControllerRotateRecoveryCodes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorSelfServiceControllerRotateRecoveryCodesUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/recovery-codes/rotate` as const,
  };
  return res;
}

/**
 * @summary Rotate recovery codes for the current user
 * {@link /api/auth/2fa/recovery-codes/rotate}
 */
export async function twoFactorSelfServiceControllerRotateRecoveryCodes(
  data: TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorSelfServiceControllerRotateRecoveryCodesMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorSelfServiceControllerRotateRecoveryCodesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
