/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorSelfServiceControllerStartEnrollmentMutationRequest,
  TwoFactorSelfServiceControllerStartEnrollmentMutationResponse,
} from '../models/TwoFactorSelfServiceControllerStartEnrollment';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorSelfServiceControllerStartEnrollmentUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/2fa/enrollment/totp/start` as const,
  };
  return res;
}

/**
 * @summary Start TOTP enrollment for the current user
 * {@link /api/auth/2fa/enrollment/totp/start}
 */
export async function twoFactorSelfServiceControllerStartEnrollment(
  data: TwoFactorSelfServiceControllerStartEnrollmentMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorSelfServiceControllerStartEnrollmentMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorSelfServiceControllerStartEnrollmentMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorSelfServiceControllerStartEnrollmentMutationRequest
  >({
    method: 'POST',
    url: getTwoFactorSelfServiceControllerStartEnrollmentUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
