/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  TwoFactorSelfServiceControllerDisableMutationRequest,
  TwoFactorSelfServiceControllerDisableMutationResponse,
} from '../models/TwoFactorSelfServiceControllerDisable';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getTwoFactorSelfServiceControllerDisableUrl() {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/auth/2fa` as const,
  };
  return res;
}

/**
 * @summary Disable 2FA for the current user
 * {@link /api/auth/2fa}
 */
export async function twoFactorSelfServiceControllerDisable(
  data: TwoFactorSelfServiceControllerDisableMutationRequest,
  config: Partial<
    RequestConfig<TwoFactorSelfServiceControllerDisableMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    TwoFactorSelfServiceControllerDisableMutationResponse,
    ResponseErrorConfig<Error>,
    TwoFactorSelfServiceControllerDisableMutationRequest
  >({
    method: 'DELETE',
    url: getTwoFactorSelfServiceControllerDisableUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
