/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  UserAuthorizationControllerListarCentrosCustoQueryResponse,
  UserAuthorizationControllerListarCentrosCustoPathParams,
} from '../models/UserAuthorizationControllerListarCentrosCusto';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getUserAuthorizationControllerListarCentrosCustoUrl(
  usuarioId: UserAuthorizationControllerListarCentrosCustoPathParams['usuarioId'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/auth/authorization/lider-centro-custo/${usuarioId}` as const,
  };
  return res;
}

/**
 * @summary Lista os centros de custo ativos de um usuario
 * {@link /api/auth/authorization/lider-centro-custo/:usuarioId}
 */
export async function userAuthorizationControllerListarCentrosCusto(
  usuarioId: UserAuthorizationControllerListarCentrosCustoPathParams['usuarioId'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    UserAuthorizationControllerListarCentrosCustoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getUserAuthorizationControllerListarCentrosCustoUrl(
      usuarioId,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
