/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest,
  UserNotificationInternalControllerNotificarCargoPorEmailMutationResponse,
} from '../models/UserNotificationInternalControllerNotificarCargoPorEmail';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getUserNotificationInternalControllerNotificarCargoPorEmailUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/auth/users/internal/notificacoes/cargo/email` as const,
  };
  return res;
}

/**
 * {@link /api/auth/users/internal/notificacoes/cargo/email}
 */
export async function userNotificationInternalControllerNotificarCargoPorEmail(
  data: UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest,
  config: Partial<
    RequestConfig<UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UserNotificationInternalControllerNotificarCargoPorEmailMutationResponse,
    ResponseErrorConfig<Error>,
    UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest
  >({
    method: 'POST',
    url: getUserNotificationInternalControllerNotificarCargoPorEmailUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
