/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResAppRouteAppDTO } from './ResAppRouteAppDTO';

/**
 * @description Lista todas as rotas cadastradas.
 */
export type AppEthosControllerGetAllRoutes200 = ResAppRouteAppDTO[];

export type AppEthosControllerGetAllRoutesQueryResponse =
  AppEthosControllerGetAllRoutes200;

export type AppEthosControllerGetAllRoutesQuery = {
  Response: AppEthosControllerGetAllRoutes200;
  Errors: any;
};
