/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResAppRouteAppDTO } from './ResAppRouteAppDTO';

/**
 * @description Lista as rotas disponíveis para o usuário autenticado.
 */
export type AppEthosControllerGetRoutesForUser200 = ResAppRouteAppDTO[];

export type AppEthosControllerGetRoutesForUserQueryResponse =
  AppEthosControllerGetRoutesForUser200;

export type AppEthosControllerGetRoutesForUserQuery = {
  Response: AppEthosControllerGetRoutesForUser200;
  Errors: any;
};
