/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ObjectId } from "./ObjectId";

export type AppSubRouteRes = {
    /**
     * @type object
    */
    _id: ObjectId;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    route: string;
    /**
     * @type string
    */
    desc: string;
};