/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AppSubRoute = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    route: string;
    /**
     * @type string
    */
    desc: string;
};