/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AppSubRoute } from "./AppSubRoute";

export enum AtualizaAppRouteReqDTOCargosEnum {
    "ADMIN" = "ADMIN",
    "PCP" = "PCP",
    "USER" = "USER",
    "CATERPILLAR_USER" = "CATERPILLAR_USER"
}

export type AtualizaAppRouteReqDTO = {
    /**
     * @type array | undefined
    */
    subRoutes?: AppSubRoute[];
    /**
     * @type array | undefined
    */
    cargos?: AtualizaAppRouteReqDTOCargosEnum[];
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    route?: string;
    /**
     * @type string | undefined
    */
    desc?: string;
};