/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppSubRoute } from './AppSubRoute';

export enum CriaAppRouteReqDtoCargosEnum {
  ADMIN = 'ADMIN',
  ESTRUTURA = 'ESTRUTURA',
  PCP = 'PCP',
  USER = 'USER',
  MOBILE_USER = 'MOBILE_USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
  ALMOX = 'ALMOX',
  LIDER_LASER = 'LIDER_LASER',
  LIDER_SOLDA = 'LIDER_SOLDA',
  LIDER_MONTAGEM = 'LIDER_MONTAGEM',
  LIDER_QUALIDADE = 'LIDER_QUALIDADE',
  LIDER_PROCESSOS = 'LIDER_PROCESSOS',
  DIRETOR = 'DIRETOR',
  LIDER_PCP = 'LIDER_PCP',
  ADMIN_POWERBI = 'ADMIN_POWERBI',
  ADMIN_POWERBI_VIEW = 'ADMIN_POWERBI_VIEW',
}

export type CriaAppRouteReqDto = {
  /**
   * @type array
   */
  subRoutes: AppSubRoute[];
  /**
   * @type array
   */
  cargos: CriaAppRouteReqDtoCargosEnum[];
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  route: string;
  /**
   * @type string
   */
  desc: string;
};
