/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppSubRouteRes } from './AppSubRouteRes';

export enum ResAppRouteAppDTOCargosEnum {
  ADMIN = 'ADMIN',
  ESTRUTURA = 'ESTRUTURA',
  PCP = 'PCP',
  USER = 'USER',
  MOBILE_USER = 'MOBILE_USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
  ALMOX = 'ALMOX',
  PROGRAMADOR_LASER = 'PROGRAMADOR_LASER',
  PRODUCAO_LASER = 'PRODUCAO_LASER',
  LIDER = 'LIDER',
  COORDENADOR = 'COORDENADOR',
  PORTARIA = 'PORTARIA',
  DIRETOR = 'DIRETOR',
  RH = 'RH',
  SUPORTE = 'SUPORTE',
  ADMIN_POWERBI = 'ADMIN_POWERBI',
  ADMIN_POWERBI_VIEW = 'ADMIN_POWERBI_VIEW',
}

export type ResAppRouteAppDTO = {
  /**
   * @type string
   */
  _id: string;
  /**
   * @type array
   */
  subRoutes: AppSubRouteRes[];
  /**
   * @type array
   */
  cargos: ResAppRouteAppDTOCargosEnum[];
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  route: string;
  /**
   * @type string
   */
  desc: string;
};
