/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppSubRouteRes } from './AppSubRouteRes';

export enum ResAppRouteAppDTOCargosEnum {
  ADMIN = 'ADMIN',
  PCP = 'PCP',
  USER = 'USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
}

export type ResAppRouteAppDTO = {
  /**
   * @type string
   */
  _id: string;
  /**
   * @type array
   */
  subRoutes: AppSubRouteRes[];
  /**
   * @type array
   */
  cargos: ResAppRouteAppDTOCargosEnum[];
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  route: string;
  /**
   * @type string
   */
  desc: string;
};
