/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppSubRouteRes } from './AppSubRouteRes';

export enum ResAppRouteAppDTOCargosEnum {
  ADMIN = 'ADMIN',
  PCP = 'PCP',
  USER = 'USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
  LIDER_LASER = 'LIDER_LASER',
  LIDER_SOLDA = 'LIDER_SOLDA',
  LIDER_MONTAGEM = 'LIDER_MONTAGEM',
  LIDER_QUALIDADE = 'LIDER_QUALIDADE',
  LIDER_PROCESSOS = 'LIDER_PROCESSOS',
  DIRETOR = 'DIRETOR',
  LIDER_PCP = 'LIDER_PCP',
  ADMIN_POWERBI = 'ADMIN_POWERBI',
  ADMIN_POWERBI_VIEW = 'ADMIN_POWERBI_VIEW',
}

export type ResAppRouteAppDTO = {
  /**
   * @type string
   */
  _id: string;
  /**
   * @type array
   */
  subRoutes: AppSubRouteRes[];
  /**
   * @type array
   */
  cargos: ResAppRouteAppDTOCargosEnum[];
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  route: string;
  /**
   * @type string
   */
  desc: string;
};
