/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GerarCodigoWifiDTO = {
  /**
   * @type string
   */
  visitanteNome: string;
  /**
   * @type string
   */
  visitanteEmpresa: string;
  /**
   * @type string
   */
  visitanteEmail: string;
};
