/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type WifiEthosControllerCheckarMagicLinkMethodPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type WifiEthosControllerCheckarMagicLinkMethodError = boolean;

export type WifiEthosControllerCheckarMagicLinkMethodMutationResponse = any;

export type WifiEthosControllerCheckarMagicLinkMethodMutation = {
  Response: any;
  PathParams: WifiEthosControllerCheckarMagicLinkMethodPathParams;
  Errors: any;
};
