/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SolicitarCodigoWifiDTO } from './SolicitarCodigoWifiDTO';

export type WifiEthosControllerSolicitarCodigoWifiError = string;

export type WifiEthosControllerSolicitarCodigoWifiMutationRequest =
  SolicitarCodigoWifiDTO;

export type WifiEthosControllerSolicitarCodigoWifiMutationResponse = any;

export type WifiEthosControllerSolicitarCodigoWifiMutation = {
  Response: any;
  Request: WifiEthosControllerSolicitarCodigoWifiMutationRequest;
  Errors: any;
};
