/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GerarCodigoWifiDTO } from './GerarCodigoWifiDTO';

export type WifiEthosControllerGerarCodigoWifiMethodPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type WifiEthosControllerGerarCodigoWifiMethodError = string;

export type WifiEthosControllerGerarCodigoWifiMethodMutationRequest =
  GerarCodigoWifiDTO;

export type WifiEthosControllerGerarCodigoWifiMethodMutationResponse = any;

export type WifiEthosControllerGerarCodigoWifiMethodMutation = {
  Response: any;
  Request: WifiEthosControllerGerarCodigoWifiMethodMutationRequest;
  PathParams: WifiEthosControllerGerarCodigoWifiMethodPathParams;
  Errors: any;
};
