/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AceiteCompraResponseDto = {
  /**
   * @type string
   */
  status: string;
  /**
   * @type string
   */
  message: string;
  /**
   * @type string
   */
  pedido: string;
  /**
   * @type string
   */
  versaoPedido: string;
  /**
   * @type string
   */
  aprovador: string;
  /**
   * @type number
   */
  niveisAtualizados: number;
  /**
   * @type number
   */
  ordensAtualizadas: number;
};
