/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AceiteCompraResponseDto } from './AceiteCompraResponseDto';
import type { ProcessarAceiteCompraDto } from './ProcessarAceiteCompraDto';

export type LogixPluginControllerProcessarAceiteCompra200 =
  AceiteCompraResponseDto;

export type LogixPluginControllerProcessarAceiteCompraMutationRequest =
  ProcessarAceiteCompraDto;

export type LogixPluginControllerProcessarAceiteCompraMutationResponse =
  LogixPluginControllerProcessarAceiteCompra200;

export type LogixPluginControllerProcessarAceiteCompraMutation = {
  Response: LogixPluginControllerProcessarAceiteCompra200;
  Request: LogixPluginControllerProcessarAceiteCompraMutationRequest;
  Errors: any;
};
