/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PedidoAceiteCompraDetalheDto } from './PedidoAceiteCompraDetalheDto';

export type LogixPluginControllerConsultarDetalhesPedidoPathParams = {
  /**
   * @description Código da empresa no Logix
   * @default "01"
   * @type string | undefined
   */
  codEmpresa?: string;
  /**
   * @description Número do pedido
   */
  pedido: any;
};

export type LogixPluginControllerConsultarDetalhesPedido200 =
  PedidoAceiteCompraDetalheDto[];

export type LogixPluginControllerConsultarDetalhesPedidoQueryResponse =
  LogixPluginControllerConsultarDetalhesPedido200;

export type LogixPluginControllerConsultarDetalhesPedidoQuery = {
  Response: LogixPluginControllerConsultarDetalhesPedido200;
  PathParams: LogixPluginControllerConsultarDetalhesPedidoPathParams;
  Errors: any;
};
