/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PedidoAceiteCompraResumoDto } from './PedidoAceiteCompraResumoDto';

export type LogixPluginControllerListarPedidosAceiteCompra200 =
  PedidoAceiteCompraResumoDto[];

export type LogixPluginControllerListarPedidosAceiteCompraQueryResponse =
  LogixPluginControllerListarPedidosAceiteCompra200;

export type LogixPluginControllerListarPedidosAceiteCompraQuery = {
  Response: LogixPluginControllerListarPedidosAceiteCompra200;
  Errors: any;
};
