/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PedidoAceiteCompraDetalheDto = {
  /**
   * @type object
   */
  solicitante: object | null;
  /**
   * @type string
   */
  numeroOc: string;
  /**
   * @type string
   */
  numeroVersao: string;
  /**
   * @type object
   */
  codItem: object | null;
  /**
   * @type object
   */
  descricaoItem: object | null;
  /**
   * @type string
   */
  numeroPedido: string;
  /**
   * @type object
   */
  unidadeMedida: object | null;
  /**
   * @type object
   */
  dataEmissao: object | null;
  /**
   * @type object
   */
  quantidadeSolicitada: object | null;
  /**
   * @type object
   */
  quantidadeRecebida: object | null;
  /**
   * @type object
   */
  dataAberturaOc: object | null;
  /**
   * @type object
   */
  precoUnitario: object | null;
  /**
   * @type object
   */
  valorOc: object | null;
  /**
   * @type object
   */
  fornecedor: object | null;
  /**
   * @type object
   */
  condicaoPagamento: object | null;
  /**
   * @type object
   */
  modalidadeEmbarque: object | null;
};
