/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProcessarAceiteCompraDto = {
  /**
   * @description Número do pedido no Logix
   * @type string
   */
  pedido: string;
  /**
   * @description Código da empresa no Logix
   * @default "01"
   * @type string | undefined
   */
  codEmpresa?: string;
};
