/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { FabricaControllerConsultaFabricaPrincipalMethodQueryResponse } from '../models/FabricaControllerConsultaFabricaPrincipalMethod.ts'

function getFabricaControllerConsultaFabricaPrincipalMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/principal` as const
}

/**
 * {@link /api/fabrica/principal}
 */
export async function fabricaControllerConsultaFabricaPrincipalMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FabricaControllerConsultaFabricaPrincipalMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getFabricaControllerConsultaFabricaPrincipalMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}