/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type {
  FabricaControllerConsultarPedidosPlanejadosMethodQueryResponse,
  FabricaControllerConsultarPedidosPlanejadosMethodQueryParams,
} from '../models/FabricaControllerConsultarPedidosPlanejadosMethod.ts'

function getFabricaControllerConsultarPedidosPlanejadosMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/planejamentos/pedidos` as const
}

/**
 * {@link /api/fabrica/planejamentos/pedidos}
 */
export async function fabricaControllerConsultarPedidosPlanejadosMethod(
  params: FabricaControllerConsultarPedidosPlanejadosMethodQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FabricaControllerConsultarPedidosPlanejadosMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getFabricaControllerConsultarPedidosPlanejadosMethodUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}