/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerPlanejarPedidoMethodMutationRequest, FabricaControllerPlanejarPedidoMethodMutationResponse } from "../models/FabricaControllerPlanejarPedidoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerPlanejarPedidoMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/planejamentos` as const
}

/**
 * {@link /api/fabrica/planejamentos}
 */
export async function fabricaControllerPlanejarPedidoMethod(data: FabricaControllerPlanejarPedidoMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerPlanejarPedidoMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerPlanejarPedidoMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerPlanejarPedidoMethodMutationRequest>({ method : "POST", url : getFabricaControllerPlanejarPedidoMethodUrl().toString(), data, ... requestConfig })
return res.data
}