/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type {
  FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest,
  FabricaControllerAtualizarPlanejamtnoUseCaseMutationResponse,
} from '../models/FabricaControllerAtualizarPlanejamtnoUseCase.js'

function getFabricaControllerAtualizarPlanejamtnoUseCaseUrl() {
  return `http://192.168.99.129:3000/api/fabrica/planejamentos` as const
}

/**
 * {@link /api/fabrica/planejamentos}
 */
export async function fabricaControllerAtualizarPlanejamtnoUseCase(
  data: FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest,
  config: Partial<RequestConfig<FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    FabricaControllerAtualizarPlanejamtnoUseCaseMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest
  >({ method: 'POST', url: getFabricaControllerAtualizarPlanejamtnoUseCaseUrl().toString(), data, ...requestConfig })
  return res.data
}