/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerRequestFabricaMergeMethodMutationRequest, FabricaControllerRequestFabricaMergeMethodMutationResponse } from "../models/FabricaControllerRequestFabricaMergeMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerRequestFabricaMergeMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/merge/request` as const
}

/**
 * {@link /api/fabrica/merge/request}
 */
export async function fabricaControllerRequestFabricaMergeMethod(data: FabricaControllerRequestFabricaMergeMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerRequestFabricaMergeMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerRequestFabricaMergeMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerRequestFabricaMergeMethodMutationRequest>({ method : "POST", url : getFabricaControllerRequestFabricaMergeMethodUrl().toString(), data, ... requestConfig })
return res.data
}