/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type {
  FabricaControllerDeletarFabricaMethodMutationRequest,
  FabricaControllerDeletarFabricaMethodMutationResponse,
} from '../models/FabricaControllerDeletarFabricaMethod.ts'

function getFabricaControllerDeletarFabricaMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/fabrica` as const
}

/**
 * {@link /api/fabrica/fabrica}
 */
export async function fabricaControllerDeletarFabricaMethod(
  data: FabricaControllerDeletarFabricaMethodMutationRequest,
  config: Partial<RequestConfig<FabricaControllerDeletarFabricaMethodMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    FabricaControllerDeletarFabricaMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerDeletarFabricaMethodMutationRequest
  >({ method: 'DELETE', url: getFabricaControllerDeletarFabricaMethodUrl().toString(), data, ...requestConfig })
  return res.data
}