/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerGetRequestsFabricaMergeMethodQueryResponse } from "../models/FabricaControllerGetRequestsFabricaMergeMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerGetRequestsFabricaMergeMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/merge/request` as const
}

/**
 * {@link /api/fabrica/merge/request}
 */
export async function fabricaControllerGetRequestsFabricaMergeMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerGetRequestsFabricaMergeMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFabricaControllerGetRequestsFabricaMergeMethodUrl().toString(), ... requestConfig })
return res.data
}