/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { FabricaControllerTestemethodMutationResponse } from '../models/FabricaControllerTestemethod.js'

function getFabricaControllerTestemethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/teste` as const
}

/**
 * {@link /api/fabrica/teste}
 */
export async function fabricaControllerTestemethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FabricaControllerTestemethodMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: getFabricaControllerTestemethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}