/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQueryResponse } from '../models/FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethod.ts'

function getFabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodUrl() {
  return `http://192.168.99.129:9279/api/fabrica/usuario` as const
}

/**
 * {@link /api/fabrica/usuario}
 */
export async function fabricaControllerConsutlarFabricasDoUsuarioUseCaseMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getFabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}