/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { KPIControllerGetGanttInformationMethodQueryResponse, KPIControllerGetGanttInformationMethodQueryParams } from "../models/KPIControllerGetGanttInformationMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getKPIControllerGetGanttInformationMethodUrl() {
  return `http://192.168.99.129:9279/api/kpi/gannt` as const
}

/**
 * @summary Gera informações para o gráfico
 * {@link /api/kpi/gannt}
 */
export async function KPIControllerGetGanttInformationMethod(params: KPIControllerGetGanttInformationMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<KPIControllerGetGanttInformationMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getKPIControllerGetGanttInformationMethodUrl().toString(), params, ... requestConfig })
return res.data
}