/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type {
  PedidoControllerConsultaItensDoPedidoMethodQueryResponse,
  PedidoControllerConsultaItensDoPedidoMethodQueryParams,
} from '../models/PedidoControllerConsultaItensDoPedidoMethod.ts'

function getPedidoControllerConsultaItensDoPedidoMethodUrl() {
  return `http://192.168.99.129:9279/api/pedido/itens` as const
}

/**
 * {@link /api/pedido/itens}
 */
export async function pedidoControllerConsultaItensDoPedidoMethod(
  params: PedidoControllerConsultaItensDoPedidoMethodQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PedidoControllerConsultaItensDoPedidoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getPedidoControllerConsultaItensDoPedidoMethodUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}