/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { PlanejamentoControllerPlanejamentoMethodMutationResponse } from '../models/PlanejamentoControllerPlanejamentoMethod.js'

function getPlanejamentoControllerPlanejamentoMethodUrl() {
  return `http://192.168.99.129:3000/api/plan` as const
}

/**
 * {@link /api/plan}
 */
export async function planejamentoControllerPlanejamentoMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PlanejamentoControllerPlanejamentoMethodMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: getPlanejamentoControllerPlanejamentoMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}