/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { PlanejamentoControllerDatasPlanejadasMethodQueryResponse } from '../models/PlanejamentoControllerDatasPlanejadasMethod.ts'

function getPlanejamentoControllerDatasPlanejadasMethodUrl() {
  return `http://192.168.99.129:3000/plan/datas` as const
}

/**
 * {@link /plan/datas}
 */
export async function planejamentoControllerDatasPlanejadasMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PlanejamentoControllerDatasPlanejadasMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getPlanejamentoControllerDatasPlanejadasMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}