/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { ProducaoSimulacaoControllerGetGanttInformationMethodQueryResponse } from '../models/ProducaoSimulacaoControllerGetGanttInformationMethod.js'

function getProducaoSimulacaoControllerGetGanttInformationMethodUrl() {
  return `http://192.168.99.129:3000/api/simulacao/gen/gannt` as const
}

/**
 * @summary Gera informações para o gráfico
 * {@link /api/simulacao/gen/gannt}
 */
export async function producaoSimulacaoControllerGetGanttInformationMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ProducaoSimulacaoControllerGetGanttInformationMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getProducaoSimulacaoControllerGetGanttInformationMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}