/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { ProducaoSimulacaoControllerConsultarMercadoMethodQueryResponse } from '../models/ProducaoSimulacaoControllerConsultarMercadoMethod.ts'

function getProducaoSimulacaoControllerConsultarMercadoMethodUrl() {
  return `http://192.168.99.129:3000/simulacao/gen/mercado` as const
}

/**
 * {@link /simulacao/gen/mercado}
 */
export async function producaoSimulacaoControllerConsultarMercadoMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ProducaoSimulacaoControllerConsultarMercadoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getProducaoSimulacaoControllerConsultarMercadoMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}