/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationRequest, ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationResponse } from "../models/ProducaoSimulacaoControllerSaveTabelaDiariaMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getProducaoSimulacaoControllerSaveTabelaDiariaMethodUrl() {
  return `http://192.168.99.129:9279/api/simulacao/gen` as const
}

/**
 * @summary Salva a tabela diária de produção para a data informada
 * {@link /api/simulacao/gen}
 */
export async function producaoSimulacaoControllerSaveTabelaDiariaMethod(data: ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationRequest, config: Partial<RequestConfig<ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationResponse, ResponseErrorConfig<Error>, ProducaoSimulacaoControllerSaveTabelaDiariaMethodMutationRequest>({ method : "POST", url : getProducaoSimulacaoControllerSaveTabelaDiariaMethodUrl().toString(), data, ... requestConfig })
return res.data
}