/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/client'
import type { RequestConfig, ResponseErrorConfig } from '@/client'
import type { ReplanejamentoControllerReplanejamentoMethodMutationResponse } from '../models/ReplanejamentoControllerReplanejamentoMethod.ts'

function getReplanejamentoControllerReplanejamentoMethodUrl() {
  return `http://192.168.99.129:9279/api/replanejamento` as const
}

/**
 * {@link /api/replanejamento}
 */
export async function replanejamentoControllerReplanejamentoMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<ReplanejamentoControllerReplanejamentoMethodMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: getReplanejamentoControllerReplanejamentoMethodUrl().toString(),
    ...requestConfig,
  })
  return res.data
}