/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { UserControllerUserDetailsMethodQueryResponse, UserControllerUserDetailsMethod401 } from "../models/UserControllerUserDetailsMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getUserControllerUserDetailsMethodUrl() {
  return `http://192.168.99.129:9279/api/user/me` as const
}

/**
 * {@link /api/user/me}
 */
export async function userControllerUserDetailsMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<UserControllerUserDetailsMethodQueryResponse, ResponseErrorConfig<UserControllerUserDetailsMethod401>, unknown>({ method : "GET", url : getUserControllerUserDetailsMethodUrl().toString(), ... requestConfig })
return res.data
}