/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { UserControllerLoginMethodMutationRequest, UserControllerLoginMethodMutationResponse, UserControllerLoginMethod401 } from "../models/UserControllerLoginMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getUserControllerLoginMethodUrl() {
  return `http://192.168.99.129:9279/api/user/auth` as const
}

/**
 * {@link /api/user/auth}
 */
export async function userControllerLoginMethod(data: UserControllerLoginMethodMutationRequest, config: Partial<RequestConfig<UserControllerLoginMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<UserControllerLoginMethodMutationResponse, ResponseErrorConfig<UserControllerLoginMethod401>, UserControllerLoginMethodMutationRequest>({ method : "POST", url : getUserControllerLoginMethodUrl().toString(), data, ... requestConfig })
return res.data
}