/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AuditLogControllerFindAllQueryResponse,
  AuditLogControllerFindAllQueryParams,
} from '../models/AuditLogControllerFindAll';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAuditLogControllerFindAllUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/audit/log` as const,
  };
  return res;
}

/**
 * {@link /api/audit/log}
 */
export async function auditLogControllerFindAll(
  params?: AuditLogControllerFindAllQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AuditLogControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getAuditLogControllerFindAllUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
