/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum CentroCustoLiderEnum {
  CentroCustoLiderEnum_8888 = 8888,
  CentroCustoLiderEnum_9100 = 9100,
  CentroCustoLiderEnum_9111 = 9111,
  CentroCustoLiderEnum_9112 = 9112,
  CentroCustoLiderEnum_9113 = 9113,
  CentroCustoLiderEnum_9114 = 9114,
  CentroCustoLiderEnum_9115 = 9115,
  CentroCustoLiderEnum_9116 = 9116,
  CentroCustoLiderEnum_9120 = 9120,
  CentroCustoLiderEnum_9130 = 9130,
  CentroCustoLiderEnum_9131 = 9131,
  CentroCustoLiderEnum_9151 = 9151,
  CentroCustoLiderEnum_9152 = 9152,
  CentroCustoLiderEnum_9153 = 9153,
  CentroCustoLiderEnum_9154 = 9154,
  CentroCustoLiderEnum_9155 = 9155,
  CentroCustoLiderEnum_9156 = 9156,
  CentroCustoLiderEnum_9215 = 9215,
  CentroCustoLiderEnum_9216 = 9216,
  CentroCustoLiderEnum_9217 = 9217,
  CentroCustoLiderEnum_9228 = 9228,
  CentroCustoLiderEnum_9229 = 9229,
  CentroCustoLiderEnum_9230 = 9230,
  CentroCustoLiderEnum_9231 = 9231,
  CentroCustoLiderEnum_9226 = 9226,
  CentroCustoLiderEnum_9227 = 9227,
}

export type CentroCustoLider = CentroCustoLiderEnum;
