/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ItemFuncionarioHEDTO } from './ItemFuncionarioHEDTO';

export type CriarFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  dataContexto: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type array
   */
  funcionarios: ItemFuncionarioHEDTO[];
  /**
   * @type string | undefined
   */
  observacao?: string;
};
