/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ItemFuncionarioHEDTO } from './ItemFuncionarioHEDTO';

export type EditarFolhaHoraExtraDTO = {
  /**
   * @type string | undefined
   */
  dataContexto?: string;
  /**
   * @type string | undefined
   */
  setor?: string;
  /**
   * @type number | undefined
   */
  centroCustoCodigo?: number;
  /**
   * @type array | undefined
   */
  funcionarios?: ItemFuncionarioHEDTO[];
  /**
   * @type string | undefined
   */
  observacao?: string;
};
