/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EditarFolhaHoraExtraDTO } from './EditarFolhaHoraExtraDTO';
import type { ResFolhaHoraExtraDetalheDTO } from './ResFolhaHoraExtraDetalheDTO';

export type FolhaHoraExtraControllerEditarPathParams = {
  /**
   * @description ID MongoDB da folha de hora extra.
   * @type string
   */
  id: string;
};

/**
 * @description Folha atualizada com sucesso.
 */
export type FolhaHoraExtraControllerEditar200 = ResFolhaHoraExtraDetalheDTO;

/**
 * @description Folha em status nao editavel, usuario nao autor, dados invalidos ou usuario sem vinculo com o novo centro de custo.
 */
export type FolhaHoraExtraControllerEditar400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerEditar401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerEditar403 = any;

/**
 * @description Folha nao encontrada.
 */
export type FolhaHoraExtraControllerEditar404 = any;

/**
 * @description Campos alteraveis da folha. Campos omitidos mantem o valor atual.
 */
export type FolhaHoraExtraControllerEditarMutationRequest =
  EditarFolhaHoraExtraDTO;

export type FolhaHoraExtraControllerEditarMutationResponse =
  FolhaHoraExtraControllerEditar200;

export type FolhaHoraExtraControllerEditarMutation = {
  Response: FolhaHoraExtraControllerEditar200;
  Request: FolhaHoraExtraControllerEditarMutationRequest;
  PathParams: FolhaHoraExtraControllerEditarPathParams;
  Errors:
    | FolhaHoraExtraControllerEditar400
    | FolhaHoraExtraControllerEditar401
    | FolhaHoraExtraControllerEditar403
    | FolhaHoraExtraControllerEditar404;
};
