/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResHorasExtrasNaoAutorizadasDTO } from './ResHorasExtrasNaoAutorizadasDTO';

export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryParams = {
  /**
   * @description Filial Protheus. Padrão: 01.
   * @type string | undefined
   */
  filial?: string;
  /**
   * @type array | undefined
   */
  matriculas?: string[];
  /**
   * @description Trecho do nome do funcionário, sem diferenciação de maiúsculas ou acentos.
   * @type string | undefined
   */
  nome?: string;
  /**
   * @type array | undefined
   */
  centroCustos?: string[];
  /**
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @type string | undefined
   */
  dataFim?: string;
};

export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas200 =
  ResHorasExtrasNaoAutorizadasDTO[];

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas403 = any;

export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryResponse =
  FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas200;

export type FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQuery = {
  Response: FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas200;
  QueryParams: FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryParams;
  Errors:
    | FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas401
    | FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas403;
};
