/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RejeitarFolhaHoraExtraDTO } from './RejeitarFolhaHoraExtraDTO';
import type { ResFolhaHoraExtraDetalheDTO } from './ResFolhaHoraExtraDetalheDTO';

export type FolhaHoraExtraControllerRejeitarPathParams = {
  /**
   * @description ID MongoDB da folha de hora extra.
   * @type string
   */
  id: string;
};

/**
 * @description Folha rejeitada com motivo registrado no historico.
 */
export type FolhaHoraExtraControllerRejeitar200 = ResFolhaHoraExtraDetalheDTO;

/**
 * @description Motivo ausente, cargo invalido ou transicao de status invalida para a etapa atual.
 */
export type FolhaHoraExtraControllerRejeitar400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerRejeitar401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerRejeitar403 = any;

/**
 * @description Folha nao encontrada.
 */
export type FolhaHoraExtraControllerRejeitar404 = any;

/**
 * @description Motivo da rejeicao. O campo folhaId do DTO e informativo; a rota usa o id do path.
 */
export type FolhaHoraExtraControllerRejeitarMutationRequest =
  RejeitarFolhaHoraExtraDTO;

export type FolhaHoraExtraControllerRejeitarMutationResponse =
  FolhaHoraExtraControllerRejeitar200;

export type FolhaHoraExtraControllerRejeitarMutation = {
  Response: FolhaHoraExtraControllerRejeitar200;
  Request: FolhaHoraExtraControllerRejeitarMutationRequest;
  PathParams: FolhaHoraExtraControllerRejeitarPathParams;
  Errors:
    | FolhaHoraExtraControllerRejeitar400
    | FolhaHoraExtraControllerRejeitar401
    | FolhaHoraExtraControllerRejeitar403
    | FolhaHoraExtraControllerRejeitar404;
};
