/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResRefeicaoFuncionarioDTODto } from './PaginatedResRefeicaoFuncionarioDTODto';

export enum FolhaHoraExtraControllerConsultarRefeicoesQueryParamsRefeicaoEnum {
  MARMITEX = 'MARMITEX',
  LANCHE = 'LANCHE',
  'N/A' = 'N/A',
}

export enum FolhaHoraExtraControllerConsultarRefeicoesQueryParamsStatusEnum {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_GERENCIA = 'AGUARDANDO_GERENCIA',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_GERENCIA = 'REJEITADO_GERENCIA',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type FolhaHoraExtraControllerConsultarRefeicoesQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Data inicial em ISO date. Sem datas, usa o dia atual.
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @description Data final em ISO date. Se omitida, usa a data inicial.
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @type number | undefined
   */
  centroCustoCodigo?: number;
  /**
   * @type string | undefined
   */
  matricula?: string;
  /**
   * @type string | undefined
   */
  nome?: string;
  /**
   * @type string | undefined
   */
  refeicao?: FolhaHoraExtraControllerConsultarRefeicoesQueryParamsRefeicaoEnum;
  /**
   * @description Se omitido, considera todos os status.
   * @type array | undefined
   */
  status?: FolhaHoraExtraControllerConsultarRefeicoesQueryParamsStatusEnum[];
};

/**
 * @description Lista paginada de refeicoes por funcionario.
 */
export type FolhaHoraExtraControllerConsultarRefeicoes200 =
  PaginatedResRefeicaoFuncionarioDTODto;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerConsultarRefeicoes401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerConsultarRefeicoes403 = any;

export type FolhaHoraExtraControllerConsultarRefeicoesQueryResponse =
  FolhaHoraExtraControllerConsultarRefeicoes200;

export type FolhaHoraExtraControllerConsultarRefeicoesQuery = {
  Response: FolhaHoraExtraControllerConsultarRefeicoes200;
  QueryParams: FolhaHoraExtraControllerConsultarRefeicoesQueryParams;
  Errors:
    | FolhaHoraExtraControllerConsultarRefeicoes401
    | FolhaHoraExtraControllerConsultarRefeicoes403;
};
