/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResFolhaHoraExtraDetalheDTO } from './ResFolhaHoraExtraDetalheDTO';

export type FolhaHoraExtraControllerAprovarPathParams = {
  /**
   * @description ID MongoDB da folha de hora extra.
   * @type string
   */
  id: string;
};

/**
 * @description Folha aprovada na etapa correspondente ao cargo do usuario.
 */
export type FolhaHoraExtraControllerAprovar200 = ResFolhaHoraExtraDetalheDTO;

/**
 * @description Cargo invalido para aprovacao ou transicao de status invalida para a etapa atual.
 */
export type FolhaHoraExtraControllerAprovar400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerAprovar401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerAprovar403 = any;

/**
 * @description Folha nao encontrada.
 */
export type FolhaHoraExtraControllerAprovar404 = any;

export type FolhaHoraExtraControllerAprovarMutationResponse =
  FolhaHoraExtraControllerAprovar200;

export type FolhaHoraExtraControllerAprovarMutation = {
  Response: FolhaHoraExtraControllerAprovar200;
  PathParams: FolhaHoraExtraControllerAprovarPathParams;
  Errors:
    | FolhaHoraExtraControllerAprovar400
    | FolhaHoraExtraControllerAprovar401
    | FolhaHoraExtraControllerAprovar403
    | FolhaHoraExtraControllerAprovar404;
};
