/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResFolhaHoraExtraDetalheDTO } from './ResFolhaHoraExtraDetalheDTO';

export type FolhaHoraExtraControllerSubmeterPathParams = {
  /**
   * @description ID MongoDB da folha de hora extra.
   * @type string
   */
  id: string;
};

/**
 * @description Folha submetida para aprovacao da gerencia.
 */
export type FolhaHoraExtraControllerSubmeter200 = ResFolhaHoraExtraDetalheDTO;

/**
 * @description Usuario sem permissao de submissao, folha vazia ou transicao de status invalida.
 */
export type FolhaHoraExtraControllerSubmeter400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerSubmeter401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerSubmeter403 = any;

/**
 * @description Folha nao encontrada.
 */
export type FolhaHoraExtraControllerSubmeter404 = any;

export type FolhaHoraExtraControllerSubmeterMutationResponse =
  FolhaHoraExtraControllerSubmeter200;

export type FolhaHoraExtraControllerSubmeterMutation = {
  Response: FolhaHoraExtraControllerSubmeter200;
  PathParams: FolhaHoraExtraControllerSubmeterPathParams;
  Errors:
    | FolhaHoraExtraControllerSubmeter400
    | FolhaHoraExtraControllerSubmeter401
    | FolhaHoraExtraControllerSubmeter403
    | FolhaHoraExtraControllerSubmeter404;
};
