/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResRelatorioHoraExtraDTO } from './ResRelatorioHoraExtraDTO';

export enum FolhaHoraExtraControllerRelatorioRecursosQueryParamsStatusEnum {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_GERENCIA = 'AGUARDANDO_GERENCIA',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_GERENCIA = 'REJEITADO_GERENCIA',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type FolhaHoraExtraControllerRelatorioRecursosQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Data inicial do periodo de referencia da folha, em ISO date.
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @description Data final do periodo de referencia da folha, em ISO date.
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @description Codigo do centro de custo para filtrar a consolidacao.
   * @type number | undefined
   */
  centroCustoCodigo?: number;
  /**
   * @description Status a consolidar. Se omitido, retorna somente folhas APROVADO.
   * @type array | undefined
   */
  status?: FolhaHoraExtraControllerRelatorioRecursosQueryParamsStatusEnum[];
};

/**
 * @description Relatorio agregado de recursos e detalhamento por setor.
 */
export type FolhaHoraExtraControllerRelatorioRecursos200 =
  ResRelatorioHoraExtraDTO;

/**
 * @description Usuario sem cargo previsto para consulta do relatorio de folhas HE.
 */
export type FolhaHoraExtraControllerRelatorioRecursos400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerRelatorioRecursos401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerRelatorioRecursos403 = any;

export type FolhaHoraExtraControllerRelatorioRecursosQueryResponse =
  FolhaHoraExtraControllerRelatorioRecursos200;

export type FolhaHoraExtraControllerRelatorioRecursosQuery = {
  Response: FolhaHoraExtraControllerRelatorioRecursos200;
  QueryParams: FolhaHoraExtraControllerRelatorioRecursosQueryParams;
  Errors:
    | FolhaHoraExtraControllerRelatorioRecursos400
    | FolhaHoraExtraControllerRelatorioRecursos401
    | FolhaHoraExtraControllerRelatorioRecursos403;
};
