/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResFolhaHoraExtraDTODto } from './PaginatedResFolhaHoraExtraDTODto';

export enum FolhaHoraExtraControllerHistoricoQueryParamsStatusEnum {
  AGUARDANDO_COORDENACAO = 'AGUARDANDO_COORDENACAO',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_COORDENACAO = 'REJEITADO_COORDENACAO',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type FolhaHoraExtraControllerHistoricoQueryParams = {
  /**
   * @description Pagina zero-based.
   * @type number | undefined
   */
  page?: number;
  /**
   * @description Quantidade de registros por pagina.
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Data inicial do periodo de referencia da folha, em ISO date.
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @description Data final do periodo de referencia da folha, em ISO date.
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @description Codigo do centro de custo para filtrar a listagem.
   * @type number | undefined
   */
  centroCustoCodigo?: number;
  /**
   * @description Status da folha. Se omitido, retorna todos os status historicos exceto RASCUNHO.
   * @type array | undefined
   */
  status?: FolhaHoraExtraControllerHistoricoQueryParamsStatusEnum[];
};

/**
 * @description Historico paginado de folhas HE para dashboard.
 */
export type FolhaHoraExtraControllerHistorico200 =
  PaginatedResFolhaHoraExtraDTODto;

/**
 * @description Usuario sem cargo previsto para consulta historica de folhas HE.
 */
export type FolhaHoraExtraControllerHistorico400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerHistorico401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerHistorico403 = any;

export type FolhaHoraExtraControllerHistoricoQueryResponse =
  FolhaHoraExtraControllerHistorico200;

export type FolhaHoraExtraControllerHistoricoQuery = {
  Response: FolhaHoraExtraControllerHistorico200;
  QueryParams: FolhaHoraExtraControllerHistoricoQueryParams;
  Errors:
    | FolhaHoraExtraControllerHistorico400
    | FolhaHoraExtraControllerHistorico401
    | FolhaHoraExtraControllerHistorico403;
};
