/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResLiderCentroCustoDTO } from './ResLiderCentroCustoDTO';

export type FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams = {
  /**
   * @description ID UUID do usuario lider.
   * @type string
   */
  usuarioId: string;
  /**
   * @description Codigo numerico do centro de custo.
   * @type number
   */
  centroCustoCodigo: number;
};

/**
 * @description Vinculo desativado com sucesso.
 */
export type FolhaHoraExtraControllerDesativarLiderCentroCusto200 =
  ResLiderCentroCustoDTO;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerDesativarLiderCentroCusto401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerDesativarLiderCentroCusto403 = any;

/**
 * @description Vinculo nao encontrado para o usuario e centro de custo informados.
 */
export type FolhaHoraExtraControllerDesativarLiderCentroCusto404 = any;

export type FolhaHoraExtraControllerDesativarLiderCentroCustoMutationResponse =
  FolhaHoraExtraControllerDesativarLiderCentroCusto200;

export type FolhaHoraExtraControllerDesativarLiderCentroCustoMutation = {
  Response: FolhaHoraExtraControllerDesativarLiderCentroCusto200;
  PathParams: FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams;
  Errors:
    | FolhaHoraExtraControllerDesativarLiderCentroCusto401
    | FolhaHoraExtraControllerDesativarLiderCentroCusto403
    | FolhaHoraExtraControllerDesativarLiderCentroCusto404;
};
