/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResKpiCustoFolhaHoraExtraDTO } from './ResKpiCustoFolhaHoraExtraDTO';

export enum FolhaHoraExtraKpiControllerCustoQueryParamsViewEnum {
  ano = 'ano',
  mes = 'mes',
  dia = 'dia',
}

export enum FolhaHoraExtraKpiControllerCustoQueryParamsGranularidadeEnum {
  ano = 'ano',
  mes = 'mes',
  dia = 'dia',
}

export type FolhaHoraExtraKpiControllerCustoQueryParams = {
  /**
   * @description Granularidade da série. O padrão é mes.
   * @type string | undefined
   */
  view?: FolhaHoraExtraKpiControllerCustoQueryParamsViewEnum;
  /**
   * @description Alias de view para selecionar a granularidade.
   * @type string | undefined
   */
  granularidade?: FolhaHoraExtraKpiControllerCustoQueryParamsGranularidadeEnum;
  /**
   * @description Data de referência do ano, mês ou dia. O padrão é hoje.
   * @type string | undefined
   */
  dataReferencia?: string;
  /**
   * @description Início do intervalo. Deve ser usado junto com dataFim.
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @description Fim do intervalo. Deve ser usado junto com dataInicio.
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @description Código do centro de custo para filtrar o custo.
   * @type number | undefined
   */
  centroCustoCodigo?: number;
};

/**
 * @description Série de custos, incluindo períodos sem folhas com valor R$ 0,00.
 */
export type FolhaHoraExtraKpiControllerCusto200 = ResKpiCustoFolhaHoraExtraDTO;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraKpiControllerCusto401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraKpiControllerCusto403 = any;

export type FolhaHoraExtraKpiControllerCustoQueryResponse =
  FolhaHoraExtraKpiControllerCusto200;

export type FolhaHoraExtraKpiControllerCustoQuery = {
  Response: FolhaHoraExtraKpiControllerCusto200;
  QueryParams: FolhaHoraExtraKpiControllerCustoQueryParams;
  Errors:
    | FolhaHoraExtraKpiControllerCusto401
    | FolhaHoraExtraKpiControllerCusto403;
};
