/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResKpiJornadaFolhaHoraExtraDTO } from './ResKpiJornadaFolhaHoraExtraDTO';

export type FolhaHoraExtraKpiControllerJornada200 =
  ResKpiJornadaFolhaHoraExtraDTO;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraKpiControllerJornada401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraKpiControllerJornada403 = any;

export type FolhaHoraExtraKpiControllerJornadaQueryResponse =
  FolhaHoraExtraKpiControllerJornada200;

export type FolhaHoraExtraKpiControllerJornadaQuery = {
  Response: FolhaHoraExtraKpiControllerJornada200;
  Errors:
    | FolhaHoraExtraKpiControllerJornada401
    | FolhaHoraExtraKpiControllerJornada403;
};
