/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResKpiCumprimentoFolhaHoraExtraDTO } from './ResKpiCumprimentoFolhaHoraExtraDTO';

export type FolhaHoraExtraControllerConsultarKpiCumprimentoPathParams = {
  /**
   * @description ID MongoDB da folha de hora extra.
   * @type string
   */
  id: string;
};

/**
 * @description KPI de cumprimento de HE calculada por funcionario da folha.
 */
export type FolhaHoraExtraControllerConsultarKpiCumprimento200 =
  ResKpiCumprimentoFolhaHoraExtraDTO;

/**
 * @description Usuario nao pode consultar esta KPI da folha ou horario de HE invalido.
 */
export type FolhaHoraExtraControllerConsultarKpiCumprimento400 = any;

/**
 * @description Token JWT ausente, invalido ou expirado.
 */
export type FolhaHoraExtraControllerConsultarKpiCumprimento401 = any;

/**
 * @description Usuario autenticado nao possui cargo permitido para o endpoint.
 */
export type FolhaHoraExtraControllerConsultarKpiCumprimento403 = any;

/**
 * @description Folha nao encontrada.
 */
export type FolhaHoraExtraControllerConsultarKpiCumprimento404 = any;

export type FolhaHoraExtraControllerConsultarKpiCumprimentoQueryResponse =
  FolhaHoraExtraControllerConsultarKpiCumprimento200;

export type FolhaHoraExtraControllerConsultarKpiCumprimentoQuery = {
  Response: FolhaHoraExtraControllerConsultarKpiCumprimento200;
  PathParams: FolhaHoraExtraControllerConsultarKpiCumprimentoPathParams;
  Errors:
    | FolhaHoraExtraControllerConsultarKpiCumprimento400
    | FolhaHoraExtraControllerConsultarKpiCumprimento401
    | FolhaHoraExtraControllerConsultarKpiCumprimento403
    | FolhaHoraExtraControllerConsultarKpiCumprimento404;
};
