/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResPontoFuncionarioDTODto } from './PaginatedResPontoFuncionarioDTODto';

export type FuncionarioControllerConsultaFuncionariosMethodQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Filtro por centro de custo (RA_CC)
   * @type string | undefined
   */
  RA_CC?: string;
  /**
   * @description Filtro por cpf
   * @type string | undefined
   */
  CPF?: string;
  /**
   * @description Filtro por PIS
   * @type string | undefined
   */
  PIS?: string;
  /**
   * @description Filtro por matricula
   * @type string | undefined
   */
  matricula?: string;
  /**
   * @description Filtro por nome do funcionário
   * @type string | undefined
   */
  nome?: string;
};

export type FuncionarioControllerConsultaFuncionariosMethodError =
  PaginatedResPontoFuncionarioDTODto;

export type FuncionarioControllerConsultaFuncionariosMethodQueryResponse = any;

export type FuncionarioControllerConsultaFuncionariosMethodQuery = {
  Response: any;
  QueryParams: FuncionarioControllerConsultaFuncionariosMethodQueryParams;
  Errors: any;
};
