/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResTurnoFuncionarioDTO } from './ResTurnoFuncionarioDTO';

export type FuncionarioControllerConsultarTurnoFuncionarioPathParams = {
  /**
   * @type string
   */
  matricula: string;
};

export type FuncionarioControllerConsultarTurnoFuncionarioError =
  ResTurnoFuncionarioDTO;

export type FuncionarioControllerConsultarTurnoFuncionarioQueryResponse = any;

export type FuncionarioControllerConsultarTurnoFuncionarioQuery = {
  Response: any;
  PathParams: FuncionarioControllerConsultarTurnoFuncionarioPathParams;
  Errors: any;
};
