/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResFuncionarioListagemDTODto } from './PaginatedResFuncionarioListagemDTODto';
import type { _Object } from './_Object';

export type FuncionarioControllerConsultaFuncionariosLegadoQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Filtro por centro de custo (RA_CC)
   * @type object | undefined
   */
  RA_CC?: _Object;
  /**
   * @description Alias do centro de custo usado por integracoes antigas
   * @type object | undefined
   */
  ccid?: _Object;
  /**
   * @description Alias explicito do centro de custo
   * @type object | undefined
   */
  centroCustoCodigo?: _Object;
  /**
   * @description Filtro por cpf
   * @type string | undefined
   */
  CPF?: string;
  /**
   * @description Filtro por PIS
   * @type string | undefined
   */
  PIS?: string;
  /**
   * @description Filtro por matricula
   * @type string | undefined
   */
  matricula?: string;
  /**
   * @description Filtro por nome do funcionário
   * @type string | undefined
   */
  nome?: string;
};

export type FuncionarioControllerConsultaFuncionariosLegadoError =
  PaginatedResFuncionarioListagemDTODto;

export type FuncionarioControllerConsultaFuncionariosLegadoQueryResponse = any;

export type FuncionarioControllerConsultaFuncionariosLegadoQuery = {
  Response: any;
  QueryParams: FuncionarioControllerConsultaFuncionariosLegadoQueryParams;
  Errors: any;
};
