/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResPresencaFuncionarioDTODto } from './PaginatedResPresencaFuncionarioDTODto';
import type { _Object } from './_Object';

export enum FuncionarioControllerConsultarPresencaFuncionariosQueryParamsStatusEnum {
  PRESENTE = 'PRESENTE',
  NAO_PRESENTE = 'NAO_PRESENTE',
  FORA_DO_TURNO = 'FORA_DO_TURNO',
  FERIAS = 'FERIAS',
}

export type FuncionarioControllerConsultarPresencaFuncionariosQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description PRESENTE quando a última marcação de hoje é uma entrada; NAO_PRESENTE durante a janela de trabalho sem presença; FORA_DO_TURNO fora dessa janela; FERIAS quando RA_SITFOLH é F. Sem filtro, retorna todos os funcionários ativos.
   * @type string | undefined
   */
  status?: FuncionarioControllerConsultarPresencaFuncionariosQueryParamsStatusEnum;
  /**
   * @description Filtro parcial por nome
   * @type string | undefined
   */
  nome?: string;
  /**
   * @description Alias de nome para compatibilidade com integrações
   * @type string | undefined
   */
  name?: string;
  /**
   * @description Matrícula, CPF ou PIS do funcionário
   * @type string | undefined
   */
  identificador?: string;
  /**
   * @description Alias legado de identificador usado pela API de marcações
   * @type string | undefined
   */
  indetificador?: string;
  /**
   * @description Filtro exato por matrícula
   * @type string | undefined
   */
  matricula?: string;
  /**
   * @description Filtro exato por CPF
   * @type string | undefined
   */
  CPF?: string;
  /**
   * @description Filtro exato por PIS
   * @type string | undefined
   */
  PIS?: string;
  /**
   * @description Filtro por centro de custo
   * @type object | undefined
   */
  RA_CC?: _Object;
  /**
   * @description Alias de RA_CC
   * @type object | undefined
   */
  ccid?: _Object;
  /**
   * @description Alias de RA_CC
   * @type object | undefined
   */
  centroCustoCodigo?: _Object;
};

export type FuncionarioControllerConsultarPresencaFuncionariosError =
  PaginatedResPresencaFuncionarioDTODto;

export type FuncionarioControllerConsultarPresencaFuncionariosQueryResponse =
  any;

export type FuncionarioControllerConsultarPresencaFuncionariosQuery = {
  Response: any;
  QueryParams: FuncionarioControllerConsultarPresencaFuncionariosQueryParams;
  Errors: any;
};
