/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ItemFuncionarioHEDTOTransporteEnum {
  UBER = 'UBER',
  TAXI = 'TAXI',
  FRETADO = 'FRETADO',
  'N/A' = 'N/A',
}

export enum ItemFuncionarioHEDTORefeicaoEnum {
  MARMITEX = 'MARMITEX',
  LANCHE = 'LANCHE',
  'N/A' = 'N/A',
}

export type ItemFuncionarioHEDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @default "N/A"
   * @type string | undefined
   */
  transporte?: ItemFuncionarioHEDTOTransporteEnum;
  /**
   * @type string
   */
  inicioHE: string;
  /**
   * @type string
   */
  fimHE: string;
  /**
   * @default "N/A"
   * @type string | undefined
   */
  refeicao?: ItemFuncionarioHEDTORefeicaoEnum;
  /**
   * @type string
   */
  justificativa: string;
};
