/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type KpiCustoFolhaHoraExtraCentroCustoDTO = {
  /**
   * @type number
   */
  codigo: number;
  /**
   * @type string
   */
  descricao: string;
  /**
   * @type number
   */
  custo: number;
  /**
   * @type string
   */
  custoFormatado: string;
  /**
   * @type number
   */
  quantidadeFolhas: number;
};
