/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type KpiJornadaFolhaHoraExtraCentroCustoDTO = {
  /**
   * @type number
   */
  codigo: number;
  /**
   * @type string
   */
  descricao: string;
};
