/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KpiJornadaFolhaHoraExtraCentroCustoDTO } from './KpiJornadaFolhaHoraExtraCentroCustoDTO';

export type KpiJornadaFolhaHoraExtraFuncionarioDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type array
   */
  centrosCusto: KpiJornadaFolhaHoraExtraCentroCustoDTO[];
  /**
   * @type number
   */
  ocorrenciasNaoCumprimento: number;
  /**
   * @type number
   */
  ocorrenciasExtrapolacao: number;
  /**
   * @type number
   */
  minutosIrregularesNaoCumprimentoHE: number;
  /**
   * @type number
   */
  minutosIrregularesExtrapolacaoHE: number;
  /**
   * @type number
   */
  minutosExcedentesHE: number;
};
