/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type KpiJornadaFolhaHoraExtraDiaDTO = {
  /**
   * @type string
   */
  data: string;
  /**
   * @type number
   */
  totalProgramados: number;
  /**
   * @type number
   */
  totalNaoCumpriram: number;
  /**
   * @type number
   */
  totalExtrapolaram: number;
  /**
   * @description Minutos irregulares por entrada após o início ou saída antes do fim da HE.
   * @type number
   */
  minutosIrregularesNaoCumprimentoHE: number;
  /**
   * @description Minutos irregulares por saída após o fim da HE.
   * @type number
   */
  minutosIrregularesExtrapolacaoHE: number;
  /**
   * @description Minutos trabalhados após o fim de HE previsto.
   * @type number
   */
  minutosExcedentesHE: number;
};
