/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResFolhaHoraExtraDTO } from './ResFolhaHoraExtraDTO';

export type PaginatedResFolhaHoraExtraDTODto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ResFolhaHoraExtraDTO.
   * @type array
   */
  data: ResFolhaHoraExtraDTO[];
};
