/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResFuncionarioListagemDTO } from './ResFuncionarioListagemDTO';

export type PaginatedResFuncionarioListagemDTODto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ResFuncionarioListagemDTO.
   * @type array
   */
  data: ResFuncionarioListagemDTO[];
};
