/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResPresencaFuncionarioDTO } from './ResPresencaFuncionarioDTO';

export type PaginatedResPresencaFuncionarioDTODto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ResPresencaFuncionarioDTO.
   * @type array
   */
  data: ResPresencaFuncionarioDTO[];
};
