/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResPontoFuncionarioDTO } from "./ResPontoFuncionarioDTO";

export type PaginatedResPontoFuncionarioDTODto = {
    /**
     * @type number
    */
    total: number;
    /**
     * @type number
    */
    page: number;
    /**
     * @type number
    */
    limit: number;
    /**
     * @type number
    */
    totalPages: number;
    /**
     * @description Lista de itens paginados do tipo ResPontoFuncionarioDTO.
     * @type array
    */
    data: ResPontoFuncionarioDTO[];
};