/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResRegistroPontoTurnoPontoDTO } from './ResRegistroPontoTurnoPontoDTO';

export type PaginatedResRegistroPontoTurnoPontoDTODto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ResRegistroPontoTurnoPontoDTO.
   * @type array
   */
  data: ResRegistroPontoTurnoPontoDTO[];
};
