/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResRegistroPontoTurnoPontoDTODto } from './PaginatedResRegistroPontoTurnoPontoDTODto';

export type PontoControllerConsultaMarcacaoMethodQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Identificador do funcionário : nome, matrícula, CPF ou PIS
   * @type string | undefined
   */
  indetificador?: string;
  /**
   * @description Identificador do centro de custo
   * @type array | undefined
   */
  ccid?: string[];
  /**
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @description Quantidade mínima de horas trabalhadas no turno para filtrar o KPI.
   * @type number | undefined
   */
  horasTrabalhadasMin?: number;
  /**
   * @description Quantidade máxima de horas trabalhadas no turno para filtrar o KPI.
   * @type number | undefined
   */
  horasTrabalhadasMax?: number;
};

export type PontoControllerConsultaMarcacaoMethodError =
  PaginatedResRegistroPontoTurnoPontoDTODto[];

export type PontoControllerConsultaMarcacaoMethodQueryResponse = any;

export type PontoControllerConsultaMarcacaoMethodQuery = {
  Response: any;
  QueryParams: PontoControllerConsultaMarcacaoMethodQueryParams;
  Errors: any;
};
