/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResHorasIrregularesDTO } from './ResHorasIrregularesDTO';

export type PontoKPIControllerConsultarMaisHorasIrregularesQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Identificador do funcionário : nome, matrícula, CPF ou PIS
   * @type string | undefined
   */
  indetificador?: string;
  /**
   * @description Identificador do centro de custo
   * @type array | undefined
   */
  ccid?: string[];
  /**
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @type string | undefined
   */
  dataFim?: string;
};

export type PontoKPIControllerConsultarMaisHorasIrregularesError =
  ResHorasIrregularesDTO[];

export type PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse = any;

export type PontoKPIControllerConsultarMaisHorasIrregularesQuery = {
  Response: any;
  QueryParams: PontoKPIControllerConsultarMaisHorasIrregularesQueryParams;
  Errors: any;
};
