/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResPontoRegistroDTO } from './ResPontoRegistroDTO';

export type PontoControllerSicnronizaPontoMethodError = ResPontoRegistroDTO[];

export type PontoControllerSicnronizaPontoMethodMutationResponse = any;

export type PontoControllerSicnronizaPontoMethodMutation = {
  Response: any;
  Errors: any;
};
