/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResPontoRegistroDTO } from "./ResPontoRegistroDTO";

export type PontoControllerProcessaTipoMarcacaoMethodError = ResPontoRegistroDTO[];

export type PontoControllerProcessaTipoMarcacaoMethodMutationRequest = ResPontoRegistroDTO[];

export type PontoControllerProcessaTipoMarcacaoMethodMutationResponse = any;

export type PontoControllerProcessaTipoMarcacaoMethodMutation = {
    Response: any;
    Request: PontoControllerProcessaTipoMarcacaoMethodMutationRequest;
    Errors: any;
};