/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResHorasIrregularesDTO } from './ResHorasIrregularesDTO';

export type PontoKPIControllerConsultarMaisHorasIrregularesQueryParams = {
  /**
   * @description Identificador do funcionário : nome, matrícula, CPF ou PIS
   * @type string | undefined
   */
  indetificador?: string;
  /**
   * @description Identificador do centro de custo
   * @type array | undefined
   */
  ccid?: string[];
  /**
   * @type string | undefined
   */
  dataInicio?: string;
  /**
   * @type string | undefined
   */
  dataFim?: string;
  /**
   * @description Quantidade mínima de horas trabalhadas no turno para filtrar o KPI.
   * @type number | undefined
   */
  horasTrabalhadasMin?: number;
  /**
   * @description Quantidade máxima de horas trabalhadas no turno para filtrar o KPI.
   * @type number | undefined
   */
  horasTrabalhadasMax?: number;
  /**
   * @default 1
   * @type number | undefined
   */
  page?: number;
  /**
   * @maxLength 9999
   * @default 20
   * @type number | undefined
   */
  limit?: number;
};

export type PontoKPIControllerConsultarMaisHorasIrregularesError =
  ResHorasIrregularesDTO[];

export type PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse = any;

export type PontoKPIControllerConsultarMaisHorasIrregularesQuery = {
  Response: any;
  QueryParams: PontoKPIControllerConsultarMaisHorasIrregularesQueryParams;
  Errors: any;
};
