/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResCentroDeCustoDTO = {
  /**
   * @type string
   */
  setor: string;
  /**
   * @type number
   */
  ccid: number;
};
