/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResExtratoCustoHoraExtraLinhaDTO } from './ResExtratoCustoHoraExtraLinhaDTO';

export type ResExtratoCustoFuncionarioHoraExtraDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type number
   */
  salarioHora: number;
  /**
   * @type number
   */
  multiplicadorCompensacao: number;
  /**
   * @type number
   */
  adicionalNoturno: number;
  /**
   * @type number
   */
  horasDiurnas: number;
  /**
   * @type number
   */
  horasNoturnas: number;
  /**
   * @type number
   */
  valorHoraDiurnaComEncargo: number;
  /**
   * @type number
   */
  valorHoraNoturnaComEncargo: number;
  /**
   * @type number
   */
  valorHorasDiurnas: number;
  /**
   * @type number
   */
  valorHorasNoturnas: number;
  /**
   * @type number
   */
  refeicao: number;
  /**
   * @type number
   */
  transporte: number;
  /**
   * @type number
   */
  total: number;
  /**
   * @type array
   */
  linhas: ResExtratoCustoHoraExtraLinhaDTO[];
};
