/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResExtratoCustoFuncionarioHoraExtraDTO } from './ResExtratoCustoFuncionarioHoraExtraDTO';

export type ResExtratoCustoHoraExtraDTO = {
  /**
   * @type string | undefined
   */
  folhaId?: string;
  /**
   * @type array
   */
  funcionarios: ResExtratoCustoFuncionarioHoraExtraDTO[];
  /**
   * @type number
   */
  quantidadeFuncionarios: number;
  /**
   * @type number
   */
  multiplicadorAdicionalHE: number;
  /**
   * @type number
   */
  adicionalNoturno: number;
  /**
   * @type number
   */
  totalRefeicao: number;
  /**
   * @type number
   */
  totalTransporte: number;
  /**
   * @type number
   */
  totalEncargo: number;
  /**
   * @type number
   */
  totalHorasDiurnas: number;
  /**
   * @type number
   */
  totalHorasNoturnas: number;
  /**
   * @type number
   */
  totalHorasExtras: number;
  /**
   * @type number
   */
  totalHorasDiurnasValor: number;
  /**
   * @type number
   */
  totalHorasNoturnasValor: number;
  /**
   * @type number
   */
  totalGeral: number;
};
