/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ResEventoHoraExtraNaoAutorizadaDTOOrigemEnum {
  SPC010 = 'SPC010',
  SPH010 = 'SPH010',
}

export type ResEventoHoraExtraNaoAutorizadaDTO = {
  /**
   * @type string
   */
  data: string;
  /**
   * @type string
   */
  evento: string;
  /**
   * @description Descrição do evento cadastrada na SP9.
   * @type string
   */
  nomeEvento: string;
  /**
   * @type string
   */
  tipoHoraExtra: string;
  /**
   * @type number
   */
  quantidade: number;
  /**
   * @type object
   */
  percentual: object | null;
  /**
   * @type string
   */
  origem: ResEventoHoraExtraNaoAutorizadaDTOOrigemEnum;
};
