/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResExtratoCustoHoraExtraLinhaDTO = {
  /**
   * @type string
   */
  componente: string;
  /**
   * @type string
   */
  baseCalculo: string;
  /**
   * @type number
   */
  quantidade: number;
  /**
   * @type number
   */
  valorUnitario: number;
  /**
   * @type number
   */
  subtotal: number;
};
