/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResFuncionarioListagemDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @description Código do turno base cadastrado para o funcionário
   * @type string
   */
  turnoBase: string;
  /**
   * @description Indica se o funcionario veio da planilha de temporarios
   * @type boolean
   */
  temporario: boolean;
};
