/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResAssinaturaAprovacaoDTO } from './ResAssinaturaAprovacaoDTO';
import type { ResExtratoCustoHoraExtraDTO } from './ResExtratoCustoHoraExtraDTO';
import type { ResItemFuncionarioHEDTO } from './ResItemFuncionarioHEDTO';

export enum ResFolhaHoraExtraDetalheDTOPercentualCustoEnum {
  ResFolhaHoraExtraDetalheDTOPercentualCustoEnum_50 = 50,
  ResFolhaHoraExtraDetalheDTOPercentualCustoEnum_100 = 100,
}

export enum ResFolhaHoraExtraDetalheDTOStatusEnum {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_COORDENACAO = 'AGUARDANDO_COORDENACAO',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_COORDENACAO = 'REJEITADO_COORDENACAO',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type ResFolhaHoraExtraDetalheDTO = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string, date-time
   */
  dataContexto: Date;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type string
   */
  centroCustoDescricao: string;
  /**
   * @type number
   */
  percentualCusto: ResFolhaHoraExtraDetalheDTOPercentualCustoEnum;
  /**
   * @type string
   */
  status: ResFolhaHoraExtraDetalheDTOStatusEnum;
  /**
   * @type number
   */
  totalFuncionarios: number;
  /**
   * @type string
   */
  autorNome: string;
  /**
   * @type string, date-time
   */
  criadoEm: Date;
  /**
   * @type string, date-time
   */
  atualizadoEm: Date;
  /**
   * @type array
   */
  funcionarios: ResItemFuncionarioHEDTO[];
  /**
   * @type string | undefined
   */
  observacao?: string;
  /**
   * @type array
   */
  historico: ResAssinaturaAprovacaoDTO[];
  /**
   * @type string
   */
  autorId: string;
  /**
   * @type object | undefined
   */
  extratoCusto?: ResExtratoCustoHoraExtraDTO;
};
