/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResTipoMarcacaoDTO } from './ResTipoMarcacaoDTO';

export type ResFuncionarioKpiCumprimentoFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  inicioHEPrevisto: string;
  /**
   * @type string
   */
  fimHEPrevisto: string;
  /**
   * @type string
   */
  totalHEPrevisto: string;
  /**
   * @type string | undefined, date-time
   */
  primeiraBatida?: Date;
  /**
   * @type string | undefined, date-time
   */
  ultimaBatida?: Date;
  /**
   * @type number
   */
  horasTrabalhadasNoTurno: number;
  /**
   * @type number
   */
  minutosAtrasoInicioHE: number;
  /**
   * @type number
   */
  minutosSaidaAntesFimHE: number;
  /**
   * @type boolean
   */
  cumpriuHorarioHE: boolean;
  /**
   * @type array
   */
  registros: ResTipoMarcacaoDTO[];
};
