/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResTipoMarcacaoDTO } from './ResTipoMarcacaoDTO';

export enum ResFuncionarioKpiCumprimentoFolhaHoraExtraDTOStatusCumprimentoHEEnum {
  CUMPRIU = 'CUMPRIU',
  NAO_CUMPRIU = 'NAO_CUMPRIU',
  EXTRAPOLOU = 'EXTRAPOLOU',
}

export type ResFuncionarioKpiCumprimentoFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @description Indica que o funcionario e temporario e nao entra no calculo de batidas.
   * @type boolean
   */
  temporario: boolean;
  /**
   * @type string
   */
  inicioHEPrevisto: string;
  /**
   * @type string
   */
  fimHEPrevisto: string;
  /**
   * @type string
   */
  totalHEPrevisto: string;
  /**
   * @type string | undefined, date-time
   */
  primeiraBatida?: Date;
  /**
   * @type string | undefined, date-time
   */
  ultimaBatida?: Date;
  /**
   * @type number
   */
  horasTrabalhadasNoTurno: number;
  /**
   * @type number
   */
  minutosAtrasoInicioHE: number;
  /**
   * @type number
   */
  minutosSaidaAntesFimHE: number;
  /**
   * @type boolean
   */
  cumpriuHorarioHE: boolean;
  /**
   * @description CUMPRIU: saída entre 10 minutos antes e 15 minutos depois do fim previsto; EXTRAPOLOU: saída após essa tolerância.
   * @type string | undefined
   */
  statusCumprimentoHE?: ResFuncionarioKpiCumprimentoFolhaHoraExtraDTOStatusCumprimentoHEEnum;
  /**
   * @type array
   */
  registros: ResTipoMarcacaoDTO[];
};
