/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ResFolhaHoraExtraDTOPercentualCustoEnum {
  ResFolhaHoraExtraDTOPercentualCustoEnum_50 = 50,
  ResFolhaHoraExtraDTOPercentualCustoEnum_100 = 100,
}

export enum ResFolhaHoraExtraDTOStatusEnum {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_GERENCIA = 'AGUARDANDO_GERENCIA',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_GERENCIA = 'REJEITADO_GERENCIA',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type ResFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string, date-time
   */
  dataContexto: Date;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type string
   */
  centroCustoDescricao: string;
  /**
   * @type number
   */
  percentualCusto: ResFolhaHoraExtraDTOPercentualCustoEnum;
  /**
   * @type string
   */
  status: ResFolhaHoraExtraDTOStatusEnum;
  /**
   * @type number
   */
  totalFuncionarios: number;
  /**
   * @type string
   */
  autorNome: string;
  /**
   * @type string, date-time
   */
  criadoEm: Date;
  /**
   * @type string, date-time
   */
  atualizadoEm: Date;
};
