/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEventoHoraExtraNaoAutorizadaDTO } from './ResEventoHoraExtraNaoAutorizadaDTO';

export type ResHorasExtrasNaoAutorizadasDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type object
   */
  ccid: object | null;
  /**
   * @type number
   */
  totalHoras: number;
  /**
   * @type array
   */
  eventos: ResEventoHoraExtraNaoAutorizadaDTO[];
};
