/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResHorasIrregularesDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @description Código do centro de custo do funcionário.
   * @type object
   */
  ccid: object | null;
  /**
   * @type number
   */
  horasIrregulares: number;
};
