/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KpiJornadaFolhaHoraExtraDiaDTO } from './KpiJornadaFolhaHoraExtraDiaDTO';
import type { KpiJornadaFolhaHoraExtraFuncionarioDTO } from './KpiJornadaFolhaHoraExtraFuncionarioDTO';

export type ResKpiJornadaFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  dataInicio: string;
  /**
   * @type string
   */
  dataFim: string;
  /**
   * @type number
   */
  totalProgramados: number;
  /**
   * @type number
   */
  totalNaoCumpriram: number;
  /**
   * @type number
   */
  totalExtrapolaram: number;
  /**
   * @type number
   */
  minutosIrregularesNaoCumprimentoHE: number;
  /**
   * @type number
   */
  minutosIrregularesExtrapolacaoHE: number;
  /**
   * @type number
   */
  minutosExcedentesHE: number;
  /**
   * @type array
   */
  dias: KpiJornadaFolhaHoraExtraDiaDTO[];
  /**
   * @type array
   */
  funcionariosComMaisOcorrencias: KpiJornadaFolhaHoraExtraFuncionarioDTO[];
};
