/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KpiCustoFolhaHoraExtraPeriodoDTO } from './KpiCustoFolhaHoraExtraPeriodoDTO';

export enum ResKpiCustoFolhaHoraExtraDTOViewEnum {
  ano = 'ano',
  mes = 'mes',
  dia = 'dia',
}

export type ResKpiCustoFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  moeda: string;
  /**
   * @type string
   */
  view: ResKpiCustoFolhaHoraExtraDTOViewEnum;
  /**
   * @type string
   */
  dataInicio: string;
  /**
   * @type string
   */
  dataFim: string;
  /**
   * @description Custo total do período em reais.
   * @type number
   */
  custoTotal: number;
  /**
   * @type string
   */
  custoTotalFormatado: string;
  /**
   * @type array
   */
  periodos: KpiCustoFolhaHoraExtraPeriodoDTO[];
};
