/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResFuncionarioKpiCumprimentoFolhaHoraExtraDTO } from './ResFuncionarioKpiCumprimentoFolhaHoraExtraDTO';

export type ResKpiCumprimentoFolhaHoraExtraDTO = {
  /**
   * @type string
   */
  folhaId: string;
  /**
   * @type string, date-time
   */
  dataContexto: Date;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type string
   */
  centroCustoDescricao: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type number
   */
  totalFuncionarios: number;
  /**
   * @type number
   */
  totalCumpriram: number;
  /**
   * @type number
   */
  totalNaoCumpriram: number;
  /**
   * @type number
   */
  percentualCumprimento: number;
  /**
   * @type array
   */
  funcionarios: ResFuncionarioKpiCumprimentoFolhaHoraExtraDTO[];
};
