/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResLiderCentroCustoDTO = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  usuarioId: string;
  /**
   * @type string
   */
  usuarioNome: string;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type string
   */
  centroCustoDescricao: string;
  /**
   * @type boolean
   */
  ativo: boolean;
};
