/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ResPresencaFuncionarioDTOStatusEnum {
  PRESENTE = 'PRESENTE',
  NAO_PRESENTE = 'NAO_PRESENTE',
  FORA_DO_TURNO = 'FORA_DO_TURNO',
  FERIAS = 'FERIAS',
  AFASTADO = 'AFASTADO',
}

export type ResPresencaFuncionarioDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type string
   */
  turnoBase: string;
  /**
   * @description Primeiro horário de entrada previsto no turno do dia.
   * @type object
   */
  entradaTurnoBase: object | null;
  /**
   * @description Último horário de saída previsto no turno do dia.
   * @type object
   */
  saidaTurnoBase: object | null;
  /**
   * @description Indica se a última marcação válida do dia é uma entrada.
   * @type boolean
   */
  presente: boolean;
  /**
   * @description Situação atual calculada a partir da última batida e do turno do dia.
   * @type string
   */
  status: ResPresencaFuncionarioDTOStatusEnum;
  /**
   * @description Indica se o funcionário está de férias (RA_SITFOLH = F).
   * @type boolean
   */
  ferias: boolean;
};
