/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResponsePaginatorDTO = {
    /**
     * @type number
    */
    total: number;
    /**
     * @type number
    */
    page: number;
    /**
     * @type number
    */
    limit: number;
    /**
     * @type number
    */
    totalPages: number;
};