/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResPontoRegistroDTO = {
    /**
     * @type number
    */
    id: number;
    /**
     * @type string
    */
    mat: string;
    /**
     * @type string
    */
    nome: string;
    /**
     * @type string
    */
    pis: string;
    /**
     * @type string
    */
    cpf: string;
    /**
     * @type string, date-time
    */
    data: Date;
    /**
     * @type string
    */
    hora: string;
    /**
     * @type number
    */
    horaNumber: number;
    /**
     * @type string, date-time
    */
    dataHoraAr: Date;
};