/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResPontoFuncionarioDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  setor: string;
};
