/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResTipoMarcacaoDTO } from './ResTipoMarcacaoDTO';
import type { ResTurnoDTO } from './ResTurnoDTO';

export enum ResRegistroPontoTurnoPontoDTOStatusEnum {
  OK = 'OK',
  ALERTA = 'ALERTA',
  FALHA = 'FALHA',
}

export type ResRegistroPontoTurnoPontoDTO = {
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @description Jornada-base aplicável ao dia da marcação, obtida da SPJ010 pelo código RA_TNOTRAB.
   * @type object
   */
  turnoBase: ResTurnoDTO | null;
  /**
   * @type string, date-time
   */
  turnoDia: Date;
  /**
   * @type string
   */
  turnoDiaStr: string;
  /**
   * @type array
   */
  registros: ResTipoMarcacaoDTO[];
  /**
   * @type number
   */
  qtdHoras: number;
  /**
   * @type number
   */
  horasIrregulares: number;
  /**
   * @description FALHA para marcações inválidas; ALERTA para excesso de horas; OK nos demais casos.
   * @type string
   */
  status: ResRegistroPontoTurnoPontoDTOStatusEnum;
};
