/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ResRefeicaoFuncionarioDTORefeicaoEnum {
  MARMITEX = 'MARMITEX',
  LANCHE = 'LANCHE',
  'N/A' = 'N/A',
}

export enum ResRefeicaoFuncionarioDTOStatusEnum {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_GERENCIA = 'AGUARDANDO_GERENCIA',
  AGUARDANDO_DIRETORIA = 'AGUARDANDO_DIRETORIA',
  APROVADO = 'APROVADO',
  REJEITADO_GERENCIA = 'REJEITADO_GERENCIA',
  REJEITADO_DIRETORIA = 'REJEITADO_DIRETORIA',
}

export type ResRefeicaoFuncionarioDTO = {
  /**
   * @type string
   */
  folhaId: string;
  /**
   * @type string, date-time
   */
  dataContexto: Date;
  /**
   * @type number
   */
  centroCustoCodigo: number;
  /**
   * @type string
   */
  centroCustoDescricao: string;
  /**
   * @type string
   */
  setor: string;
  /**
   * @type string
   */
  matricula: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  refeicao: ResRefeicaoFuncionarioDTORefeicaoEnum;
  /**
   * @type string
   */
  inicioHE: string;
  /**
   * @type string
   */
  fimHE: string;
  /**
   * @type string
   */
  justificativa: string;
  /**
   * @type string
   */
  status: ResRefeicaoFuncionarioDTOStatusEnum;
  /**
   * @type string
   */
  autorNome: string;
  /**
   * @type string | undefined
   */
  observacao?: string;
};
