/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResTipoMarcacaoDTO = {
    /**
     * @type number
    */
    id: number;
    /**
     * @type string
    */
    marcacao: string;
    /**
     * @type string
    */
    dataStr: string;
    /**
     * @type string, date-time
    */
    data: Date;
};