/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileGaleriaControllerListReportFotosQueryResponse,
  MobileGaleriaControllerListReportFotosQueryParams,
} from '../models/MobileGaleriaControllerListReportFotos';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileGaleriaControllerListReportFotosUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/report-fotos` as const,
  };
  return res;
}

/**
 * @description Ao informar serialNumber e codItem, inclui as inspeções do item selecionado e do respectivo ROPS retornado pela Estrutura.
 * @summary Lista reports de fotos com paginação e filtros dinâmicos
 * {@link /api/mobile/galeria/report-fotos}
 */
export async function mobileGaleriaControllerListReportFotos(
  params?: MobileGaleriaControllerListReportFotosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileGaleriaControllerListReportFotosQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getMobileGaleriaControllerListReportFotosUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
