/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileImpressoraControllerRemoveMutationResponse,
  MobileImpressoraControllerRemovePathParams,
  MobileImpressoraControllerRemove404,
} from '../models/MobileImpressoraControllerRemove';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileImpressoraControllerRemoveUrl(
  id: MobileImpressoraControllerRemovePathParams['id'],
) {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/mobile/impressora-bluetooth/${id}` as const,
  };
  return res;
}

/**
 * @description Remove do cadastro a impressora Bluetooth identificada pelo ID informado.
 * @summary Deleta uma impressora Bluetooth
 * {@link /api/mobile/impressora-bluetooth/:id}
 */
export async function mobileImpressoraControllerRemove(
  id: MobileImpressoraControllerRemovePathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileImpressoraControllerRemoveMutationResponse,
    ResponseErrorConfig<MobileImpressoraControllerRemove404>,
    unknown
  >({
    method: 'DELETE',
    url: getMobileImpressoraControllerRemoveUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
