/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileVersionControllerUpdateReleaseMutationRequest,
  MobileVersionControllerUpdateReleaseMutationResponse,
  MobileVersionControllerUpdateReleasePathParams,
} from '../models/MobileVersionControllerUpdateRelease';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileVersionControllerUpdateReleaseUrl(
  id: MobileVersionControllerUpdateReleasePathParams['id'],
) {
  const res = {
    method: 'PATCH',
    url: `https://app.ethos.ind.br/api/mobile/version/releases/${id}` as const,
  };
  return res;
}

/**
 * @summary Atualiza uma versão cadastrada
 * {@link /api/mobile/version/releases/:id}
 */
export async function mobileVersionControllerUpdateRelease(
  id: MobileVersionControllerUpdateReleasePathParams['id'],
  data: MobileVersionControllerUpdateReleaseMutationRequest,
  config: Partial<
    RequestConfig<MobileVersionControllerUpdateReleaseMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    MobileVersionControllerUpdateReleaseMutationResponse,
    ResponseErrorConfig<Error>,
    MobileVersionControllerUpdateReleaseMutationRequest
  >({
    method: 'PATCH',
    url: getMobileVersionControllerUpdateReleaseUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
