/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileEtiquetasControllerListarEtiquetasCatQueryResponse,
  MobileEtiquetasControllerListarEtiquetasCatQueryParams,
} from '../models/MobileEtiquetasControllerListarEtiquetasCat';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileEtiquetasControllerListarEtiquetasCatUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/sticker/list-cat` as const,
  };
  return res;
}

/**
 * @description Consulta etiquetas Caterpillar pendentes com paginação e filtros de pesquisa.
 * @summary Lista etiquetas Caterpillar (AIAG) paginadas com filtros opcionais
 * {@link /api/mobile/sticker/list-cat}
 */
export async function mobileEtiquetasControllerListarEtiquetasCat(
  params?: MobileEtiquetasControllerListarEtiquetasCatQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileEtiquetasControllerListarEtiquetasCatQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getMobileEtiquetasControllerListarEtiquetasCatUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
