/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileGaleriaControllerUploadProjectMutationRequest,
  MobileGaleriaControllerUploadProjectMutationResponse,
  MobileGaleriaControllerUploadProjectHeaderParams,
} from '../models/MobileGaleriaControllerUploadProject';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';
import { buildFormData } from '../.kubb/config';

function getMobileGaleriaControllerUploadProjectUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/mobile/galeria/report-qualidade` as const,
  };
  return res;
}

/**
 * @description Recebe arquivos do aplicativo mobile e cria um reporte de qualidade vinculado ao número de série, gate e item.
 * @summary Envia fotos/vídeos para reporte de qualidade
 * {@link /api/mobile/galeria/report-qualidade}
 */
export async function mobileGaleriaControllerUploadProject(
  data: MobileGaleriaControllerUploadProjectMutationRequest,
  headers: MobileGaleriaControllerUploadProjectHeaderParams,
  config: Partial<
    RequestConfig<MobileGaleriaControllerUploadProjectMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const formData = buildFormData(requestData);
  const res = await request<
    MobileGaleriaControllerUploadProjectMutationResponse,
    ResponseErrorConfig<Error>,
    MobileGaleriaControllerUploadProjectMutationRequest
  >({
    method: 'POST',
    url: getMobileGaleriaControllerUploadProjectUrl().url.toString(),
    data: formData as FormData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  });
  return res.data;
}
