/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileImpressoraControllerFindOneQueryResponse,
  MobileImpressoraControllerFindOnePathParams,
  MobileImpressoraControllerFindOne404,
} from '../models/MobileImpressoraControllerFindOne';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileImpressoraControllerFindOneUrl(
  id: MobileImpressoraControllerFindOnePathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/impressora-bluetooth/${id}` as const,
  };
  return res;
}

/**
 * @description Retorna os dados da impressora Bluetooth identificada pelo ID informado.
 * @summary Busca uma impressora Bluetooth pelo ID
 * {@link /api/mobile/impressora-bluetooth/:id}
 */
export async function mobileImpressoraControllerFindOne(
  id: MobileImpressoraControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileImpressoraControllerFindOneQueryResponse,
    ResponseErrorConfig<MobileImpressoraControllerFindOne404>,
    unknown
  >({
    method: 'GET',
    url: getMobileImpressoraControllerFindOneUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
