/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileGaleriaControllerListReportFotosAppNamesQueryResponse,
  MobileGaleriaControllerListReportFotosAppNamesQueryParams,
} from '../models/MobileGaleriaControllerListReportFotosAppNames';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileGaleriaControllerListReportFotosAppNamesUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/report-fotos/app-names` as const,
  };
  return res;
}

/**
 * @description Aplica os mesmos filtros de report-fotos, exceto paginação, e retorna os contextos disponíveis para a galeria.
 * @summary Lista álbuns de reports com a quantidade de fotos
 * {@link /api/mobile/galeria/report-fotos/app-names}
 */
export async function mobileGaleriaControllerListReportFotosAppNames(
  params?: MobileGaleriaControllerListReportFotosAppNamesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileGaleriaControllerListReportFotosAppNamesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getMobileGaleriaControllerListReportFotosAppNamesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
