/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { MobileImpressoraControllerFindAllQueryResponse } from '../models/MobileImpressoraControllerFindAll';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileImpressoraControllerFindAllUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/impressora-bluetooth` as const,
  };
  return res;
}

/**
 * @description Retorna as impressoras Bluetooth cadastradas para o aplicativo mobile.
 * @summary Lista todas as impressoras Bluetooth
 * {@link /api/mobile/impressora-bluetooth}
 */
export async function mobileImpressoraControllerFindAll(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileImpressoraControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getMobileImpressoraControllerFindAllUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
