/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileEtiquetasControllerBuscarAberturaEtiquetaPdiQueryResponse,
  MobileEtiquetasControllerBuscarAberturaEtiquetaPdiPathParams,
  MobileEtiquetasControllerBuscarAberturaEtiquetaPdi404,
} from '../models/MobileEtiquetasControllerBuscarAberturaEtiquetaPdi';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileEtiquetasControllerBuscarAberturaEtiquetaPdiUrl(
  id: MobileEtiquetasControllerBuscarAberturaEtiquetaPdiPathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/sticker/pdi/${id}/order-opening` as const,
  };
  return res;
}

/**
 * @summary Busca os detalhes da abertura realizada com uma etiqueta PDI
 * {@link /api/mobile/sticker/pdi/:id/order-opening}
 */
export async function mobileEtiquetasControllerBuscarAberturaEtiquetaPdi(
  id: MobileEtiquetasControllerBuscarAberturaEtiquetaPdiPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileEtiquetasControllerBuscarAberturaEtiquetaPdiQueryResponse,
    ResponseErrorConfig<MobileEtiquetasControllerBuscarAberturaEtiquetaPdi404>,
    unknown
  >({
    method: 'GET',
    url: getMobileEtiquetasControllerBuscarAberturaEtiquetaPdiUrl(
      id,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
