/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest,
  MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationResponse,
} from '../models/MobileEtiquetasControllerRegenerateStrickerPDIMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileEtiquetasControllerRegenerateStrickerPDIMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/mobile/sticker/regenerate-pdi` as const,
  };
  return res;
}

/**
 * @description Gera novamente uma etiqueta PDI usando os dados informados na solicitação.
 * @summary Regera uma etiqueta PDI existente
 * {@link /api/mobile/sticker/regenerate-pdi}
 */
export async function mobileEtiquetasControllerRegenerateStrickerPDIMethod(
  data: MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest,
  config: Partial<
    RequestConfig<MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationResponse,
    ResponseErrorConfig<Error>,
    MobileEtiquetasControllerRegenerateStrickerPDIMethodMutationRequest
  >({
    method: 'POST',
    url: getMobileEtiquetasControllerRegenerateStrickerPDIMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
