/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  MobileGaleriaControllerGetImagePackMethodQueryResponse,
  MobileGaleriaControllerGetImagePackMethodPathParams,
} from '../models/MobileGaleriaControllerGetImagePackMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getMobileGaleriaControllerGetImagePackMethodUrl(
  id: MobileGaleriaControllerGetImagePackMethodPathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/galeria/pack/${id}` as const,
  };
  return res;
}

/**
 * @description Gera uma página HTML para visualização das imagens associadas ao pack informado.
 * @summary Renderiza um HTML com as imagens de um pack
 * {@link /api/mobile/galeria/pack/:id}
 */
export async function mobileGaleriaControllerGetImagePackMethod(
  id: MobileGaleriaControllerGetImagePackMethodPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MobileGaleriaControllerGetImagePackMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getMobileGaleriaControllerGetImagePackMethodUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
