/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ScannerControllerGetOrderQueryResponse,
  ScannerControllerGetOrderPathParams,
} from '../models/ScannerControllerGetOrder';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getScannerControllerGetOrderUrl(
  order: ScannerControllerGetOrderPathParams['order'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/scanner/order/${order}` as const,
  };
  return res;
}

/**
 * @description Consulta a ordem de produção e retorna seus dados, item, quantidades, pedido e informações complementares.
 * @summary Consulta as informações de uma ordem de produção pelo scanner
 * {@link /api/mobile/scanner/order/:order}
 */
export async function scannerControllerGetOrder(
  order: ScannerControllerGetOrderPathParams['order'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ScannerControllerGetOrderQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getScannerControllerGetOrderUrl(order).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
