/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ScannerControllerGetLabelQueryResponse,
  ScannerControllerGetLabelPathParams,
  ScannerControllerGetLabel404,
} from '../models/ScannerControllerGetLabel';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getScannerControllerGetLabelUrl(
  code: ScannerControllerGetLabelPathParams['code'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/mobile/scanner/label-pdi/${code}` as const,
  };
  return res;
}

/**
 * @description Localiza a etiqueta PDI correspondente ao código lido e retorna seus dados para conferência.
 * @summary Consulta uma etiqueta PDI pelo DataMatrix lido pelo scanner
 * {@link /api/mobile/scanner/label-pdi/:code}
 */
export async function scannerControllerGetLabel(
  code: ScannerControllerGetLabelPathParams['code'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ScannerControllerGetLabelQueryResponse,
    ResponseErrorConfig<ScannerControllerGetLabel404>,
    unknown
  >({
    method: 'GET',
    url: getScannerControllerGetLabelUrl(code).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
