/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerListConversationsQueryResponse,
  ChatbotEstruturaControllerListConversationsQueryParams,
} from '../models/ChatbotEstruturaControllerListConversations';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerListConversationsUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/estrutura/chatbot/conversations` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/conversations}
 */
export async function chatbotEstruturaControllerListConversations(
  params?: ChatbotEstruturaControllerListConversationsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ChatbotEstruturaControllerListConversationsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getChatbotEstruturaControllerListConversationsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
