/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerSendMessageMutationRequest,
  ChatbotEstruturaControllerSendMessageMutationResponse,
} from '../models/ChatbotEstruturaControllerSendMessage';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerSendMessageUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/estrutura/chatbot/message` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/message}
 */
export async function chatbotEstruturaControllerSendMessage(
  data: ChatbotEstruturaControllerSendMessageMutationRequest,
  config: Partial<
    RequestConfig<ChatbotEstruturaControllerSendMessageMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ChatbotEstruturaControllerSendMessageMutationResponse,
    ResponseErrorConfig<Error>,
    ChatbotEstruturaControllerSendMessageMutationRequest
  >({
    method: 'POST',
    url: getChatbotEstruturaControllerSendMessageUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
