/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerDeleteConversationMutationResponse,
  ChatbotEstruturaControllerDeleteConversationPathParams,
} from '../models/ChatbotEstruturaControllerDeleteConversation';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerDeleteConversationUrl(
  conversationId: ChatbotEstruturaControllerDeleteConversationPathParams['conversationId'],
) {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/estrutura/chatbot/conversations/${conversationId}` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/conversations/:conversationId}
 */
export async function chatbotEstruturaControllerDeleteConversation(
  conversationId: ChatbotEstruturaControllerDeleteConversationPathParams['conversationId'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ChatbotEstruturaControllerDeleteConversationMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'DELETE',
    url: getChatbotEstruturaControllerDeleteConversationUrl(
      conversationId,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
