/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerCreateConversationMutationRequest,
  ChatbotEstruturaControllerCreateConversationMutationResponse,
} from '../models/ChatbotEstruturaControllerCreateConversation';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerCreateConversationUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/estrutura/chatbot/conversations` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/conversations}
 */
export async function chatbotEstruturaControllerCreateConversation(
  data: ChatbotEstruturaControllerCreateConversationMutationRequest,
  config: Partial<
    RequestConfig<ChatbotEstruturaControllerCreateConversationMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ChatbotEstruturaControllerCreateConversationMutationResponse,
    ResponseErrorConfig<Error>,
    ChatbotEstruturaControllerCreateConversationMutationRequest
  >({
    method: 'POST',
    url: getChatbotEstruturaControllerCreateConversationUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
