/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerCancelMessageMutationRequest,
  ChatbotEstruturaControllerCancelMessageMutationResponse,
} from '../models/ChatbotEstruturaControllerCancelMessage';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerCancelMessageUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/estrutura/chatbot/cancel` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/cancel}
 */
export async function chatbotEstruturaControllerCancelMessage(
  data: ChatbotEstruturaControllerCancelMessageMutationRequest,
  config: Partial<
    RequestConfig<ChatbotEstruturaControllerCancelMessageMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ChatbotEstruturaControllerCancelMessageMutationResponse,
    ResponseErrorConfig<Error>,
    ChatbotEstruturaControllerCancelMessageMutationRequest
  >({
    method: 'POST',
    url: getChatbotEstruturaControllerCancelMessageUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
