/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  ChatbotEstruturaControllerUpdateConversationMutationRequest,
  ChatbotEstruturaControllerUpdateConversationMutationResponse,
  ChatbotEstruturaControllerUpdateConversationPathParams,
} from '../models/ChatbotEstruturaControllerUpdateConversation';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getChatbotEstruturaControllerUpdateConversationUrl(
  conversationId: ChatbotEstruturaControllerUpdateConversationPathParams['conversationId'],
) {
  const res = {
    method: 'PATCH',
    url: `https://app.ethos.ind.br/api/estrutura/chatbot/conversations/${conversationId}` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/chatbot/conversations/:conversationId}
 */
export async function chatbotEstruturaControllerUpdateConversation(
  conversationId: ChatbotEstruturaControllerUpdateConversationPathParams['conversationId'],
  data: ChatbotEstruturaControllerUpdateConversationMutationRequest,
  config: Partial<
    RequestConfig<ChatbotEstruturaControllerUpdateConversationMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ChatbotEstruturaControllerUpdateConversationMutationResponse,
    ResponseErrorConfig<Error>,
    ChatbotEstruturaControllerUpdateConversationMutationRequest
  >({
    method: 'PATCH',
    url: getChatbotEstruturaControllerUpdateConversationUrl(
      conversationId,
    ).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
