/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerGetChecklistQueryResponse,
  CheckListControllerGetChecklistQueryParams,
} from '../models/CheckListControllerGetChecklist';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerGetChecklistUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/checklist` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist}
 */
export async function checkListControllerGetChecklist(
  params: CheckListControllerGetChecklistQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CheckListControllerGetChecklistQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getCheckListControllerGetChecklistUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
