/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerObterProgressoQueryResponse,
  CheckListControllerObterProgressoQueryParams,
} from '../models/CheckListControllerObterProgresso';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerObterProgressoUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/checklist/progresso` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist/progresso}
 */
export async function checkListControllerObterProgresso(
  params: CheckListControllerObterProgressoQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CheckListControllerObterProgressoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getCheckListControllerObterProgressoUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
