/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerInsertItemCheckListMutationRequest,
  CheckListControllerInsertItemCheckListMutationResponse,
} from '../models/CheckListControllerInsertItemCheckList';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerInsertItemCheckListUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/estrutura/checklist` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist}
 */
export async function checkListControllerInsertItemCheckList(
  data: CheckListControllerInsertItemCheckListMutationRequest,
  config: Partial<
    RequestConfig<CheckListControllerInsertItemCheckListMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CheckListControllerInsertItemCheckListMutationResponse,
    ResponseErrorConfig<Error>,
    CheckListControllerInsertItemCheckListMutationRequest
  >({
    method: 'POST',
    url: getCheckListControllerInsertItemCheckListUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
