/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerGetChecklistAvaiableQueryResponse,
  CheckListControllerGetChecklistAvaiableQueryParams,
} from '../models/CheckListControllerGetChecklistAvaiable';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerGetChecklistAvaiableUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/checklist/avaiable` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist/avaiable}
 */
export async function checkListControllerGetChecklistAvaiable(
  params: CheckListControllerGetChecklistAvaiableQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CheckListControllerGetChecklistAvaiableQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getCheckListControllerGetChecklistAvaiableUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
