/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerSubmitChecklistMutationRequest,
  CheckListControllerSubmitChecklistMutationResponse,
} from '../models/CheckListControllerSubmitChecklist';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerSubmitChecklistUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/estrutura/checklist/submit` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist/submit}
 */
export async function checkListControllerSubmitChecklist(
  data: CheckListControllerSubmitChecklistMutationRequest,
  config: Partial<
    RequestConfig<CheckListControllerSubmitChecklistMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CheckListControllerSubmitChecklistMutationResponse,
    ResponseErrorConfig<Error>,
    CheckListControllerSubmitChecklistMutationRequest
  >({
    method: 'POST',
    url: getCheckListControllerSubmitChecklistUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
