/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CheckListControllerGetChecklistTagsQueryResponse,
  CheckListControllerGetChecklistTagsQueryParams,
} from '../models/CheckListControllerGetChecklistTags';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCheckListControllerGetChecklistTagsUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/checklist/tags` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/checklist/tags}
 */
export async function checkListControllerGetChecklistTags(
  params: CheckListControllerGetChecklistTagsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CheckListControllerGetChecklistTagsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getCheckListControllerGetChecklistTagsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
