/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaRoteiroControllerConsultarRoteiroMethodQueryResponse,
  EstruturaRoteiroControllerConsultarRoteiroMethodQueryParams,
} from '../models/EstruturaRoteiroControllerConsultarRoteiroMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaRoteiroControllerConsultarRoteiroMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/estrutura/roteiro` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/roteiro}
 */
export async function estruturaRoteiroControllerConsultarRoteiroMethod(
  params: EstruturaRoteiroControllerConsultarRoteiroMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaRoteiroControllerConsultarRoteiroMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaRoteiroControllerConsultarRoteiroMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
