/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaExportControllerExportToNeo4JMutationRequest,
  EstruturaExportControllerExportToNeo4JMutationResponse,
} from '../models/EstruturaExportControllerExportToNeo4J';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaExportControllerExportToNeo4JUrl() {
  const res = {
    method: 'POST',
    url: `https://dev.ethos.ind.br/api/estrutura/export` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/export}
 */
export async function estruturaExportControllerExportToNeo4J(
  data: EstruturaExportControllerExportToNeo4JMutationRequest,
  config: Partial<
    RequestConfig<EstruturaExportControllerExportToNeo4JMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    EstruturaExportControllerExportToNeo4JMutationResponse,
    ResponseErrorConfig<Error>,
    EstruturaExportControllerExportToNeo4JMutationRequest
  >({
    method: 'POST',
    url: getEstruturaExportControllerExportToNeo4JUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
