/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaControllerEstrturaAsListMethodQueryResponse,
  EstruturaControllerEstrturaAsListMethodQueryParams,
} from '../models/EstruturaControllerEstrturaAsListMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaControllerEstrturaAsListMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/estrutura/list` as const,
  };
  return res;
}

/**
 * @summary lista a estrutura como lista simples
 * {@link /api/estrutura/list}
 */
export async function estruturaControllerEstrturaAsListMethod(
  params: EstruturaControllerEstrturaAsListMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaControllerEstrturaAsListMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaControllerEstrturaAsListMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
