/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaControllerAnaliseEstruturaResumidaMethodQueryResponse,
  EstruturaControllerAnaliseEstruturaResumidaMethodQueryParams,
} from '../models/EstruturaControllerAnaliseEstruturaResumidaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaControllerAnaliseEstruturaResumidaMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/analise/resumida` as const,
  };
  return res;
}

/**
 * @summary resume o tempo total de producao por setor para um item final ou uma lista de itens finais
 * {@link /api/estrutura/analise/resumida}
 */
export async function estruturaControllerAnaliseEstruturaResumidaMethod(
  params?: EstruturaControllerAnaliseEstruturaResumidaMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaControllerAnaliseEstruturaResumidaMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaControllerAnaliseEstruturaResumidaMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
