/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaInternalControllerGetEstruturasDependentesQueryResponse,
  EstruturaInternalControllerGetEstruturasDependentesQueryParams,
} from '../models/EstruturaInternalControllerGetEstruturasDependentes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaInternalControllerGetEstruturasDependentesUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/internal/dependentes` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/internal/dependentes}
 */
export async function estruturaInternalControllerGetEstruturasDependentes(
  params: EstruturaInternalControllerGetEstruturasDependentesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaInternalControllerGetEstruturasDependentesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaInternalControllerGetEstruturasDependentesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
