/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaControllerDetalharItensQueryResponse,
  EstruturaControllerDetalharItensQueryParams,
} from '../models/EstruturaControllerDetalharItens';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaControllerDetalharItensUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/estrutura/itens` as const,
  };
  return res;
}

/**
 * @summary detalha uma lista de itens
 * {@link /api/estrutura/itens}
 */
export async function estruturaControllerDetalharItens(
  params: EstruturaControllerDetalharItensQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaControllerDetalharItensQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaControllerDetalharItensUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
