/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaInternalControllerGetItemDeControleQueryResponse,
  EstruturaInternalControllerGetItemDeControleQueryParams,
} from '../models/EstruturaInternalControllerGetItemDeControle';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaInternalControllerGetItemDeControleUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/estrutura/internal/controle` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/internal/controle}
 */
export async function estruturaInternalControllerGetItemDeControle(
  params: EstruturaInternalControllerGetItemDeControleQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaInternalControllerGetItemDeControleQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaInternalControllerGetItemDeControleUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
