/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  EstruturaControllerGetEstruturasDedendentesMethodQueryResponse,
  EstruturaControllerGetEstruturasDedendentesMethodQueryParams,
} from '../models/EstruturaControllerGetEstruturasDedendentesMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getEstruturaControllerGetEstruturasDedendentesMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://dev.ethos.ind.br/api/estrutura/dependentes` as const,
  };
  return res;
}

/**
 * {@link /api/estrutura/dependentes}
 */
export async function estruturaControllerGetEstruturasDedendentesMethod(
  params: EstruturaControllerGetEstruturasDedendentesMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EstruturaControllerGetEstruturasDedendentesMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getEstruturaControllerGetEstruturasDedendentesMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
