/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ControlePortariaVideoControllerGetStatus200 = any;

export type ControlePortariaVideoControllerGetStatusQueryResponse =
  ControlePortariaVideoControllerGetStatus200;

export type ControlePortariaVideoControllerGetStatusQuery = {
  Response: ControlePortariaVideoControllerGetStatus200;
  Errors: any;
};
