/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { VehicleKpiResponseDto } from './VehicleKpiResponseDto';

export enum ControleVeiculosControllerGetKpisQueryParamsStatusEnum {
  INSIDE = 'INSIDE',
  OUTSIDE = 'OUTSIDE',
  FORCE_CLOSE = 'FORCE_CLOSE',
}

export type ControleVeiculosControllerGetKpisQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Placa do veículo
   * @type string | undefined
   */
  placa?: string;
  /**
   * @description Status/Direção do veículo
   * @type string | undefined
   */
  status?: ControleVeiculosControllerGetKpisQueryParamsStatusEnum;
  /**
   * @description Modelo do veículo
   * @type string | undefined
   */
  modelo?: string;
  /**
   * @description Data Inicial (YYYY-MM-DD)
   * @type string | undefined
   */
  startDate?: string;
  /**
   * @description Data Final (YYYY-MM-DD)
   * @type string | undefined
   */
  endDate?: string;
};

/**
 * @description KPIs retornados com sucesso
 */
export type ControleVeiculosControllerGetKpis200 = VehicleKpiResponseDto;

export type ControleVeiculosControllerGetKpisQueryResponse =
  ControleVeiculosControllerGetKpis200;

export type ControleVeiculosControllerGetKpisQuery = {
  Response: ControleVeiculosControllerGetKpis200;
  QueryParams: ControleVeiculosControllerGetKpisQueryParams;
  Errors: any;
};
