/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ControleVeiculosControllerGetFotoPathParams = {
  /**
   * @type string
   */
  filename: string;
};

export type ControleVeiculosControllerGetFoto200 = any;

export type ControleVeiculosControllerGetFotoQueryResponse =
  ControleVeiculosControllerGetFoto200;

export type ControleVeiculosControllerGetFotoQuery = {
  Response: ControleVeiculosControllerGetFoto200;
  PathParams: ControleVeiculosControllerGetFotoPathParams;
  Errors: any;
};
