/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ControlePortariaVideoControllerCreateSession201 = any;

export type ControlePortariaVideoControllerCreateSessionMutationResponse =
  ControlePortariaVideoControllerCreateSession201;

export type ControlePortariaVideoControllerCreateSessionMutation = {
  Response: ControlePortariaVideoControllerCreateSession201;
  Errors: any;
};
