/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IntelbrasEventDTO } from './IntelbrasEventDTO';

/**
 * @description Evento recebido com sucesso
 */
export type ControleVeiculosWebHookControllerHandleWebhook200 = any;

/**
 * @description Dados do evento inválidos
 */
export type ControleVeiculosWebHookControllerHandleWebhook400 = any;

/**
 * @description Dados do evento da câmera Intelbras
 */
export type ControleVeiculosWebHookControllerHandleWebhookMutationRequest =
  IntelbrasEventDTO;

export type ControleVeiculosWebHookControllerHandleWebhookMutationResponse =
  ControleVeiculosWebHookControllerHandleWebhook200;

export type ControleVeiculosWebHookControllerHandleWebhookMutation = {
  Response: ControleVeiculosWebHookControllerHandleWebhook200;
  Request: ControleVeiculosWebHookControllerHandleWebhookMutationRequest;
  Errors: ControleVeiculosWebHookControllerHandleWebhook400;
};
