/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Service is alive (GET).
 */
export type ControleVeiculosWebHookControllerGetHeartbeat200 = any;

export type ControleVeiculosWebHookControllerGetHeartbeatQueryResponse =
  ControleVeiculosWebHookControllerGetHeartbeat200;

export type ControleVeiculosWebHookControllerGetHeartbeatQuery = {
  Response: ControleVeiculosWebHookControllerGetHeartbeat200;
  Errors: any;
};
