/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ControlePortariaVideoControllerGetSegmentPathParams = {
  /**
   * @description Nome do arquivo de segmento (.ts)
   * @type string
   */
  filename: string;
};

export type ControlePortariaVideoControllerGetSegment200 = any;

export type ControlePortariaVideoControllerGetSegmentQueryResponse =
  ControlePortariaVideoControllerGetSegment200;

export type ControlePortariaVideoControllerGetSegmentQuery = {
  Response: ControlePortariaVideoControllerGetSegment200;
  PathParams: ControlePortariaVideoControllerGetSegmentPathParams;
  Errors: any;
};
