/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type NormalPic = {
  /**
   * @description Imagem em base64
   * @type string
   */
  Content: string;
  /**
   * @type string
   */
  PicName: string;
};
