/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NormalPic } from './NormalPic';
import type { Plate } from './Plate';
import type { SnapInfo } from './SnapInfo';
import type { Vehicle } from './Vehicle';

export type PictureData = {
  /**
   * @type object
   */
  NormalPic: NormalPic;
  /**
   * @type object
   */
  Plate: Plate;
  /**
   * @type object
   */
  SnapInfo: SnapInfo;
  /**
   * @type object
   */
  Vehicle: Vehicle;
};
