/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Plate = {
  /**
   * @description Coordenadas [x, y, w, h]
   * @type array
   */
  BoundingBox: number[];
  /**
   * @type number
   */
  Channel: number;
  /**
   * @type number
   */
  Confidence: number;
  /**
   * @type boolean
   */
  IsExist: boolean;
  /**
   * @type string
   */
  PlateColor: string;
  /**
   * @type string
   */
  PlateNumber: string;
  /**
   * @type string
   */
  PlateType: string;
  /**
   * @type string
   */
  Region: string;
  /**
   * @type number
   */
  UploadNum: number;
};
