/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PbindexControllerGetRefreshDateQueryResponse,
  PbindexControllerGetRefreshDateQueryParams,
  PbindexControllerGetRefreshDate500,
} from '../models/PbindexControllerGetRefreshDate';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPbindexControllerGetRefreshDateUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/pbindex/api/pbindex/powerbi/refresh` as const,
  };
  return res;
}

/**
 * @summary Obtém a data da última atualização de um dataset
 * {@link /api/pbindex/powerbi/refresh}
 */
export async function pbindexControllerGetRefreshDate(
  params: PbindexControllerGetRefreshDateQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PbindexControllerGetRefreshDateQueryResponse,
    ResponseErrorConfig<PbindexControllerGetRefreshDate500>,
    unknown
  >({
    method: 'GET',
    url: getPbindexControllerGetRefreshDateUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
