/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PbindexControllerAssignDatasetMutationRequest,
  PbindexControllerAssignDatasetMutationResponse,
  PbindexControllerAssignDataset500,
} from '../models/PbindexControllerAssignDataset';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPbindexControllerAssignDatasetUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/pbindex/api/pbindex/powerbi/datasets` as const,
  };
  return res;
}

/**
 * @summary Cria um novo dataset/link do PowerBI
 * {@link /api/pbindex/powerbi/datasets}
 */
export async function pbindexControllerAssignDataset(
  data: PbindexControllerAssignDatasetMutationRequest,
  config: Partial<
    RequestConfig<PbindexControllerAssignDatasetMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PbindexControllerAssignDatasetMutationResponse,
    ResponseErrorConfig<PbindexControllerAssignDataset500>,
    PbindexControllerAssignDatasetMutationRequest
  >({
    method: 'POST',
    url: getPbindexControllerAssignDatasetUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
