/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { PbindexControllerGetOnlineUsersQueryResponse } from '../models/PbindexControllerGetOnlineUsers';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPbindexControllerGetOnlineUsersUrl() {
  const res = {
    method: 'GET',
    url: `http://192.168.99.129:3000/api/pbindex/powerbi/online-users` as const,
  };
  return res;
}

/**
 * @summary Obtém a lista de usuários conectados ao WebSocket
 * {@link /api/pbindex/powerbi/online-users}
 */
export async function pbindexControllerGetOnlineUsers(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PbindexControllerGetOnlineUsersQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getPbindexControllerGetOnlineUsersUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
