/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PbindexControllerRefreshDatasetAsAdminMutationRequest,
  PbindexControllerRefreshDatasetAsAdminMutationResponse,
  PbindexControllerRefreshDatasetAsAdmin404,
} from '../models/PbindexControllerRefreshDatasetAsAdmin';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPbindexControllerRefreshDatasetAsAdminUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/pbindex/api/pbindex/powerbi/refresh/admin` as const,
  };
  return res;
}

/**
 * @summary Solicita atualização de um dataset do PowerBI como admin
 * {@link /api/pbindex/powerbi/refresh/admin}
 */
export async function pbindexControllerRefreshDatasetAsAdmin(
  data: PbindexControllerRefreshDatasetAsAdminMutationRequest,
  config: Partial<
    RequestConfig<PbindexControllerRefreshDatasetAsAdminMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PbindexControllerRefreshDatasetAsAdminMutationResponse,
    ResponseErrorConfig<PbindexControllerRefreshDatasetAsAdmin404>,
    PbindexControllerRefreshDatasetAsAdminMutationRequest
  >({
    method: 'POST',
    url: getPbindexControllerRefreshDatasetAsAdminUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
