/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PbindexControllerRefreshDatasetMutationRequest,
  PbindexControllerRefreshDatasetMutationResponse,
  PbindexControllerRefreshDataset400,
  PbindexControllerRefreshDataset404,
} from '../models/PbindexControllerRefreshDataset';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPbindexControllerRefreshDatasetUrl() {
  const res = {
    method: 'POST',
    url: `http://192.168.99.129:3000/api/pbindex/powerbi/refresh` as const,
  };
  return res;
}

/**
 * @summary Solicita atualização de um dataset do PowerBI
 * {@link /api/pbindex/powerbi/refresh}
 */
export async function pbindexControllerRefreshDataset(
  data: PbindexControllerRefreshDatasetMutationRequest,
  config: Partial<
    RequestConfig<PbindexControllerRefreshDatasetMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PbindexControllerRefreshDatasetMutationResponse,
    ResponseErrorConfig<
      PbindexControllerRefreshDataset400 | PbindexControllerRefreshDataset404
    >,
    PbindexControllerRefreshDatasetMutationRequest
  >({
    method: 'POST',
    url: getPbindexControllerRefreshDatasetUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
