/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedReportsResponse } from './PaginatedReportsResponse';

export type GetAlbumHistoryQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @type string
   */
  pn: string;
  /**
   * @type string
   */
  serialNumber: string;
  /**
   * @type string
   */
  appName: string;
  /**
   * @type string | undefined
   */
  'properties.codItem'?: string;
  /**
   * @type string | undefined
   */
  'properties.gate'?: string;
  /**
   * @type string | undefined
   */
  reportType?: string;
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type string | undefined
   */
  mediaType?: string;
};

/**
 * @description Paginated reports
 */
export type GetAlbumHistory200 = PaginatedReportsResponse;

export type GetAlbumHistoryQueryResponse = GetAlbumHistory200;

export type GetAlbumHistoryQuery = {
  Response: GetAlbumHistory200;
  QueryParams: GetAlbumHistoryQueryParams;
  Errors: any;
};
