/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InspectionFailureResponse } from './InspectionFailureResponse';

export type GetInspectionFailuresQueryParams = {
  /**
   * @type string
   */
  startDate: string;
  /**
   * @type string
   */
  endDate: string;
  /**
   * @type string
   */
  nSerie: string;
  /**
   * @type string
   */
  partCode: string;
};

/**
 * @description Inspection failures
 */
export type GetInspectionFailures200 = InspectionFailureResponse[];

export type GetInspectionFailuresQueryResponse = GetInspectionFailures200;

export type GetInspectionFailuresQuery = {
  Response: GetInspectionFailures200;
  QueryParams: GetInspectionFailuresQueryParams;
  Errors: any;
};
