/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetMediaUrlQueryParams = {
  /**
   * @type string
   */
  path: string;
  /**
   * @type string
   */
  name: string;
};

/**
 * @description Media file
 */
export type GetMediaUrl200 = Blob;

export type GetMediaUrlQueryResponse = GetMediaUrl200;

export type GetMediaUrlQuery = {
  Response: GetMediaUrl200;
  QueryParams: GetMediaUrlQueryParams;
  Errors: any;
};
