/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetPackDetailUrlPathParams = {
  /**
   * @type string
   */
  code: string;
};

/**
 * @description Pack HTML
 */
export type GetPackDetailUrl200 = string;

export type GetPackDetailUrlQueryResponse = GetPackDetailUrl200;

export type GetPackDetailUrlQuery = {
  Response: GetPackDetailUrl200;
  PathParams: GetPackDetailUrlPathParams;
  Errors: any;
};
