/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PhotoAlbumResponse } from './PhotoAlbumResponse';

export type GetProductAlbumsQueryParams = {
  /**
   * @type string
   */
  pn: string;
  /**
   * @type string
   */
  serialNumber: string;
  /**
   * @type string | undefined
   */
  reportType?: string;
  /**
   * @type string | undefined
   */
  status?: string;
  /**
   * @type string | undefined
   */
  mediaType?: string;
};

/**
 * @description Albums
 */
export type GetProductAlbums200 = PhotoAlbumResponse[];

export type GetProductAlbumsQueryResponse = GetProductAlbums200;

export type GetProductAlbumsQuery = {
  Response: GetProductAlbums200;
  QueryParams: GetProductAlbumsQueryParams;
  Errors: any;
};
