/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InspectionFailureResponse = {
  /**
   * @type string | undefined
   */
  ResourceName?: string;
  /**
   * @type string | undefined
   */
  OperatorName?: string;
  /**
   * @type string | undefined
   */
  PartCode?: string;
  /**
   * @type string | undefined
   */
  NSerie?: string;
  /**
   * @type string | undefined
   */
  Detalhamento?: string;
  /**
   * @type string | undefined
   */
  ServerTimestamp?: string;
  /**
   * @type string | undefined
   */
  OrderNum?: string;
  /**
   * @type string | undefined
   */
  Operation?: string;
  /**
   * @type string | undefined
   */
  Sequence?: string;
  /**
   * @type string | undefined
   */
  Book?: string;
  [key: string]: unknown;
};
