/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PhotoAlbumResponse = {
  /**
   * @type string
   */
  nome: string;
  /**
   * @type number
   */
  quantidadeFotos: number;
};
