/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProductContextResponse } from './ProductContextResponse';

export type ResolveProductLabelPathParams = {
  /**
   * @type string
   */
  pdiLabel: string;
};

/**
 * @description Product context
 */
export type ResolveProductLabel200 = ProductContextResponse;

export type ResolveProductLabelQueryResponse = ResolveProductLabel200;

export type ResolveProductLabelQuery = {
  Response: ResolveProductLabel200;
  PathParams: ResolveProductLabelPathParams;
  Errors: any;
};
