/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AppEthosControllerCriaRoutesMutationRequest,
  AppEthosControllerCriaRoutesMutationResponse,
} from '../models/AppEthosControllerCriaRoutes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAppEthosControllerCriaRoutesUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/route/app/routes` as const,
  };
  return res;
}

/**
 * {@link /api/route/app/routes}
 */
export async function appEthosControllerCriaRoutes(
  data: AppEthosControllerCriaRoutesMutationRequest,
  config: Partial<
    RequestConfig<AppEthosControllerCriaRoutesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AppEthosControllerCriaRoutesMutationResponse,
    ResponseErrorConfig<Error>,
    AppEthosControllerCriaRoutesMutationRequest
  >({
    method: 'POST',
    url: getAppEthosControllerCriaRoutesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
