/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { AppEthosControllerCriaRoutesMutationRequest, AppEthosControllerCriaRoutesMutationResponse } from "../models/AppEthosControllerCriaRoutes";

function getAppEthosControllerCriaRoutesUrl() {
  return `https://app.ethos.ind.br/api/route/app/routes` as const
}

/**
 * {@link /api/route/app/routes}
 */
export async function appEthosControllerCriaRoutes(data: AppEthosControllerCriaRoutesMutationRequest, config: Partial<RequestConfig<AppEthosControllerCriaRoutesMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AppEthosControllerCriaRoutesMutationResponse, ResponseErrorConfig<Error>, AppEthosControllerCriaRoutesMutationRequest>({ method : "POST", url : getAppEthosControllerCriaRoutesUrl().toString(), data, ... requestConfig })
return res.data
}