/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AppEthosControllerAtualizaRoutesMutationRequest,
  AppEthosControllerAtualizaRoutesMutationResponse,
  AppEthosControllerAtualizaRoutesPathParams,
} from '../models/AppEthosControllerAtualizaRoutes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAppEthosControllerAtualizaRoutesUrl(
  id: AppEthosControllerAtualizaRoutesPathParams['id'],
) {
  const res = {
    method: 'PUT',
    url: `https://app.ethos.ind.br/api/route/app/routes/${id}` as const,
  };
  return res;
}

/**
 * {@link /api/route/app/routes/:id}
 */
export async function appEthosControllerAtualizaRoutes(
  id: AppEthosControllerAtualizaRoutesPathParams['id'],
  data?: AppEthosControllerAtualizaRoutesMutationRequest,
  config: Partial<
    RequestConfig<AppEthosControllerAtualizaRoutesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AppEthosControllerAtualizaRoutesMutationResponse,
    ResponseErrorConfig<Error>,
    AppEthosControllerAtualizaRoutesMutationRequest
  >({
    method: 'PUT',
    url: getAppEthosControllerAtualizaRoutesUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
