/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { AppEthosControllerAtualizaRoutesMutationRequest, AppEthosControllerAtualizaRoutesMutationResponse, AppEthosControllerAtualizaRoutesPathParams } from "../models/AppEthosControllerAtualizaRoutes";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getAppEthosControllerAtualizaRoutesUrl(id: AppEthosControllerAtualizaRoutesPathParams["id"]) {
  return `https://app.prod.ethos/api/route/app/routes/${id}` as const
}

/**
 * {@link /api/route/app/routes/:id}
 */
export async function appEthosControllerAtualizaRoutes(id: AppEthosControllerAtualizaRoutesPathParams["id"], data?: AppEthosControllerAtualizaRoutesMutationRequest, config: Partial<RequestConfig<AppEthosControllerAtualizaRoutesMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<AppEthosControllerAtualizaRoutesMutationResponse, ResponseErrorConfig<Error>, AppEthosControllerAtualizaRoutesMutationRequest>({ method : "PUT", url : getAppEthosControllerAtualizaRoutesUrl(id).toString(), data, ... requestConfig })
return res.data
}