/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  AppEthosControllerDeletaRoutesMutationResponse,
  AppEthosControllerDeletaRoutesPathParams,
} from '../models/AppEthosControllerDeletaRoutes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAppEthosControllerDeletaRoutesUrl(
  id: AppEthosControllerDeletaRoutesPathParams['id'],
) {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/route/app/routes/${id}` as const,
  };
  return res;
}

/**
 * {@link /api/route/app/routes/:id}
 */
export async function appEthosControllerDeletaRoutes(
  id: AppEthosControllerDeletaRoutesPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AppEthosControllerDeletaRoutesMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'DELETE',
    url: getAppEthosControllerDeletaRoutesUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
