/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { AppEthosControllerGetRoutesForUserQueryResponse } from '../models/AppEthosControllerGetRoutesForUser';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getAppEthosControllerGetRoutesForUserUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/route/app/routes` as const,
  };
  return res;
}

/**
 * {@link /api/route/app/routes}
 */
export async function appEthosControllerGetRoutesForUser(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AppEthosControllerGetRoutesForUserQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getAppEthosControllerGetRoutesForUserUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
