/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerListarLiderCentroCustoQueryResponse,
  FolhaHoraExtraControllerListarLiderCentroCustoPathParams,
  FolhaHoraExtraControllerListarLiderCentroCusto401,
  FolhaHoraExtraControllerListarLiderCentroCusto403,
} from '../models/FolhaHoraExtraControllerListarLiderCentroCusto';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerListarLiderCentroCustoUrl(
  usuarioId: FolhaHoraExtraControllerListarLiderCentroCustoPathParams['usuarioId'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/lider-centro-custo/${usuarioId}` as const,
  };
  return res;
}

/**
 * @description Retorna os vinculos ativos de um usuario lider com centros de custo. Use para auditar ou montar telas administrativas de permissao por CC.
 * @summary Lista centros de custo vinculados a um lider
 * {@link /api/ponto/folha-he/lider-centro-custo/:usuarioId}
 */
export async function folhaHoraExtraControllerListarLiderCentroCusto(
  usuarioId: FolhaHoraExtraControllerListarLiderCentroCustoPathParams['usuarioId'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerListarLiderCentroCustoQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerListarLiderCentroCusto401
      | FolhaHoraExtraControllerListarLiderCentroCusto403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraControllerListarLiderCentroCustoUrl(
      usuarioId,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
