/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryResponse,
  FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryParams,
  FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas401,
  FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas403,
} from '../models/FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/kpi/horas-extras-nao-autorizadas` as const,
  };
  return res;
}

/**
 * @description Consulta SPC010 com fallback em SPH010 e cruza matrícula e data com as folhas de hora extra. Retorna os funcionários que possuem HE apontada no Protheus, mas não possuem registro correspondente na folha.
 * @summary Lista horas extras apontadas sem folha de HE
 * {@link /api/ponto/folha-he/kpi/horas-extras-nao-autorizadas}
 */
export async function folhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas(
  params?: FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas401
      | FolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadas403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraKpiControllerHorasExtrasNaoAutorizadasUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
