/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerEditarMutationRequest,
  FolhaHoraExtraControllerEditarMutationResponse,
  FolhaHoraExtraControllerEditarPathParams,
  FolhaHoraExtraControllerEditar400,
  FolhaHoraExtraControllerEditar401,
  FolhaHoraExtraControllerEditar403,
  FolhaHoraExtraControllerEditar404,
} from '../models/FolhaHoraExtraControllerEditar';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerEditarUrl(
  id: FolhaHoraExtraControllerEditarPathParams['id'],
) {
  const res = {
    method: 'PUT',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/${id}` as const,
  };
  return res;
}

/**
 * @description Permite ao autor operacional editar uma folha em RASCUNHO ou rejeitada. Folhas em aprovacao ou aprovadas ficam imutaveis. Se a folha estava REJEITADO_COORDENACAO ou REJEITADO_DIRETORIA, a edicao reabre o status para RASCUNHO.
 * @summary Edita uma folha de hora extra
 * {@link /api/ponto/folha-he/:id}
 */
export async function folhaHoraExtraControllerEditar(
  id: FolhaHoraExtraControllerEditarPathParams['id'],
  data: FolhaHoraExtraControllerEditarMutationRequest,
  config: Partial<
    RequestConfig<FolhaHoraExtraControllerEditarMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FolhaHoraExtraControllerEditarMutationResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerEditar400
      | FolhaHoraExtraControllerEditar401
      | FolhaHoraExtraControllerEditar403
      | FolhaHoraExtraControllerEditar404
    >,
    FolhaHoraExtraControllerEditarMutationRequest
  >({
    method: 'PUT',
    url: getFolhaHoraExtraControllerEditarUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
