/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerCriarMutationRequest,
  FolhaHoraExtraControllerCriarMutationResponse,
  FolhaHoraExtraControllerCriar400,
  FolhaHoraExtraControllerCriar401,
  FolhaHoraExtraControllerCriar403,
  FolhaHoraExtraControllerCriar404,
} from '../models/FolhaHoraExtraControllerCriar';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerCriarUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/ponto/folha-he` as const,
  };
  return res;
}

/**
 * @description Cria uma folha HE para um centro de custo vinculado ao usuario operacional autenticado. Valida existencia do CC, funcionarios, demissao, duplicidade de matricula, vinculo funcionario x CC e vinculo usuario x CC. A folha nasce com status RASCUNHO.
 * @summary Cria uma folha de hora extra em rascunho
 * {@link /api/ponto/folha-he}
 */
export async function folhaHoraExtraControllerCriar(
  data: FolhaHoraExtraControllerCriarMutationRequest,
  config: Partial<
    RequestConfig<FolhaHoraExtraControllerCriarMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FolhaHoraExtraControllerCriarMutationResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerCriar400
      | FolhaHoraExtraControllerCriar401
      | FolhaHoraExtraControllerCriar403
      | FolhaHoraExtraControllerCriar404
    >,
    FolhaHoraExtraControllerCriarMutationRequest
  >({
    method: 'POST',
    url: getFolhaHoraExtraControllerCriarUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
