/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerConsultarKpiCumprimentoQueryResponse,
  FolhaHoraExtraControllerConsultarKpiCumprimentoPathParams,
  FolhaHoraExtraControllerConsultarKpiCumprimento400,
  FolhaHoraExtraControllerConsultarKpiCumprimento401,
  FolhaHoraExtraControllerConsultarKpiCumprimento403,
  FolhaHoraExtraControllerConsultarKpiCumprimento404,
} from '../models/FolhaHoraExtraControllerConsultarKpiCumprimento';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerConsultarKpiCumprimentoUrl(
  id: FolhaHoraExtraControllerConsultarKpiCumprimentoPathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/${id}/kpi-cumprimento` as const,
  };
  return res;
}

/**
 * @description Retorna, para cada funcionario da folha, as batidas do dia de referencia, a primeira e ultima batida, o horario de HE previsto e se o funcionario cobriu o intervalo de HE estipulado. A visibilidade segue a mesma regra de consulta da folha.
 * @summary Consulta KPI de cumprimento da jornada de hora extra da folha
 * {@link /api/ponto/folha-he/:id/kpi-cumprimento}
 */
export async function folhaHoraExtraControllerConsultarKpiCumprimento(
  id: FolhaHoraExtraControllerConsultarKpiCumprimentoPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerConsultarKpiCumprimentoQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerConsultarKpiCumprimento400
      | FolhaHoraExtraControllerConsultarKpiCumprimento401
      | FolhaHoraExtraControllerConsultarKpiCumprimento403
      | FolhaHoraExtraControllerConsultarKpiCumprimento404
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraControllerConsultarKpiCumprimentoUrl(
      id,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
