/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerVincularLiderCentroCustoMutationRequest,
  FolhaHoraExtraControllerVincularLiderCentroCustoMutationResponse,
  FolhaHoraExtraControllerVincularLiderCentroCusto401,
  FolhaHoraExtraControllerVincularLiderCentroCusto403,
  FolhaHoraExtraControllerVincularLiderCentroCusto404,
} from '../models/FolhaHoraExtraControllerVincularLiderCentroCusto';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerVincularLiderCentroCustoUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/lider-centro-custo` as const,
  };
  return res;
}

/**
 * @description Cria ou reativa o vinculo entre um usuario lider e um centro de custo. Esse cadastro define em quais centros de custo o lider pode criar ou editar folhas de hora extra. Endpoint restrito a ADMIN.
 * @summary Vincula um lider a um centro de custo
 * {@link /api/ponto/folha-he/lider-centro-custo}
 */
export async function folhaHoraExtraControllerVincularLiderCentroCusto(
  data: FolhaHoraExtraControllerVincularLiderCentroCustoMutationRequest,
  config: Partial<
    RequestConfig<FolhaHoraExtraControllerVincularLiderCentroCustoMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FolhaHoraExtraControllerVincularLiderCentroCustoMutationResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerVincularLiderCentroCusto401
      | FolhaHoraExtraControllerVincularLiderCentroCusto403
      | FolhaHoraExtraControllerVincularLiderCentroCusto404
    >,
    FolhaHoraExtraControllerVincularLiderCentroCustoMutationRequest
  >({
    method: 'POST',
    url: getFolhaHoraExtraControllerVincularLiderCentroCustoUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
