/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraKpiControllerCumprimentoQueryResponse,
  FolhaHoraExtraKpiControllerCumprimentoPathParams,
  FolhaHoraExtraKpiControllerCumprimento400,
  FolhaHoraExtraKpiControllerCumprimento401,
  FolhaHoraExtraKpiControllerCumprimento403,
  FolhaHoraExtraKpiControllerCumprimento404,
} from '../models/FolhaHoraExtraKpiControllerCumprimento';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraKpiControllerCumprimentoUrl(
  id: FolhaHoraExtraKpiControllerCumprimentoPathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/${id}/kpi-cumprimento` as const,
  };
  return res;
}

/**
 * @description Retorna, para cada funcionario da folha, as batidas do dia de referencia, a primeira e ultima batida, o horario de HE previsto e se o funcionario cobriu o intervalo de HE estipulado. A visibilidade segue a mesma regra de consulta da folha.
 * @summary Consulta KPI de cumprimento da jornada de hora extra da folha
 * {@link /api/ponto/folha-he/:id/kpi-cumprimento}
 */
export async function folhaHoraExtraKpiControllerCumprimento(
  id: FolhaHoraExtraKpiControllerCumprimentoPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraKpiControllerCumprimentoQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraKpiControllerCumprimento400
      | FolhaHoraExtraKpiControllerCumprimento401
      | FolhaHoraExtraKpiControllerCumprimento403
      | FolhaHoraExtraKpiControllerCumprimento404
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraKpiControllerCumprimentoUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
