/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraKpiControllerCumprimentoPorPeriodoQueryResponse,
  FolhaHoraExtraKpiControllerCumprimentoPorPeriodoQueryParams,
  FolhaHoraExtraKpiControllerCumprimentoPorPeriodo401,
  FolhaHoraExtraKpiControllerCumprimentoPorPeriodo403,
} from '../models/FolhaHoraExtraKpiControllerCumprimentoPorPeriodo';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraKpiControllerCumprimentoPorPeriodoUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/kpi-cumprimento/periodo` as const,
  };
  return res;
}

/**
 * @description Retorna a mesma DTO do KPI de uma folha, para todas as folhas aprovadas do período. As batidas são carregadas em lote, sem uma consulta por funcionário ou folha.
 * @summary Consulta o cumprimento de HE das folhas aprovadas por período
 * {@link /api/ponto/folha-he/kpi-cumprimento/periodo}
 */
export async function folhaHoraExtraKpiControllerCumprimentoPorPeriodo(
  params: FolhaHoraExtraKpiControllerCumprimentoPorPeriodoQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraKpiControllerCumprimentoPorPeriodoQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraKpiControllerCumprimentoPorPeriodo401
      | FolhaHoraExtraKpiControllerCumprimentoPorPeriodo403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraKpiControllerCumprimentoPorPeriodoUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
