/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerRelatorioRecursosQueryResponse,
  FolhaHoraExtraControllerRelatorioRecursosQueryParams,
  FolhaHoraExtraControllerRelatorioRecursos400,
  FolhaHoraExtraControllerRelatorioRecursos401,
  FolhaHoraExtraControllerRelatorioRecursos403,
} from '../models/FolhaHoraExtraControllerRelatorioRecursos';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerRelatorioRecursosUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/relatorio-recursos` as const,
  };
  return res;
}

/**
 * @description Gera um relatorio agregado com totais de transporte e refeicao, alem do detalhamento por setor. Quando nenhum status e informado, considera apenas folhas APROVADO. Lideres veem apenas centros de custo ativos vinculados a eles.
 * @summary Consolida recursos solicitados nas folhas de hora extra
 * {@link /api/ponto/folha-he/relatorio-recursos}
 */
export async function folhaHoraExtraControllerRelatorioRecursos(
  params?: FolhaHoraExtraControllerRelatorioRecursosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerRelatorioRecursosQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerRelatorioRecursos400
      | FolhaHoraExtraControllerRelatorioRecursos401
      | FolhaHoraExtraControllerRelatorioRecursos403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraControllerRelatorioRecursosUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
