/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraKpiControllerJornadaQueryResponse,
  FolhaHoraExtraKpiControllerJornada401,
  FolhaHoraExtraKpiControllerJornada403,
} from '../models/FolhaHoraExtraKpiControllerJornada';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraKpiControllerJornadaUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/kpi/jornada` as const,
  };
  return res;
}

/**
 * @description Série dos últimos 30 dias baseada nas folhas aprovadas de cada dia, com ranking por descumprimentos e minutos excedentes. As batidas são consultadas em lote.
 * @summary Consulta indicadores diários de cumprimento de HE
 * {@link /api/ponto/folha-he/kpi/jornada}
 */
export async function folhaHoraExtraKpiControllerJornada(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraKpiControllerJornadaQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraKpiControllerJornada401
      | FolhaHoraExtraKpiControllerJornada403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraKpiControllerJornadaUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
