/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerDesativarLiderCentroCustoMutationResponse,
  FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams,
  FolhaHoraExtraControllerDesativarLiderCentroCusto401,
  FolhaHoraExtraControllerDesativarLiderCentroCusto403,
  FolhaHoraExtraControllerDesativarLiderCentroCusto404,
} from '../models/FolhaHoraExtraControllerDesativarLiderCentroCusto';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerDesativarLiderCentroCustoUrl(
  usuarioId: FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams['usuarioId'],
  centroCustoCodigo: FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams['centroCustoCodigo'],
) {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/lider-centro-custo/${usuarioId}/${centroCustoCodigo}` as const,
  };
  return res;
}

/**
 * @description Marca o vinculo como inativo. A remocao e logica para preservar historico administrativo e permitir reativacao posterior pelo endpoint de vinculo.
 * @summary Desativa o vinculo de um lider com um centro de custo
 * {@link /api/ponto/folha-he/lider-centro-custo/:usuarioId/:centroCustoCodigo}
 */
export async function folhaHoraExtraControllerDesativarLiderCentroCusto(
  usuarioId: FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams['usuarioId'],
  centroCustoCodigo: FolhaHoraExtraControllerDesativarLiderCentroCustoPathParams['centroCustoCodigo'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerDesativarLiderCentroCustoMutationResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerDesativarLiderCentroCusto401
      | FolhaHoraExtraControllerDesativarLiderCentroCusto403
      | FolhaHoraExtraControllerDesativarLiderCentroCusto404
    >,
    unknown
  >({
    method: 'DELETE',
    url: getFolhaHoraExtraControllerDesativarLiderCentroCustoUrl(
      usuarioId,
      centroCustoCodigo,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
