/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerConsultarRefeicoesQueryResponse,
  FolhaHoraExtraControllerConsultarRefeicoesQueryParams,
  FolhaHoraExtraControllerConsultarRefeicoes401,
  FolhaHoraExtraControllerConsultarRefeicoes403,
} from '../models/FolhaHoraExtraControllerConsultarRefeicoes';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerConsultarRefeicoesUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/refeicoes` as const,
  };
  return res;
}

/**
 * @description Retorna uma linha por funcionario para montagem da tabela de refeicoes. Por padrao consulta o dia atual, todos os status e omite funcionarios com refeicao N/A.
 * @summary Lista as refeicoes solicitadas por funcionario
 * {@link /api/ponto/folha-he/refeicoes}
 */
export async function folhaHoraExtraControllerConsultarRefeicoes(
  params?: FolhaHoraExtraControllerConsultarRefeicoesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerConsultarRefeicoesQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerConsultarRefeicoes401
      | FolhaHoraExtraControllerConsultarRefeicoes403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraControllerConsultarRefeicoesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
