/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FolhaHoraExtraControllerHistoricoQueryResponse,
  FolhaHoraExtraControllerHistoricoQueryParams,
  FolhaHoraExtraControllerHistorico400,
  FolhaHoraExtraControllerHistorico401,
  FolhaHoraExtraControllerHistorico403,
} from '../models/FolhaHoraExtraControllerHistorico';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFolhaHoraExtraControllerHistoricoUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/folha-he/historico` as const,
  };
  return res;
}

/**
 * @description Retorna folhas HE ja submetidas ou encerradas para visao historica. Lideres veem apenas os centros de custo ativos vinculados a eles. Gerentes e diretores veem o historico completo com filtros por periodo, centro de custo, status e paginacao.
 * @summary Lista historico de folhas de hora extra para dashboard
 * {@link /api/ponto/folha-he/historico}
 */
export async function folhaHoraExtraControllerHistorico(
  params?: FolhaHoraExtraControllerHistoricoQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FolhaHoraExtraControllerHistoricoQueryResponse,
    ResponseErrorConfig<
      | FolhaHoraExtraControllerHistorico400
      | FolhaHoraExtraControllerHistorico401
      | FolhaHoraExtraControllerHistorico403
    >,
    unknown
  >({
    method: 'GET',
    url: getFolhaHoraExtraControllerHistoricoUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
