/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FuncionarioControllerConsultaFuncionariosMethodQueryResponse, FuncionarioControllerConsultaFuncionariosMethodQueryParams } from "../models/FuncionarioControllerConsultaFuncionariosMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFuncionarioControllerConsultaFuncionariosMethodUrl() {
  return `http://192.168.99.129:30001/api/ponto/funcionario/funcionarios` as const
}

/**
 * {@link /api/ponto/funcionario/funcionarios}
 */
export async function funcionarioControllerConsultaFuncionariosMethod(params?: FuncionarioControllerConsultaFuncionariosMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FuncionarioControllerConsultaFuncionariosMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFuncionarioControllerConsultaFuncionariosMethodUrl().toString(), params, ... requestConfig })
return res.data
}