/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { FuncionarioControllerConsultarCentroDeCustoMethodQueryResponse } from '../models/FuncionarioControllerConsultarCentroDeCustoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFuncionarioControllerConsultarCentroDeCustoMethodUrl() {
  const res = {
    method: 'GET',
    url: `http://192.168.99.129:30001/api/ponto/funcionario/centro-custo` as const,
  };
  return res;
}

/**
 * {@link /api/ponto/funcionario/centro-custo}
 */
export async function funcionarioControllerConsultarCentroDeCustoMethod(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionarioControllerConsultarCentroDeCustoMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFuncionarioControllerConsultarCentroDeCustoMethodUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
