/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FuncionarioControllerConsultaFuncionariosLegadoQueryResponse,
  FuncionarioControllerConsultaFuncionariosLegadoQueryParams,
} from '../models/FuncionarioControllerConsultaFuncionariosLegado';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFuncionarioControllerConsultaFuncionariosLegadoUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/funcionario/funcionarios` as const,
  };
  return res;
}

/**
 * {@link /api/ponto/funcionario/funcionarios}
 */
export async function funcionarioControllerConsultaFuncionariosLegado(
  params?: FuncionarioControllerConsultaFuncionariosLegadoQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionarioControllerConsultaFuncionariosLegadoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFuncionarioControllerConsultaFuncionariosLegadoUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
