/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FuncionarioControllerConsultaFuncionariosMethodQueryResponse,
  FuncionarioControllerConsultaFuncionariosMethodQueryParams,
} from '../models/FuncionarioControllerConsultaFuncionariosMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFuncionarioControllerConsultaFuncionariosMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/ponto/funcionario/funcionarios` as const,
  };
  return res;
}

/**
 * {@link /api/ponto/funcionario/funcionarios}
 */
export async function funcionarioControllerConsultaFuncionariosMethod(
  params?: FuncionarioControllerConsultaFuncionariosMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionarioControllerConsultaFuncionariosMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFuncionarioControllerConsultaFuncionariosMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
