/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FuncionarioControllerConsultarCentroDeCustoMethodQueryResponse } from "../models/FuncionarioControllerConsultarCentroDeCustoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFuncionarioControllerConsultarCentroDeCustoMethodUrl() {
  return `http://192.168.99.129:30001/api/ponto/funcionario/centro-custo` as const
}

/**
 * {@link /api/ponto/funcionario/centro-custo}
 */
export async function funcionarioControllerConsultarCentroDeCustoMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FuncionarioControllerConsultarCentroDeCustoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFuncionarioControllerConsultarCentroDeCustoMethodUrl().toString(), ... requestConfig })
return res.data
}