/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { PontoControllerSicnronizaPontoMethodMutationResponse } from '../models/PontoControllerSicnronizaPontoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPontoControllerSicnronizaPontoMethodUrl() {
  const res = {
    method: 'POST',
    url: `http://192.168.99.129:30001/api/ponto/sincroniza` as const,
  };
  return res;
}

/**
 * {@link /api/ponto/sincroniza}
 */
export async function pontoControllerSicnronizaPontoMethod(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PontoControllerSicnronizaPontoMethodMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'POST',
    url: getPontoControllerSicnronizaPontoMethodUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
