/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PontoControllerProcessaTipoMarcacaoMethodMutationRequest, PontoControllerProcessaTipoMarcacaoMethodMutationResponse } from "../models/PontoControllerProcessaTipoMarcacaoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPontoControllerProcessaTipoMarcacaoMethodUrl() {
  return `https://app.prod.ethos/api/ponto/marcacao` as const
}

/**
 * {@link /api/ponto/marcacao}
 */
export async function pontoControllerProcessaTipoMarcacaoMethod(data?: PontoControllerProcessaTipoMarcacaoMethodMutationRequest, config: Partial<RequestConfig<PontoControllerProcessaTipoMarcacaoMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PontoControllerProcessaTipoMarcacaoMethodMutationResponse, ResponseErrorConfig<Error>, PontoControllerProcessaTipoMarcacaoMethodMutationRequest>({ method : "POST", url : getPontoControllerProcessaTipoMarcacaoMethodUrl().toString(), data, ... requestConfig })
return res.data
}