/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PontoControllerConsultaMarcacaoMethodQueryResponse, PontoControllerConsultaMarcacaoMethodQueryParams } from "../models/PontoControllerConsultaMarcacaoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPontoControllerConsultaMarcacaoMethodUrl() {
  return `https://app.prod.ethos/api/ponto/registro` as const
}

/**
 * {@link /api/ponto/registro}
 */
export async function pontoControllerConsultaMarcacaoMethod(params?: PontoControllerConsultaMarcacaoMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PontoControllerConsultaMarcacaoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPontoControllerConsultaMarcacaoMethodUrl().toString(), params, ... requestConfig })
return res.data
}