/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse, PontoKPIControllerConsultarMaisHorasIrregularesQueryParams } from "../models/PontoKPIControllerConsultarMaisHorasIrregulares";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPontoKPIControllerConsultarMaisHorasIrregularesUrl() {
  return `http://192.168.99.129:30001/api/ponto/kpi/mais-horas-irregulares` as const
}

/**
 * {@link /api/ponto/kpi/mais-horas-irregulares}
 */
export async function pontoKPIControllerConsultarMaisHorasIrregulares(params?: PontoKPIControllerConsultarMaisHorasIrregularesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPontoKPIControllerConsultarMaisHorasIrregularesUrl().toString(), params, ... requestConfig })
return res.data
}