/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PontoControllerSicnronizaPontoMethodMutationResponse } from "../models/PontoControllerSicnronizaPontoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPontoControllerSicnronizaPontoMethodUrl() {
  return `http://192.168.99.129:30001/api/ponto/sincroniza` as const
}

/**
 * {@link /api/ponto/sincroniza}
 */
export async function pontoControllerSicnronizaPontoMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PontoControllerSicnronizaPontoMethodMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPontoControllerSicnronizaPontoMethodUrl().toString(), ... requestConfig })
return res.data
}