/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse,
  PontoKPIControllerConsultarMaisHorasIrregularesQueryParams,
} from '../models/PontoKPIControllerConsultarMaisHorasIrregulares';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPontoKPIControllerConsultarMaisHorasIrregularesUrl() {
  const res = {
    method: 'GET',
    url: `http://192.168.99.129:30001/api/ponto/kpi/mais-horas-irregulares` as const,
  };
  return res;
}

/**
 * {@link /api/ponto/kpi/mais-horas-irregulares}
 */
export async function pontoKPIControllerConsultarMaisHorasIrregulares(
  params?: PontoKPIControllerConsultarMaisHorasIrregularesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PontoKPIControllerConsultarMaisHorasIrregularesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getPontoKPIControllerConsultarMaisHorasIrregularesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
