/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LogixPluginControllerProcessarAceiteCompraMutationRequest,
  LogixPluginControllerProcessarAceiteCompraMutationResponse,
} from '../models/LogixPluginControllerProcessarAceiteCompra';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLogixPluginControllerProcessarAceiteCompraUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/logix-plugin/aceite-compra` as const,
  };
  return res;
}

/**
 * @summary Aprova um pedido de compra pendente
 * {@link /api/logix-plugin/aceite-compra}
 */
export async function logixPluginControllerProcessarAceiteCompra(
  data: LogixPluginControllerProcessarAceiteCompraMutationRequest,
  config: Partial<
    RequestConfig<LogixPluginControllerProcessarAceiteCompraMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    LogixPluginControllerProcessarAceiteCompraMutationResponse,
    ResponseErrorConfig<Error>,
    LogixPluginControllerProcessarAceiteCompraMutationRequest
  >({
    method: 'POST',
    url: getLogixPluginControllerProcessarAceiteCompraUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
