/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LogixPluginControllerConsultarDetalhesPedidoQueryResponse,
  LogixPluginControllerConsultarDetalhesPedidoPathParams,
} from '../models/LogixPluginControllerConsultarDetalhesPedido';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLogixPluginControllerConsultarDetalhesPedidoUrl(
  pedido: LogixPluginControllerConsultarDetalhesPedidoPathParams['pedido'],
  codEmpresa?: LogixPluginControllerConsultarDetalhesPedidoPathParams['codEmpresa'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/logix-plugin/aceite-compra/${pedido}` as const,
  };
  return res;
}

/**
 * @summary Consulta os detalhes de um pedido pendente
 * {@link /api/logix-plugin/aceite-compra/:pedido}
 */
export async function logixPluginControllerConsultarDetalhesPedido(
  pedido: LogixPluginControllerConsultarDetalhesPedidoPathParams['pedido'],
  codEmpresa?: LogixPluginControllerConsultarDetalhesPedidoPathParams['codEmpresa'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LogixPluginControllerConsultarDetalhesPedidoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getLogixPluginControllerConsultarDetalhesPedidoUrl(
      pedido,
      codEmpresa,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
