/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { LogixPluginControllerListarPedidosAceiteCompraQueryResponse } from '../models/LogixPluginControllerListarPedidosAceiteCompra';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLogixPluginControllerListarPedidosAceiteCompraUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/logix-plugin/aceite-compra` as const,
  };
  return res;
}

/**
 * @summary Lista pedidos em aberto pendentes de aprovação
 * {@link /api/logix-plugin/aceite-compra}
 */
export async function logixPluginControllerListarPedidosAceiteCompra(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LogixPluginControllerListarPedidosAceiteCompraQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getLogixPluginControllerListarPedidosAceiteCompraUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
