/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedChatConversationSummaryDtoDto } from './PaginatedChatConversationSummaryDtoDto';

export type ChatbotEstruturaControllerListConversationsQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @type string | undefined
   */
  userId?: string;
  /**
   * @type string | undefined
   */
  contextType?: string;
  /**
   * @type string | undefined
   */
  model?: string;
  /**
   * @type string | undefined
   */
  dateFrom?: string;
  /**
   * @type string | undefined
   */
  dateTo?: string;
};

export type ChatbotEstruturaControllerListConversationsError =
  PaginatedChatConversationSummaryDtoDto;

export type ChatbotEstruturaControllerListConversationsQueryResponse = any;

export type ChatbotEstruturaControllerListConversationsQuery = {
  Response: any;
  QueryParams: ChatbotEstruturaControllerListConversationsQueryParams;
  Errors: any;
};
