/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatConversationLookupDto } from './ChatConversationLookupDto';
import type { UpdateChatConversationReqDto } from './UpdateChatConversationReqDto';

export type ChatbotEstruturaControllerUpdateConversationPathParams = {
  /**
   * @type string
   */
  conversationId: string;
};

export type ChatbotEstruturaControllerUpdateConversationError =
  ChatConversationLookupDto;

export type ChatbotEstruturaControllerUpdateConversationMutationRequest =
  UpdateChatConversationReqDto;

export type ChatbotEstruturaControllerUpdateConversationMutationResponse = any;

export type ChatbotEstruturaControllerUpdateConversationMutation = {
  Response: any;
  Request: ChatbotEstruturaControllerUpdateConversationMutationRequest;
  PathParams: ChatbotEstruturaControllerUpdateConversationPathParams;
  Errors: any;
};
