/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatCompletionUsageDto = {
  /**
   * @type number
   */
  promptTokens: number;
  /**
   * @type number
   */
  completionTokens: number;
  /**
   * @type number
   */
  totalTokens: number;
};
