/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatConversationShareDto = {
  /**
   * @type string
   */
  conversationId: string;
  /**
   * @type string
   */
  shareId: string;
  /**
   * @type string
   */
  sharePath: string;
};
