/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatbotEstruturaControllerDeleteConversationPathParams = {
  /**
   * @type string
   */
  conversationId: string;
};

export type ChatbotEstruturaControllerDeleteConversation204 = any;

export type ChatbotEstruturaControllerDeleteConversationMutationResponse =
  ChatbotEstruturaControllerDeleteConversation204;

export type ChatbotEstruturaControllerDeleteConversationMutation = {
  Response: ChatbotEstruturaControllerDeleteConversation204;
  PathParams: ChatbotEstruturaControllerDeleteConversationPathParams;
  Errors: any;
};
