/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ChatConversationSummaryDto = {
  /**
   * @type string
   */
  conversationId: string;
  /**
   * @type string
   */
  sessionId: string;
  /**
   * @type string
   */
  contextType: string;
  /**
   * @type string | undefined
   */
  title?: string;
  /**
   * @type string
   */
  model: string;
  /**
   * @type object
   */
  lastMessagePreview?: object | null;
  /**
   * @type string, date-time
   */
  lastMessageAt: Date;
  /**
   * @type number
   */
  messageCount: number;
};
