/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum ChatAttachmentDtoTypeEnum {
  image = 'image',
}

export type ChatAttachmentDto = {
  /**
   * @type string
   */
  type: ChatAttachmentDtoTypeEnum;
  /**
   * @type string
   */
  url: string;
  /**
   * @type string | undefined
   */
  mimeType?: string;
  /**
   * @type string | undefined
   */
  alt?: string;
  /**
   * @type string | undefined
   */
  partcode?: string;
};
