/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCompletionUsageDto } from './ChatCompletionUsageDto';
import type { ChatMessageDto } from './ChatMessageDto';

export enum ChatCompletionDtoFinishReasonEnum {
  stop = 'stop',
  tool_calls = 'tool_calls',
  length = 'length',
}

export type ChatCompletionDto = {
  /**
   * @type object
   */
  message: ChatMessageDto;
  /**
   * @type string
   */
  finishReason: ChatCompletionDtoFinishReasonEnum;
  /**
   * @type object | undefined
   */
  usage?: ChatCompletionUsageDto;
};
