/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatConversationLookupDto } from './ChatConversationLookupDto';
import type { CreateChatConversationReqDto } from './CreateChatConversationReqDto';

export type ChatbotEstruturaControllerCreateConversationError =
  ChatConversationLookupDto;

export type ChatbotEstruturaControllerCreateConversationMutationRequest =
  CreateChatConversationReqDto;

export type ChatbotEstruturaControllerCreateConversationMutationResponse = any;

export type ChatbotEstruturaControllerCreateConversationMutation = {
  Response: any;
  Request: ChatbotEstruturaControllerCreateConversationMutationRequest;
  Errors: any;
};
