/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InsertItemChecklistDTO } from './InsertItemChecklistDTO';

export type CheckListControllerInsertItemCheckList201 = any;

export type CheckListControllerInsertItemCheckListMutationRequest =
  InsertItemChecklistDTO;

export type CheckListControllerInsertItemCheckListMutationResponse =
  CheckListControllerInsertItemCheckList201;

export type CheckListControllerInsertItemCheckListMutation = {
  Response: CheckListControllerInsertItemCheckList201;
  Request: CheckListControllerInsertItemCheckListMutationRequest;
  Errors: any;
};
