/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CheckListItemResDto } from './CheckListItemResDto';

export type CheckListResDto = {
  /**
   * @type array
   */
  itens: CheckListItemResDto[];
  /**
   * @type string
   */
  estrutura: string;
};
