/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CheckListResDto } from './CheckListResDto';

export type CheckListControllerGetChecklistQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type CheckListControllerGetChecklistError = CheckListResDto[];

export type CheckListControllerGetChecklistQueryResponse = any;

export type CheckListControllerGetChecklistQuery = {
  Response: any;
  QueryParams: CheckListControllerGetChecklistQueryParams;
  Errors: any;
};
