/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CheckListItemResStatusDto } from './CheckListItemResStatusDto';

export type CheckListStatusResDto = {
  /**
   * @type array
   */
  itens: CheckListItemResStatusDto[];
  /**
   * @type string
   */
  estrutura: string;
  /**
   * @type string
   */
  tag: string;
};
