/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CheckListStatusResDto } from './CheckListStatusResDto';

export type CheckListControllerGetChecklistAvaiableQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
  /**
   * @description Tag textual livre do checklist
   * @type string
   */
  tag: string;
};

export type CheckListControllerGetChecklistAvaiableError =
  CheckListStatusResDto;

export type CheckListControllerGetChecklistAvaiableQueryResponse = any;

export type CheckListControllerGetChecklistAvaiableQuery = {
  Response: any;
  QueryParams: CheckListControllerGetChecklistAvaiableQueryParams;
  Errors: any;
};
