/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedChecklistRealizadoResDTODto } from './PaginatedChecklistRealizadoResDTODto';

export type CheckListControllerListarChecklistsRealizadosQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
  /**
   * @description Filtra pelo código do item final do checklist.
   * @type string | undefined
   */
  codigoItem?: string;
  /**
   * @description Filtra os checklists realizados nesta data.
   * @type string | undefined
   */
  dataRealizacao?: string;
  /**
   * @description Filtra pela ordem de produção.
   * @type string | undefined
   */
  orderNum?: string;
  /**
   * @description Filtra pelo contexto (tag).
   * @type string | undefined
   */
  tag?: string;
};

/**
 * @description Lista paginada de checklists realizados.
 */
export type CheckListControllerListarChecklistsRealizadosError =
  PaginatedChecklistRealizadoResDTODto;

export type CheckListControllerListarChecklistsRealizadosQueryResponse = any;

export type CheckListControllerListarChecklistsRealizadosQuery = {
  Response: any;
  QueryParams: CheckListControllerListarChecklistsRealizadosQueryParams;
  Errors: any;
};
