/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CheckListTagsResDto } from './CheckListTagsResDto';

export type CheckListControllerGetChecklistTagsQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type CheckListControllerGetChecklistTagsError = CheckListTagsResDto;

export type CheckListControllerGetChecklistTagsQueryResponse = any;

export type CheckListControllerGetChecklistTagsQuery = {
  Response: any;
  QueryParams: CheckListControllerGetChecklistTagsQueryParams;
  Errors: any;
};
