/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RemoveItemChecklistDTO } from './RemoveItemChecklistDTO';

export type CheckListControllerDeleteItemInCheckList200 = any;

export type CheckListControllerDeleteItemInCheckListMutationRequest =
  RemoveItemChecklistDTO;

export type CheckListControllerDeleteItemInCheckListMutationResponse =
  CheckListControllerDeleteItemInCheckList200;

export type CheckListControllerDeleteItemInCheckListMutation = {
  Response: CheckListControllerDeleteItemInCheckList200;
  Request: CheckListControllerDeleteItemInCheckListMutationRequest;
  Errors: any;
};
