/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateChatConversationReqDto = {
  /**
   * @type string
   */
  contextType: string;
  /**
   * @type string | undefined
   */
  title?: string;
};
