/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetAnaliseResDTO } from './GetAnaliseResDTO';

export type EstruturaControllerAnaliseEstruturaMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerAnaliseEstruturaMethod200 = GetAnaliseResDTO[];

export type EstruturaControllerAnaliseEstruturaMethodQueryResponse =
  EstruturaControllerAnaliseEstruturaMethod200;

export type EstruturaControllerAnaliseEstruturaMethodQuery = {
  Response: EstruturaControllerAnaliseEstruturaMethod200;
  QueryParams: EstruturaControllerAnaliseEstruturaMethodQueryParams;
  Errors: any;
};
