/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EstruturaControllerRemoveInNeo4JQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerRemoveInNeo4J200 = any;

export type EstruturaControllerRemoveInNeo4JMutationResponse =
  EstruturaControllerRemoveInNeo4J200;

export type EstruturaControllerRemoveInNeo4JMutation = {
  Response: EstruturaControllerRemoveInNeo4J200;
  QueryParams: EstruturaControllerRemoveInNeo4JQueryParams;
  Errors: any;
};
