/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEstruturaDependentesDTO } from './ResEstruturaDependentesDTO';

export type EstruturaControllerGetEstruturasDedendentesMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerGetEstruturasDedendentesMethodError =
  ResEstruturaDependentesDTO[];

export type EstruturaControllerGetEstruturasDedendentesMethodQueryResponse =
  any;

export type EstruturaControllerGetEstruturasDedendentesMethodQuery = {
  Response: any;
  QueryParams: EstruturaControllerGetEstruturasDedendentesMethodQueryParams;
  Errors: any;
};
