/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EstruturaInternalControllerConsultarRoteiroQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaInternalControllerConsultarRoteiroError = string[];

export type EstruturaInternalControllerConsultarRoteiroQueryResponse = any;

export type EstruturaInternalControllerConsultarRoteiroQuery = {
  Response: any;
  QueryParams: EstruturaInternalControllerConsultarRoteiroQueryParams;
  Errors: any;
};
