/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEstruturaTreeDTO } from './ResEstruturaTreeDTO';

export type EstruturaControllerEstrturaAsTreeMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerEstrturaAsTreeMethod200 = ResEstruturaTreeDTO;

export type EstruturaControllerEstrturaAsTreeMethodQueryResponse =
  EstruturaControllerEstrturaAsTreeMethod200;

export type EstruturaControllerEstrturaAsTreeMethodQuery = {
  Response: EstruturaControllerEstrturaAsTreeMethod200;
  QueryParams: EstruturaControllerEstrturaAsTreeMethodQueryParams;
  Errors: any;
};
