/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEstruturaItemDTO } from './ResEstruturaItemDTO';

export type EstruturaInternalControllerGetItemDeControleQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaInternalControllerGetItemDeControleError =
  ResEstruturaItemDTO[];

export type EstruturaInternalControllerGetItemDeControleQueryResponse = any;

export type EstruturaInternalControllerGetItemDeControleQuery = {
  Response: any;
  QueryParams: EstruturaInternalControllerGetItemDeControleQueryParams;
  Errors: any;
};
