/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EstruturaControllerConsultaCodigosServicalMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerConsultaCodigosServicalMethod200 = any;

export type EstruturaControllerConsultaCodigosServicalMethodQueryResponse =
  EstruturaControllerConsultaCodigosServicalMethod200;

export type EstruturaControllerConsultaCodigosServicalMethodQuery = {
  Response: EstruturaControllerConsultaCodigosServicalMethod200;
  QueryParams: EstruturaControllerConsultaCodigosServicalMethodQueryParams;
  Errors: any;
};
