/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConsultaPorPartcodeReqDTO } from './ConsultaPorPartcodeReqDTO';

export type EstruturaExportControllerExportToNeo4J201 = any;

export type EstruturaExportControllerExportToNeo4JMutationRequest =
  ConsultaPorPartcodeReqDTO;

export type EstruturaExportControllerExportToNeo4JMutationResponse =
  EstruturaExportControllerExportToNeo4J201;

export type EstruturaExportControllerExportToNeo4JMutation = {
  Response: EstruturaExportControllerExportToNeo4J201;
  Request: EstruturaExportControllerExportToNeo4JMutationRequest;
  Errors: any;
};
