/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EstruturaInternalControllerGetEstruturasDependentesQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaInternalControllerGetEstruturasDependentes200 = any;

export type EstruturaInternalControllerGetEstruturasDependentesQueryResponse =
  EstruturaInternalControllerGetEstruturasDependentes200;

export type EstruturaInternalControllerGetEstruturasDependentesQuery = {
  Response: EstruturaInternalControllerGetEstruturasDependentes200;
  QueryParams: EstruturaInternalControllerGetEstruturasDependentesQueryParams;
  Errors: any;
};
