/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResItemDetalhadoDTO } from './ResItemDetalhadoDTO';

export type EstruturaControllerDetalharItensQueryParams = {
  /**
   * @type array
   */
  partcodes: string[];
};

export type EstruturaControllerDetalharItens200 = ResItemDetalhadoDTO[];

export type EstruturaControllerDetalharItensQueryResponse =
  EstruturaControllerDetalharItens200;

export type EstruturaControllerDetalharItensQuery = {
  Response: EstruturaControllerDetalharItens200;
  QueryParams: EstruturaControllerDetalharItensQueryParams;
  Errors: any;
};
