/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EstruturaImagemControllerGetImagemDaEstruturaMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaImagemControllerGetImagemDaEstruturaMethod200 = any;

export type EstruturaImagemControllerGetImagemDaEstruturaMethodQueryResponse =
  EstruturaImagemControllerGetImagemDaEstruturaMethod200;

export type EstruturaImagemControllerGetImagemDaEstruturaMethodQuery = {
  Response: EstruturaImagemControllerGetImagemDaEstruturaMethod200;
  QueryParams: EstruturaImagemControllerGetImagemDaEstruturaMethodQueryParams;
  Errors: any;
};
