/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEstruturaListaDTO } from './ResEstruturaListaDTO';

export type EstruturaControllerEstrturaAsListMethodQueryParams = {
  /**
   * @description O partcode do item
   * @type string
   */
  partcode: string;
};

export type EstruturaControllerEstrturaAsListMethod200 = ResEstruturaListaDTO[];

export type EstruturaControllerEstrturaAsListMethodQueryResponse =
  EstruturaControllerEstrturaAsListMethod200;

export type EstruturaControllerEstrturaAsListMethodQuery = {
  Response: EstruturaControllerEstrturaAsListMethod200;
  QueryParams: EstruturaControllerEstrturaAsListMethodQueryParams;
  Errors: any;
};
