/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ItemMetricas } from './ItemMetricas';
import type { SetorAnaliseDTO } from './SetorAnaliseDTO';

export type GetAnaliseResDTO = {
  /**
   * @type object
   */
  setor: SetorAnaliseDTO;
  /**
   * @type array
   */
  analise: ItemMetricas[];
};
