/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InsertItemChecklistDTO = {
  /**
   * @type array
   */
  partcodes: string[];
  /**
   * @type string
   */
  partcodePai: string;
  /**
   * @type string
   */
  tag: string;
};
