/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MetricasDTO } from './MetricasDTO';
import type { ResEstruturaItemDTO } from './ResEstruturaItemDTO';

export type ItemMetricas = {
  /**
   * @type object
   */
  item: ResEstruturaItemDTO;
  /**
   * @type array
   */
  metricas: MetricasDTO[];
  /**
   * @type object | undefined
   */
  processo?: {
    /**
     * @type string | undefined
     */
    operacao?: string;
    /**
     * @type number | undefined
     */
    seqOperacao?: number;
    /**
     * @type string | undefined
     */
    roteiro?: string;
    /**
     * @type number | undefined
     */
    roteiroAlternativo?: number;
  };
};
