/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MetricasDTO } from './MetricasDTO';
import type { ResEstruturaItemDTO } from './ResEstruturaItemDTO';

export type ItemMetricas = {
  /**
   * @type object
   */
  item: ResEstruturaItemDTO;
  /**
   * @type array
   */
  metricas: MetricasDTO[];
};
