/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChecklistRealizadoResDTO } from './ChecklistRealizadoResDTO';

export type PaginatedChecklistRealizadoResDTODto = {
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  page: number;
  /**
   * @type number
   */
  limit: number;
  /**
   * @type number
   */
  totalPages: number;
  /**
   * @description Lista de itens paginados do tipo ChecklistRealizadoResDTO.
   * @type array
   */
  data: ChecklistRealizadoResDTO[];
};
