/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProgressoChecklistResDTO = {
  /**
   * @type object
   */
  orderNum?: object | null;
  /**
   * @type string
   */
  codigoItem: string;
  /**
   * @type string
   */
  tag: string;
  /**
   * @type object
   */
  quantidadePlanejada?: object | null;
  /**
   * @type number
   */
  totalSeparado: number;
  /**
   * @type object
   */
  restante?: object | null;
  /**
   * @type object
   */
  excedente?: object | null;
  /**
   * @type object
   */
  concluido?: object | null;
};
