/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResEstruturaItemDTO } from './ResEstruturaItemDTO';

export type ResEstruturaListaDTO = {
  /**
   * @type array
   */
  estrutura: ResEstruturaItemDTO[];
  /**
   * @type object
   */
  detalhes: object;
};
