/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResOperacaoDTO = {
  /**
   * @type string
   */
  operacao: string;
  /**
   * @type number
   */
  tempo: number;
  /**
   * @type string
   */
  roteiro: string;
  /**
   * @type string
   */
  roteiroAlternativo: string;
};
