/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResumoTempoSetorItemDTO } from './ResumoTempoSetorItemDTO';

export type ResumoTempoSetorDTO = {
  /**
   * @description Item final solicitado no resumo.
   * @type string
   */
  itemFinal: string;
  /**
   * @type array
   */
  resumoSetores: ResumoTempoSetorItemDTO[];
};
