/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResumoTempoSetorItemDTO = {
  /**
   * @type string
   */
  setorNome: string;
  /**
   * @type string
   */
  setorCodigo: string;
  /**
   * @description Tempo total de producao somado no setor, em horas decimais.
   * @type number
   */
  tempoProdTotalHr: number;
  /**
   * @description Metragem quadrada total somada no setor quando a metrica se aplica.
   * @type number | undefined
   */
  m2Total?: number;
  /**
   * @description Indica se o conjunto de itens desse setor possui quimicos quando a metrica se aplica.
   * @type boolean | undefined
   */
  temQuimicos?: boolean;
};
