/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SetorAnaliseDTO = {
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  codigo: string;
};
