/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SubmitChecklistDTO = {
  /**
   * @type string | undefined
   */
  COD_ITEM_FINAL?: string;
  /**
   * @type string | undefined
   */
  ORDER_NUM?: string;
  /**
   * @type string
   */
  CHECKLIST_TAG: string;
  /**
   * @type string
   */
  SEPARADOR: string;
};
