/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToolCallFunctionDto } from './ToolCallFunctionDto';

export enum ToolCallDtoTypeEnum {
  function = 'function',
}

export type ToolCallDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  type: ToolCallDtoTypeEnum;
  /**
   * @type object
   */
  function: ToolCallFunctionDto;
};
