/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthorizationContextDTO = {
  /**
   * @type string
   */
  userId: string;
  /**
   * @type array
   */
  cargos: string[];
  /**
   * @type array
   */
  centrosCusto: number[];
  /**
   * @type object
   */
  version: object;
};
