/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthControllerGenerateInvite200 = any;

export type AuthControllerGenerateInviteMutationRequest = {
  /**
   * @type array | undefined
   */
  cargos?: string[];
};

export type AuthControllerGenerateInviteMutationResponse =
  AuthControllerGenerateInvite200;

export type AuthControllerGenerateInviteMutation = {
  Response: AuthControllerGenerateInvite200;
  Request: AuthControllerGenerateInviteMutationRequest;
  Errors: any;
};
