/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthControllerValidateInvitePathParams = {
  /**
   * @type string
   */
  token: string;
};

/**
 * @description Invite token is valid
 * @example [object Object]
 */
export type AuthControllerValidateInvite200 = any;

/**
 * @description Invalid or expired invite token
 */
export type AuthControllerValidateInvite400 = any;

export type AuthControllerValidateInviteQueryResponse =
  AuthControllerValidateInvite200;

export type AuthControllerValidateInviteQuery = {
  Response: AuthControllerValidateInvite200;
  PathParams: AuthControllerValidateInvitePathParams;
  Errors: AuthControllerValidateInvite400;
};
