/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Token validity
 * @example [object Object]
 */
export type AuthControllerCheckToken200 = any;

export type AuthControllerCheckTokenMutationResponse =
  AuthControllerCheckToken200;

export type AuthControllerCheckTokenMutation = {
  Response: AuthControllerCheckToken200;
  Errors: any;
};
