/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthorizationContextDTO } from './AuthorizationContextDTO';

export type AuthorizationControllerGetMine200 = AuthorizationContextDTO;

export type AuthorizationControllerGetMineQueryResponse =
  AuthorizationControllerGetMine200;

export type AuthorizationControllerGetMineQuery = {
  Response: AuthorizationControllerGetMine200;
  Errors: any;
};
