/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserResponseDTO } from './UserResponseDTO';

/**
 * @description List of all registered users
 */
export type AuthControllerListUsers200 = UserResponseDTO[];

export type AuthControllerListUsersQueryResponse = AuthControllerListUsers200;

export type AuthControllerListUsersQuery = {
  Response: AuthControllerListUsers200;
  Errors: any;
};
