/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthControllerValidateUserPathParams = {
  /**
   * @type string
   */
  token: string;
};

/**
 * @description User successfully validated and created
 */
export type AuthControllerValidateUser200 = string;

/**
 * @description Validation token not found
 */
export type AuthControllerValidateUser404 = any;

export type AuthControllerValidateUserQueryResponse =
  AuthControllerValidateUser200;

export type AuthControllerValidateUserQuery = {
  Response: AuthControllerValidateUser200;
  PathParams: AuthControllerValidateUserPathParams;
  Errors: AuthControllerValidateUser404;
};
