/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description User successfully logged out
 */
export type AuthControllerLogout200 = any;

export type AuthControllerLogoutMutationResponse = AuthControllerLogout200;

export type AuthControllerLogoutMutation = {
  Response: AuthControllerLogout200;
  Errors: any;
};
