/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from './CreateUserDto';

export type AuthControllerRegisterWithInvitePathParams = {
  /**
   * @type string
   */
  registrationToken: string;
};

export type AuthControllerRegisterWithInvite201 = any;

export type AuthControllerRegisterWithInviteMutationRequest = CreateUserDto;

export type AuthControllerRegisterWithInviteMutationResponse =
  AuthControllerRegisterWithInvite201;

export type AuthControllerRegisterWithInviteMutation = {
  Response: AuthControllerRegisterWithInvite201;
  Request: AuthControllerRegisterWithInviteMutationRequest;
  PathParams: AuthControllerRegisterWithInvitePathParams;
  Errors: any;
};
