/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SetUserCargoDTO } from "./SetUserCargoDTO";

export type CargoControllerSetUserCargoMethod200 = any;

export type CargoControllerSetUserCargoMethodMutationRequest = SetUserCargoDTO;

export type CargoControllerSetUserCargoMethodMutationResponse = CargoControllerSetUserCargoMethod200;

export type CargoControllerSetUserCargoMethodMutation = {
    Response: CargoControllerSetUserCargoMethod200;
    Request: CargoControllerSetUserCargoMethodMutationRequest;
    Errors: any;
};