/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CompleteTotpEnrollmentDto = {
  /**
   * @type string
   */
  enrollmentId: string;
  /**
   * @type string
   */
  code: string;
};
