/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type NotificarUsuarioEmailDTO = {
  /**
   * @type string
   */
  usuarioId: string;
  /**
   * @type string
   */
  subject: string;
  /**
   * @type string | undefined
   */
  text?: string;
  /**
   * @type string | undefined
   */
  html?: string;
};
