/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RotateRecoveryCodesDto } from './RotateRecoveryCodesDto';

export type TwoFactorSelfServiceControllerRotateRecoveryCodes201 = any;

export type TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest =
  RotateRecoveryCodesDto;

export type TwoFactorSelfServiceControllerRotateRecoveryCodesMutationResponse =
  TwoFactorSelfServiceControllerRotateRecoveryCodes201;

export type TwoFactorSelfServiceControllerRotateRecoveryCodesMutation = {
  Response: TwoFactorSelfServiceControllerRotateRecoveryCodes201;
  Request: TwoFactorSelfServiceControllerRotateRecoveryCodesMutationRequest;
  Errors: any;
};
