/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToggleServiceAccountBypassDto } from './ToggleServiceAccountBypassDto';

export type TwoFactorSelfServiceControllerSetServiceAccountBypass201 = any;

export type TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest =
  ToggleServiceAccountBypassDto;

export type TwoFactorSelfServiceControllerSetServiceAccountBypassMutationResponse =
  TwoFactorSelfServiceControllerSetServiceAccountBypass201;

export type TwoFactorSelfServiceControllerSetServiceAccountBypassMutation = {
  Response: TwoFactorSelfServiceControllerSetServiceAccountBypass201;
  Request: TwoFactorSelfServiceControllerSetServiceAccountBypassMutationRequest;
  Errors: any;
};
