/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum TwoFactorGuardPolicyDtoMethodsEnum {
  email = 'email',
  totp = 'totp',
  recovery_code = 'recovery_code',
}

export type TwoFactorGuardPolicyDto = {
  /**
   * @type string
   */
  action: string;
  /**
   * @type number
   */
  maxAgeSeconds: number;
  /**
   * @type array | undefined
   */
  bindToParams?: string[];
  /**
   * @type array | undefined
   */
  methods?: TwoFactorGuardPolicyDtoMethodsEnum[];
  /**
   * @type boolean | undefined
   */
  singleUse?: boolean;
  /**
   * @type boolean | undefined
   */
  bindIp?: boolean;
  /**
   * @type boolean | undefined
   */
  bindUserAgent?: boolean;
  /**
   * @type number | undefined
   */
  challengeTtlSeconds?: number;
  /**
   * @type number | undefined
   */
  assertionTtlSeconds?: number;
  /**
   * @type number | undefined
   */
  maxAttempts?: number;
  /**
   * @type array | undefined
   */
  requiredRoles?: string[];
  /**
   * @type array | undefined
   */
  exemptRoles?: string[];
  /**
   * @type boolean | undefined
   */
  allowServiceAccountBypass?: boolean;
  /**
   * @type string | undefined
   */
  bypassReason?: string;
};
