/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TwoFactorGuardContextDto = {
  /**
   * @type string
   */
  userId: string;
  /**
   * @type string | undefined
   */
  userEmail?: string;
  /**
   * @type array | undefined
   */
  cargosLista?: string[];
  /**
   * @type boolean | undefined
   */
  serviceAccount?: boolean;
  /**
   * @type string
   */
  routeSignature: string;
  /**
   * @type string
   */
  resourceHash: string;
  /**
   * @type object | undefined
   */
  ip?: object;
  /**
   * @type string | undefined
   */
  userAgent?: string;
};
