/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TwoFactorGuardContextDto } from './TwoFactorGuardContextDto';
import type { TwoFactorGuardPolicyDto } from './TwoFactorGuardPolicyDto';

export type TwoFactorGuardEvaluationRequestDto = {
  /**
   * @type object
   */
  policy: TwoFactorGuardPolicyDto;
  /**
   * @type object
   */
  context: TwoFactorGuardContextDto;
};
