/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { VerifyTwoFactorDto } from './VerifyTwoFactorDto';

export type TwoFactorControllerVerifyChallengePathParams = {
  /**
   * @type string
   */
  challengeId: string;
};

/**
 * @description 2FA challenge verified successfully
 */
export type TwoFactorControllerVerifyChallenge200 = any;

export type TwoFactorControllerVerifyChallengeMutationRequest =
  VerifyTwoFactorDto;

export type TwoFactorControllerVerifyChallengeMutationResponse =
  TwoFactorControllerVerifyChallenge200;

export type TwoFactorControllerVerifyChallengeMutation = {
  Response: TwoFactorControllerVerifyChallenge200;
  Request: TwoFactorControllerVerifyChallengeMutationRequest;
  PathParams: TwoFactorControllerVerifyChallengePathParams;
  Errors: any;
};
