/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BeginTotpEnrollmentDto } from './BeginTotpEnrollmentDto';

export type TwoFactorSelfServiceControllerStartEnrollment201 = any;

export type TwoFactorSelfServiceControllerStartEnrollmentMutationRequest =
  BeginTotpEnrollmentDto;

export type TwoFactorSelfServiceControllerStartEnrollmentMutationResponse =
  TwoFactorSelfServiceControllerStartEnrollment201;

export type TwoFactorSelfServiceControllerStartEnrollmentMutation = {
  Response: TwoFactorSelfServiceControllerStartEnrollment201;
  Request: TwoFactorSelfServiceControllerStartEnrollmentMutationRequest;
  Errors: any;
};
