/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TwoFactorSelfServiceControllerGetStatus200 = any;

export type TwoFactorSelfServiceControllerGetStatusQueryResponse =
  TwoFactorSelfServiceControllerGetStatus200;

export type TwoFactorSelfServiceControllerGetStatusQuery = {
  Response: TwoFactorSelfServiceControllerGetStatus200;
  Errors: any;
};
