/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResLiderCentroCustoDTO } from './ResLiderCentroCustoDTO';

export type UserResponseDTO = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  avatar: string;
  /**
   * @type array
   */
  cargosLista: string[];
  /**
   * @type array
   */
  centrosCusto: ResLiderCentroCustoDTO[];
};
