/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NotificarUsuariosPorCargoEmailDTO } from './NotificarUsuariosPorCargoEmailDTO';

export type UserNotificationInternalControllerNotificarCargoPorEmail202 = any;

export type UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest =
  NotificarUsuariosPorCargoEmailDTO;

export type UserNotificationInternalControllerNotificarCargoPorEmailMutationResponse =
  UserNotificationInternalControllerNotificarCargoPorEmail202;

export type UserNotificationInternalControllerNotificarCargoPorEmailMutation = {
  Response: UserNotificationInternalControllerNotificarCargoPorEmail202;
  Request: UserNotificationInternalControllerNotificarCargoPorEmailMutationRequest;
  Errors: any;
};
