/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UserResponseDTO = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  avatar: string;
  /**
   * @type array
   */
  cargosLista: string[];
};
