/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum VerifyTwoFactorDtoMethodEnum {
  email = 'email',
  totp = 'totp',
  recovery_code = 'recovery_code',
}

export type VerifyTwoFactorDto = {
  /**
   * @type string
   */
  code: string;
  /**
   * @default "totp"
   * @type string | undefined
   */
  method?: VerifyTwoFactorDtoMethodEnum;
};
