/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CentroCustoLider } from './CentroCustoLider';

export type VincularLiderCentroCustoDTO = {
  /**
   * @type string
   */
  usuarioId: string;
  centroCustoCodigo: CentroCustoLider;
  /**
   * @description Mantido temporariamente por compatibilidade e ignorado pelo servidor.
   * @deprecated
   * @type string | undefined
   */
  usuarioNome?: string;
};
