/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LaserControllerBoardQueryResponse,
  LaserControllerBoardQueryParams,
} from '../models/LaserControllerBoard';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLaserControllerBoardUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/producao-fabrica/laser/board` as const,
  };
  return res;
}

/**
 * @summary Monta o quadro Kanban de produção do laser
 * {@link /api/producao-fabrica/laser/board}
 */
export async function laserControllerBoard(
  params?: LaserControllerBoardQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LaserControllerBoardQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getLaserControllerBoardUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
