/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LaserControllerRemoveMachineMutationResponse,
  LaserControllerRemoveMachinePathParams,
} from '../models/LaserControllerRemoveMachine';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLaserControllerRemoveMachineUrl(
  machineId: LaserControllerRemoveMachinePathParams['machineId'],
) {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/producao-fabrica/laser/machines/${machineId}` as const,
  };
  return res;
}

/**
 * @summary Remove uma máquina de laser sem cargas alocadas
 * {@link /api/producao-fabrica/laser/machines/:machineId}
 */
export async function laserControllerRemoveMachine(
  machineId: LaserControllerRemoveMachinePathParams['machineId'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LaserControllerRemoveMachineMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'DELETE',
    url: getLaserControllerRemoveMachineUrl(machineId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
