/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LaserControllerMoveCardMutationRequest,
  LaserControllerMoveCardMutationResponse,
  LaserControllerMoveCardPathParams,
} from '../models/LaserControllerMoveCard';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLaserControllerMoveCardUrl(
  numPrograma: LaserControllerMoveCardPathParams['numPrograma'],
) {
  const res = {
    method: 'PATCH',
    url: `https://app.ethos.ind.br/api/producao-fabrica/laser/board/cards/${numPrograma}` as const,
  };
  return res;
}

/**
 * @summary Aloca ou desaloca um programa de laser
 * {@link /api/producao-fabrica/laser/board/cards/:numPrograma}
 */
export async function laserControllerMoveCard(
  numPrograma: LaserControllerMoveCardPathParams['numPrograma'],
  data: LaserControllerMoveCardMutationRequest,
  config: Partial<RequestConfig<LaserControllerMoveCardMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    LaserControllerMoveCardMutationResponse,
    ResponseErrorConfig<Error>,
    LaserControllerMoveCardMutationRequest
  >({
    method: 'PATCH',
    url: getLaserControllerMoveCardUrl(numPrograma).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
