/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LaserControllerCreateMachineMutationRequest,
  LaserControllerCreateMachineMutationResponse,
} from '../models/LaserControllerCreateMachine';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLaserControllerCreateMachineUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/producao-fabrica/laser/machines` as const,
  };
  return res;
}

/**
 * @summary Cadastra uma máquina de laser
 * {@link /api/producao-fabrica/laser/machines}
 */
export async function laserControllerCreateMachine(
  data: LaserControllerCreateMachineMutationRequest,
  config: Partial<
    RequestConfig<LaserControllerCreateMachineMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    LaserControllerCreateMachineMutationResponse,
    ResponseErrorConfig<Error>,
    LaserControllerCreateMachineMutationRequest
  >({
    method: 'POST',
    url: getLaserControllerCreateMachineUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
