/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  LaserControllerListProgramsQueryResponse,
  LaserControllerListProgramsQueryParams,
} from '../models/LaserControllerListPrograms';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getLaserControllerListProgramsUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/producao-fabrica/laser/programas` as const,
  };
  return res;
}

/**
 * @summary Lista os programas de produção do laser
 * {@link /api/producao-fabrica/laser/programas}
 */
export async function laserControllerListPrograms(
  params?: LaserControllerListProgramsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LaserControllerListProgramsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getLaserControllerListProgramsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
