/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AtualizarPlanejamentoDTO = {
  /**
   * @type number
   */
  planejamendoId: number
  /**
   * @type string
   */
  fabricaId: string
  /**
   * @minLength 0
   * @type number
   */
  qtd: number | null
  /**
   * @type string, date-time
   */
  dia: Date | null
}