/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SetUserCargoDTO } from "./SetUserCargoDTO";

export type CargoControllerSetUserCargoMethod201 = any;

export type CargoControllerSetUserCargoMethodMutationRequest = SetUserCargoDTO;

export type CargoControllerSetUserCargoMethodMutationResponse = CargoControllerSetUserCargoMethod201;

export type CargoControllerSetUserCargoMethodMutation = {
    Response: CargoControllerSetUserCargoMethod201;
    Request: CargoControllerSetUserCargoMethodMutationRequest;
    Errors: any;
};