/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DividaSlimResponseDTO = {
  /**
   * @type number
   */
  qtd: number
  /**
   * @type string
   */
  setorCodigo: string
}