/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FabricaResponseDto } from './FabricaResponseDto.ts'
import type { ResetaFabricaDTO } from './ResetaFabricaDTO.ts'

export type FabricaControllerResetaFabricaMethodError = FabricaResponseDto

export type FabricaControllerResetaFabricaMethodMutationRequest = ResetaFabricaDTO

export type FabricaControllerResetaFabricaMethodMutationResponse = any

export type FabricaControllerResetaFabricaMethodMutation = {
  Response: any
  Request: FabricaControllerResetaFabricaMethodMutationRequest
  Errors: any
}