/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PedidosPlanejadosResponseDTO } from "./PedidosPlanejadosResponseDTO";

export type FabricaControllerConsultarPedidosPlanejadosMethodQueryParams = {
    /**
     * @type string
    */
    fabricaId: string;
};

export type FabricaControllerConsultarPedidosPlanejadosMethodError = PedidosPlanejadosResponseDTO[];

export type FabricaControllerConsultarPedidosPlanejadosMethodQueryResponse = any;

export type FabricaControllerConsultarPedidosPlanejadosMethodQuery = {
    Response: any;
    QueryParams: FabricaControllerConsultarPedidosPlanejadosMethodQueryParams;
    Errors: any;
};