/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RemoverPlanejamentoDTO } from './RemoverPlanejamentoDTO.ts'

export type FabricaControllerRemoverPlanejamentoMethod200 = any

export type FabricaControllerRemoverPlanejamentoMethodMutationRequest = RemoverPlanejamentoDTO

export type FabricaControllerRemoverPlanejamentoMethodMutationResponse = FabricaControllerRemoverPlanejamentoMethod200

export type FabricaControllerRemoverPlanejamentoMethodMutation = {
  Response: FabricaControllerRemoverPlanejamentoMethod200
  Request: FabricaControllerRemoverPlanejamentoMethodMutationRequest
  Errors: any
}