/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FabricaControllerTestemethod201 = any

export type FabricaControllerTestemethodMutationResponse = FabricaControllerTestemethod201

export type FabricaControllerTestemethodMutation = {
  Response: FabricaControllerTestemethod201
  Errors: any
}