/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConsutlarFabricaDTO } from "./ConsutlarFabricaDTO";
import type { MudancasResDto } from "./MudancasResDto";

export type FabricaControllerConsultaHistoricoFabricaMethodError = MudancasResDto[];

export type FabricaControllerConsultaHistoricoFabricaMethodMutationRequest = ConsutlarFabricaDTO;

export type FabricaControllerConsultaHistoricoFabricaMethodMutationResponse = any;

export type FabricaControllerConsultaHistoricoFabricaMethodMutation = {
    Response: any;
    Request: FabricaControllerConsultaHistoricoFabricaMethodMutationRequest;
    Errors: any;
};