/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MergeRequestPendingDto } from './MergeRequestPendingDto.ts'

export type FabricaControllerGetRequestsFabricaMergeMethodError = MergeRequestPendingDto

export type FabricaControllerGetRequestsFabricaMergeMethodQueryResponse = any[]

export type FabricaControllerGetRequestsFabricaMergeMethodQuery = {
  Response: any
  Errors: any
}