/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConsutlarFabricaDTO } from './ConsutlarFabricaDTO.ts'
import type { FabricaResponseDto } from './FabricaResponseDto.ts'

export type FabricaControllerRequestFabricaMergeMethodError = FabricaResponseDto

export type FabricaControllerRequestFabricaMergeMethodMutationRequest = ConsutlarFabricaDTO

export type FabricaControllerRequestFabricaMergeMethodMutationResponse = any

export type FabricaControllerRequestFabricaMergeMethodMutation = {
  Response: any
  Request: FabricaControllerRequestFabricaMergeMethodMutationRequest
  Errors: any
}