/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserFabricaResponseDto } from './UserFabricaResponseDto.ts'

export type FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodError = UserFabricaResponseDto[]

export type FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQueryResponse = any

export type FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQuery = {
  Response: any
  Errors: any
}