/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlanejamentoResponseDTO } from "./PlanejamentoResponseDTO";

export type FabricaControllerConsultaPlanejamentosMethodQueryParams = {
    /**
     * @type string
    */
    fabricaId: string;
    /**
     * @type string, date-time
    */
    dataInicial: Date;
    /**
     * @type string, date-time
    */
    dataFinal: Date;
};

export type FabricaControllerConsultaPlanejamentosMethodError = PlanejamentoResponseDTO[];

export type FabricaControllerConsultaPlanejamentosMethodQueryResponse = any;

export type FabricaControllerConsultaPlanejamentosMethodQuery = {
    Response: any;
    QueryParams: FabricaControllerConsultaPlanejamentosMethodQueryParams;
    Errors: any;
};