/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdicionarPlanejamentoDTO } from './AdicionarPlanejamentoDTO.ts'
import type { PlanejamentoResponseDTO } from './PlanejamentoResponseDTO.ts'

export type FabricaControllerPlanejarManualMethodError = PlanejamentoResponseDTO

export type FabricaControllerPlanejarManualMethodMutationRequest = AdicionarPlanejamentoDTO

export type FabricaControllerPlanejarManualMethodMutationResponse = any

export type FabricaControllerPlanejarManualMethodMutation = {
  Response: any
  Request: FabricaControllerPlanejarManualMethodMutationRequest
  Errors: any
}