/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtualizarPlanejamentoDTO } from './AtualizarPlanejamentoDTO.js'

export type FabricaControllerAtualizarPlanejamtnoUseCase200 = any

export type FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest = AtualizarPlanejamentoDTO

export type FabricaControllerAtualizarPlanejamtnoUseCaseMutationResponse = FabricaControllerAtualizarPlanejamtnoUseCase200

export type FabricaControllerAtualizarPlanejamtnoUseCaseMutation = {
  Response: FabricaControllerAtualizarPlanejamtnoUseCase200
  Request: FabricaControllerAtualizarPlanejamtnoUseCaseMutationRequest
  Errors: any
}