/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GanttData } from './GanttData.ts'
import type { GanttLegendaDto } from './GanttLegendaDto.ts'

export type GetGanttInformationDto = {
  /**
   * @type array
   */
  data: GanttData[]
  /**
   * @type array
   */
  legenda: GanttLegendaDto[]
}