/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetMercadosEntreSetoresTabelaDto = {
    /**
     * @type string, date-time
    */
    dia: Date;
    /**
     * @type string
    */
    item: string;
    /**
     * @type string
    */
    operacao: string;
    /**
     * @type number
    */
    planejado: number;
    /**
     * @type number
    */
    produzido: number;
    /**
     * @type number
    */
    qtdmercado: number;
};