/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetTabelaProducaoDiarioDTO = {
  /**
   * @type number
   */
  id: number
  /**
   * @type string, date-time
   */
  date_planej: string
  /**
   * @type string
   */
  item: string
  /**
   * @type string
   */
  setor: string
  /**
   * @type number
   */
  planejamento: number
  /**
   * @type number
   */
  produzido: number
}