/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ItemResDto = {
    /**
     * @type string
    */
    Item: string;
    /**
     * @type string
    */
    tipo_item: string;
};