/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetGanttInformationDto } from './GetGanttInformationDto.ts'

export enum KPIControllerGetGanttInformationMethodQueryParamsColorirEnum {
  'pedido' = 'pedido',
  'operacao' = 'operacao',
}

export type KPIControllerGetGanttInformationMethodQueryParams = {
  /**
   * @type string
   */
  fabricaId: string
  /**
   * @type string
   */
  colorir: KPIControllerGetGanttInformationMethodQueryParamsColorirEnum
}

/**
 * @description Tabela de produção gerada com sucesso
 */
export type KPIControllerGetGanttInformationMethod200 = GetGanttInformationDto

export type KPIControllerGetGanttInformationMethodQueryResponse = KPIControllerGetGanttInformationMethod200

export type KPIControllerGetGanttInformationMethodQuery = {
  Response: KPIControllerGetGanttInformationMethod200
  QueryParams: KPIControllerGetGanttInformationMethodQueryParams
  Errors: any
}