/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserResDto } from './UserResDto.ts'

export type MergeRequestPendingDto = {
  /**
   * @type string
   */
  fabricaId: string
  /**
   * @type number
   */
  mergeRequestId: number
  /**
   * @type object
   */
  user: UserResDto
  /**
   * @type string, date-time
   */
  criadaEm: Date
}