/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ItemResDto } from "./ItemResDto";

export type PedidoSlimResponseDTO = {
    /**
     * @type number
    */
    id: number;
    /**
     * @type string
    */
    codigo: string;
    /**
     * @type string, date-time
    */
    dataEntrega: Date;
    /**
     * @type number
    */
    lote: number;
    /**
     * @type object
    */
    item: ItemResDto;
};