/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AtrasoSlimResponseDTO } from './AtrasoSlimResponseDTO.ts'
import type { DividaSlimResponseDTO } from './DividaSlimResponseDTO.ts'
import type { PedidoSlimResponseDTO } from './PedidoSlimResponseDTO.ts'

export type PedidosPlanejadosResponseDTO = {
  /**
   * @type object
   */
  pedido: PedidoSlimResponseDTO
  /**
   * @type array
   */
  dividas: DividaSlimResponseDTO[]
  /**
   * @type array
   */
  atrasos: AtrasoSlimResponseDTO[]
}