/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Lista de datas planejadas
 */
export type PlanejamentoControllerDatasPlanejadasMethod200 = string[]

export type PlanejamentoControllerDatasPlanejadasMethodQueryResponse = PlanejamentoControllerDatasPlanejadasMethod200

export type PlanejamentoControllerDatasPlanejadasMethodQuery = {
  Response: PlanejamentoControllerDatasPlanejadasMethod200
  Errors: any
}