/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PlanejamentoResponseDTO = {
    /**
     * @type number
    */
    planejamentoId: number;
    /**
     * @type string
    */
    item: string;
    /**
     * @type string
    */
    setor: string;
    /**
     * @type string
    */
    pedido: string;
    /**
     * @type string, date-time
    */
    dia: Date;
    /**
     * @type number
    */
    qtd: number;
};