/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PlanejamentoControllerConsultarPedidoQueryParams = {
  /**
   * @type number
   */
  pedidoId: number
  /**
   * @type string
   */
  fabricaId: string
}

/**
 * @description Consulta pedido por pedidoId e fabricaId
 */
export type PlanejamentoControllerConsultarPedido200 = {
  /**
   * @type string | undefined
   */
  pedidoId?: string
  /**
   * @type string | undefined
   */
  fabricaId?: string
}

/**
 * @description Parâmetros inválidos
 */
export type PlanejamentoControllerConsultarPedido400 = any

export type PlanejamentoControllerConsultarPedidoQueryResponse = PlanejamentoControllerConsultarPedido200

export type PlanejamentoControllerConsultarPedidoQuery = {
  Response: PlanejamentoControllerConsultarPedido200
  QueryParams: PlanejamentoControllerConsultarPedidoQueryParams
  Errors: PlanejamentoControllerConsultarPedido400
}