/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PlanejamentoControllerPlanejamentoMethod201 = any

export type PlanejamentoControllerPlanejamentoMethodMutationResponse = PlanejamentoControllerPlanejamentoMethod201

export type PlanejamentoControllerPlanejamentoMethodMutation = {
  Response: PlanejamentoControllerPlanejamentoMethod201
  Errors: any
}