/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTabelaProducaoDiarioDTO } from "./GetTabelaProducaoDiarioDTO";

export type ProducaoSimulacaoControllerGenTabelaDiariaMethodQueryParams = {
    /**
     * @description inicio no dia
     * @type string
    */
    startDate: string;
    /**
     * @description finalizacao no dia
     * @type string
    */
    endDate: string;
};

/**
 * @description Tabela de produção gerada com sucesso
*/
export type ProducaoSimulacaoControllerGenTabelaDiariaMethod200 = GetTabelaProducaoDiarioDTO[];

export type ProducaoSimulacaoControllerGenTabelaDiariaMethodQueryResponse = ProducaoSimulacaoControllerGenTabelaDiariaMethod200;

export type ProducaoSimulacaoControllerGenTabelaDiariaMethodQuery = {
    Response: ProducaoSimulacaoControllerGenTabelaDiariaMethod200;
    QueryParams: ProducaoSimulacaoControllerGenTabelaDiariaMethodQueryParams;
    Errors: any;
};