/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SetorSnapshot } from './SetorSnapshot.ts'

export type ProducaoSimulacaoControllerConsultarMercadoMethodError = SetorSnapshot[]

export type ProducaoSimulacaoControllerConsultarMercadoMethodQueryResponse = any

export type ProducaoSimulacaoControllerConsultarMercadoMethodQuery = {
  Response: any
  Errors: any
}