/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetMercadosEntreSetoresTabelaDto } from './GetMercadosEntreSetoresTabelaDto.ts'

export type ProducaoSimulacaoControllerConsultarMercadoMethodError = GetMercadosEntreSetoresTabelaDto[]

export type ProducaoSimulacaoControllerConsultarMercadoMethodQueryResponse = any

export type ProducaoSimulacaoControllerConsultarMercadoMethodQuery = {
  Response: any
  Errors: any
}