/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReplanejarPedidoDTO = {
  /**
   * @type string
   */
  fabricaId: string
  /**
   * @type number
   */
  pedidoId: number
}