/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SalvarTabelaProducaoDiarioDTO = {
    /**
     * @type number
    */
    id: number;
    /**
     * @type number
    */
    produzido: number;
};