/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SetorSnapshot = {
  /**
   * @type string, date-time
   */
  dia: string
  /**
   * @type string
   */
  item: string
  /**
   * @type string
   */
  operacao: string
  /**
   * @type number
   */
  qtdmercado: number
}