/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type User = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  email: string
  /**
   * @type string
   */
  password: string
  /**
   * @type string
   */
  avatar: string
  /**
   * @type string, date-time
   */
  created: Date
}