/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserResponseDTO } from "./UserResponseDTO";

export type UserControllerUserDetailsMethod200 = UserResponseDTO;

/**
 * @description Invalid credentials
*/
export type UserControllerUserDetailsMethod401 = any;

export type UserControllerUserDetailsMethodQueryResponse = UserControllerUserDetailsMethod200;

export type UserControllerUserDetailsMethodQuery = {
    Response: UserControllerUserDetailsMethod200;
    Errors: UserControllerUserDetailsMethod401;
};