/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FabricaResponseDto } from "./FabricaResponseDto";

export type UserFabricaResponseDto = {
    /**
     * @type object
    */
    fabrica: FabricaResponseDto;
    /**
     * @type boolean
    */
    expirada: boolean;
};