/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description No content
*/
export type UserControllerCheckUserAuth200 = any;

export type UserControllerCheckUserAuthMutationResponse = UserControllerCheckUserAuth200;

export type UserControllerCheckUserAuthMutation = {
    Response: UserControllerCheckUserAuth200;
    Errors: any;
};