/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description User successfully logged out
 */
export type UserControllerLogoutMethod200 = any

export type UserControllerLogoutMethodMutationResponse = UserControllerLogoutMethod200

export type UserControllerLogoutMethodMutation = {
  Response: UserControllerLogoutMethod200
  Errors: any
}