/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from './CreateUserDto.ts'
import type { User } from './User.ts'

export type UserControllerCreateUserMethod200 = User

export type UserControllerCreateUserMethodMutationRequest = CreateUserDto

export type UserControllerCreateUserMethodMutationResponse = UserControllerCreateUserMethod200

export type UserControllerCreateUserMethodMutation = {
  Response: UserControllerCreateUserMethod200
  Request: UserControllerCreateUserMethodMutationRequest
  Errors: any
}