/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FabricaResponseDto } from './FabricaResponseDto.ts'

export type UserFabricaResponseDto = {
  /**
   * @type object
   */
  fabrica: FabricaResponseDto
  /**
   * @type boolean
   */
  expirada: boolean
}