/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export enum VirtualDateControllerHandleDateMethodPathParamsParamEnum {
  'proxima' = 'proxima',
  'anterior' = 'anterior',
}

export type VirtualDateControllerHandleDateMethodPathParams = {
  /**
   * @description Parâmetro para alterar a data virtual: \"proxima\" ou \"anterior\"
   * @type string
   */
  param: VirtualDateControllerHandleDateMethodPathParamsParamEnum
}

/**
 * @description Lista de datas planejadas
 */
export type VirtualDateControllerHandleDateMethod200 = Date

export type VirtualDateControllerHandleDateMethodMutationResponse = VirtualDateControllerHandleDateMethod200

export type VirtualDateControllerHandleDateMethodMutation = {
  Response: VirtualDateControllerHandleDateMethod200
  PathParams: VirtualDateControllerHandleDateMethodPathParams
  Errors: any
}