/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { FabricaControllerGetRequestsFabricaMergeMethodQueryResponse } from '../models/FabricaControllerGetRequestsFabricaMergeMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerGetRequestsFabricaMergeMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/merge/request` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/merge/request}
 */
export async function fabricaControllerGetRequestsFabricaMergeMethod(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FabricaControllerGetRequestsFabricaMergeMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFabricaControllerGetRequestsFabricaMergeMethodUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
