/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQueryResponse } from "../models/FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodUrl() {
  return `http://192.168.99.129:30010/api/planejador/fabrica/usuario` as const
}

/**
 * {@link /api/planejador/fabrica/usuario}
 */
export async function fabricaControllerConsutlarFabricasDoUsuarioUseCaseMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFabricaControllerConsutlarFabricasDoUsuarioUseCaseMethodUrl().toString(), ... requestConfig })
return res.data
}