/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerMergeFabricaMethodMutationRequest, FabricaControllerMergeFabricaMethodMutationResponse } from "../models/FabricaControllerMergeFabricaMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerMergeFabricaMethodUrl() {
  return `http://192.168.99.129:30010/api/planejador/fabrica/merge` as const
}

/**
 * {@link /api/planejador/fabrica/merge}
 */
export async function fabricaControllerMergeFabricaMethod(data: FabricaControllerMergeFabricaMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerMergeFabricaMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerMergeFabricaMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerMergeFabricaMethodMutationRequest>({ method : "POST", url : getFabricaControllerMergeFabricaMethodUrl().toString(), data, ... requestConfig })
return res.data
}