/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerPlanejarManualMethodMutationRequest,
  FabricaControllerPlanejarManualMethodMutationResponse,
} from '../models/FabricaControllerPlanejarManualMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerPlanejarManualMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos/manual` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/planejamentos/manual}
 */
export async function fabricaControllerPlanejarManualMethod(
  data: FabricaControllerPlanejarManualMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerPlanejarManualMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerPlanejarManualMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerPlanejarManualMethodMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerPlanejarManualMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
