/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerDeletarFabricaMethodMutationRequest, FabricaControllerDeletarFabricaMethodMutationResponse } from "../models/FabricaControllerDeletarFabricaMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerDeletarFabricaMethodUrl() {
  return `https://app.prod.ethos/api/planejador/fabrica/fabrica` as const
}

/**
 * {@link /api/planejador/fabrica/fabrica}
 */
export async function fabricaControllerDeletarFabricaMethod(data: FabricaControllerDeletarFabricaMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerDeletarFabricaMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerDeletarFabricaMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerDeletarFabricaMethodMutationRequest>({ method : "DELETE", url : getFabricaControllerDeletarFabricaMethodUrl().toString(), data, ... requestConfig })
return res.data
}