/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerConsultaHistoricoFabricaMethodQueryResponse,
  FabricaControllerConsultaHistoricoFabricaMethodQueryParams,
} from '../models/FabricaControllerConsultaHistoricoFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerConsultaHistoricoFabricaMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/historico` as const,
  };
  return res;
}

/**
 * @summary busca mudancas que foram aplicadas nessa fabrica
 * {@link /api/planejador/fabrica/historico}
 */
export async function fabricaControllerConsultaHistoricoFabricaMethod(
  params: FabricaControllerConsultaHistoricoFabricaMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FabricaControllerConsultaHistoricoFabricaMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFabricaControllerConsultaHistoricoFabricaMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
