/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { FabricaControllerPlanejarPedidoMethodMutationRequest, FabricaControllerPlanejarPedidoMethodMutationResponse } from "../models/FabricaControllerPlanejarPedidoMethod";

function getFabricaControllerPlanejarPedidoMethodUrl() {
  return `https://app.prod.ethos/api/planejador/fabrica/planejamentos` as const
}

/**
 * {@link /api/planejador/fabrica/planejamentos}
 */
export async function fabricaControllerPlanejarPedidoMethod(data: FabricaControllerPlanejarPedidoMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerPlanejarPedidoMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerPlanejarPedidoMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerPlanejarPedidoMethodMutationRequest>({ method : "POST", url : getFabricaControllerPlanejarPedidoMethodUrl().toString(), data, ... requestConfig })
return res.data
}