/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerConsultaPlanejamentosMethodQueryResponse,
  FabricaControllerConsultaPlanejamentosMethodQueryParams,
} from '../models/FabricaControllerConsultaPlanejamentosMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerConsultaPlanejamentosMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/planejamentos}
 */
export async function fabricaControllerConsultaPlanejamentosMethod(
  params: FabricaControllerConsultaPlanejamentosMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FabricaControllerConsultaPlanejamentosMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFabricaControllerConsultaPlanejamentosMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
