/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerResetaFabricaMethodMutationRequest,
  FabricaControllerResetaFabricaMethodMutationResponse,
} from '../models/FabricaControllerResetaFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerResetaFabricaMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/reset` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/reset}
 */
export async function fabricaControllerResetaFabricaMethod(
  data: FabricaControllerResetaFabricaMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerResetaFabricaMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerResetaFabricaMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerResetaFabricaMethodMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerResetaFabricaMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
