/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { FabricaControllerConsultaPlanejamentosMethodQueryResponse, FabricaControllerConsultaPlanejamentosMethodQueryParams } from "../models/FabricaControllerConsultaPlanejamentosMethod";

function getFabricaControllerConsultaPlanejamentosMethodUrl() {
  return `https://app.prod.ethos/api/planejador/fabrica/planejamentos` as const
}

/**
 * {@link /api/planejador/fabrica/planejamentos}
 */
export async function fabricaControllerConsultaPlanejamentosMethod(params: FabricaControllerConsultaPlanejamentosMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerConsultaPlanejamentosMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFabricaControllerConsultaPlanejamentosMethodUrl().toString(), params, ... requestConfig })
return res.data
}