/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { FabricaControllerPlanejarManualMethodMutationRequest, FabricaControllerPlanejarManualMethodMutationResponse } from "../models/FabricaControllerPlanejarManualMethod";

function getFabricaControllerPlanejarManualMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos/manual` as const
}

/**
 * {@link /api/planejador/fabrica/planejamentos/manual}
 */
export async function fabricaControllerPlanejarManualMethod(data: FabricaControllerPlanejarManualMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerPlanejarManualMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerPlanejarManualMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerPlanejarManualMethodMutationRequest>({ method : "POST", url : getFabricaControllerPlanejarManualMethodUrl().toString(), data, ... requestConfig })
return res.data
}