/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerRequestFabricaMergeMethodMutationRequest,
  FabricaControllerRequestFabricaMergeMethodMutationResponse,
} from '../models/FabricaControllerRequestFabricaMergeMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerRequestFabricaMergeMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/merge/request` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/merge/request}
 */
export async function fabricaControllerRequestFabricaMergeMethod(
  data: FabricaControllerRequestFabricaMergeMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerRequestFabricaMergeMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerRequestFabricaMergeMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerRequestFabricaMergeMethodMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerRequestFabricaMergeMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
