/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerReplanejarPedidoUseCaseMutationRequest,
  FabricaControllerReplanejarPedidoUseCaseMutationResponse,
} from '../models/FabricaControllerReplanejarPedidoUseCase';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerReplanejarPedidoUseCaseUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/fabrica/replanejamento` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/fabrica/replanejamento}
 */
export async function fabricaControllerReplanejarPedidoUseCase(
  data: FabricaControllerReplanejarPedidoUseCaseMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerReplanejarPedidoUseCaseMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerReplanejarPedidoUseCaseMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerReplanejarPedidoUseCaseMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerReplanejarPedidoUseCaseUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
