/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerForkFabricaMethodMutationRequest,
  FabricaControllerForkFabricaMethodMutationResponse,
} from '../models/FabricaControllerForkFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerForkFabricaMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/fork` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/fork}
 */
export async function fabricaControllerForkFabricaMethod(
  data: FabricaControllerForkFabricaMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerForkFabricaMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerForkFabricaMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerForkFabricaMethodMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerForkFabricaMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
