/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerConsultarPedidosPlanejadosMethodQueryResponse,
  FabricaControllerConsultarPedidosPlanejadosMethodQueryParams,
} from '../models/FabricaControllerConsultarPedidosPlanejadosMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerConsultarPedidosPlanejadosMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos/pedidos` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/planejamentos/pedidos}
 */
export async function fabricaControllerConsultarPedidosPlanejadosMethod(
  params: FabricaControllerConsultarPedidosPlanejadosMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FabricaControllerConsultarPedidosPlanejadosMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFabricaControllerConsultarPedidosPlanejadosMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
