/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerRemoverPlanejamentoMethodMutationRequest,
  FabricaControllerRemoverPlanejamentoMethodMutationResponse,
} from '../models/FabricaControllerRemoverPlanejamentoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerRemoverPlanejamentoMethodUrl() {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/planejamentos}
 */
export async function fabricaControllerRemoverPlanejamentoMethod(
  data: FabricaControllerRemoverPlanejamentoMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerRemoverPlanejamentoMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerRemoverPlanejamentoMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerRemoverPlanejamentoMethodMutationRequest
  >({
    method: 'DELETE',
    url: getFabricaControllerRemoverPlanejamentoMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
