/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerRemoverPlanejamentoMethodMutationRequest, FabricaControllerRemoverPlanejamentoMethodMutationResponse } from "../models/FabricaControllerRemoverPlanejamentoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerRemoverPlanejamentoMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/fabrica/planejamentos` as const
}

/**
 * {@link /api/planejador/fabrica/planejamentos}
 */
export async function fabricaControllerRemoverPlanejamentoMethod(data: FabricaControllerRemoverPlanejamentoMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerRemoverPlanejamentoMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerRemoverPlanejamentoMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerRemoverPlanejamentoMethodMutationRequest>({ method : "DELETE", url : getFabricaControllerRemoverPlanejamentoMethodUrl().toString(), data, ... requestConfig })
return res.data
}