/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerDeletarFabricaMethodMutationRequest,
  FabricaControllerDeletarFabricaMethodMutationResponse,
} from '../models/FabricaControllerDeletarFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerDeletarFabricaMethodUrl() {
  const res = {
    method: 'DELETE',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/fabrica` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/fabrica}
 */
export async function fabricaControllerDeletarFabricaMethod(
  data: FabricaControllerDeletarFabricaMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerDeletarFabricaMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerDeletarFabricaMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerDeletarFabricaMethodMutationRequest
  >({
    method: 'DELETE',
    url: getFabricaControllerDeletarFabricaMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
