/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerMergeFabricaMethodMutationRequest,
  FabricaControllerMergeFabricaMethodMutationResponse,
} from '../models/FabricaControllerMergeFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerMergeFabricaMethodUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/planejador/fabrica/merge` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica/merge}
 */
export async function fabricaControllerMergeFabricaMethod(
  data: FabricaControllerMergeFabricaMethodMutationRequest,
  config: Partial<
    RequestConfig<FabricaControllerMergeFabricaMethodMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FabricaControllerMergeFabricaMethodMutationResponse,
    ResponseErrorConfig<Error>,
    FabricaControllerMergeFabricaMethodMutationRequest
  >({
    method: 'POST',
    url: getFabricaControllerMergeFabricaMethodUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
