/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  FabricaControllerConsultaFabricaMethodQueryResponse,
  FabricaControllerConsultaFabricaMethodQueryParams,
} from '../models/FabricaControllerConsultaFabricaMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getFabricaControllerConsultaFabricaMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/fabrica` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/fabrica}
 */
export async function fabricaControllerConsultaFabricaMethod(
  params: FabricaControllerConsultaFabricaMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FabricaControllerConsultaFabricaMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getFabricaControllerConsultaFabricaMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
