/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { FabricaControllerConsultaFabricaMethodQueryResponse, FabricaControllerConsultaFabricaMethodQueryParams } from "../models/FabricaControllerConsultaFabricaMethod";

function getFabricaControllerConsultaFabricaMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/fabrica` as const
}

/**
 * {@link /api/planejador/fabrica}
 */
export async function fabricaControllerConsultaFabricaMethod(params: FabricaControllerConsultaFabricaMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerConsultaFabricaMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFabricaControllerConsultaFabricaMethodUrl().toString(), params, ... requestConfig })
return res.data
}