/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest, FabricaControllerSincronizarFabricaPrivadaMethodMutationResponse } from "../models/FabricaControllerSincronizarFabricaPrivadaMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerSincronizarFabricaPrivadaMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/fabrica/sincronizar` as const
}

/**
 * @description operação que força uma fabrica a mudar o pai dela para o nó principal mais recente
 * @summary sicronizar com o nó principal atual
 * {@link /api/planejador/fabrica/sincronizar}
 */
export async function fabricaControllerSincronizarFabricaPrivadaMethod(data: FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerSincronizarFabricaPrivadaMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerSincronizarFabricaPrivadaMethodMutationRequest>({ method : "POST", url : getFabricaControllerSincronizarFabricaPrivadaMethodUrl().toString(), data, ... requestConfig })
return res.data
}