/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { FabricaControllerDesplanejarPedidoNaFabricaMethodMutationRequest, FabricaControllerDesplanejarPedidoNaFabricaMethodMutationResponse } from "../models/FabricaControllerDesplanejarPedidoNaFabricaMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getFabricaControllerDesplanejarPedidoNaFabricaMethodUrl() {
  return `https://app.prod.ethos/api/planejador/fabrica/fabrica/pedido` as const
}

/**
 * {@link /api/planejador/fabrica/fabrica/pedido}
 */
export async function fabricaControllerDesplanejarPedidoNaFabricaMethod(data: FabricaControllerDesplanejarPedidoNaFabricaMethodMutationRequest, config: Partial<RequestConfig<FabricaControllerDesplanejarPedidoNaFabricaMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerDesplanejarPedidoNaFabricaMethodMutationResponse, ResponseErrorConfig<Error>, FabricaControllerDesplanejarPedidoNaFabricaMethodMutationRequest>({ method : "DELETE", url : getFabricaControllerDesplanejarPedidoNaFabricaMethodUrl().toString(), data, ... requestConfig })
return res.data
}