/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { FabricaControllerConsultaHistoricoFabricaMethodQueryResponse, FabricaControllerConsultaHistoricoFabricaMethodQueryParams } from "../models/FabricaControllerConsultaHistoricoFabricaMethod";

function getFabricaControllerConsultaHistoricoFabricaMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/fabrica/historico` as const
}

/**
 * @summary busca mudancas que foram aplicadas nessa fabrica
 * {@link /api/planejador/fabrica/historico}
 */
export async function fabricaControllerConsultaHistoricoFabricaMethod(params: FabricaControllerConsultaHistoricoFabricaMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<FabricaControllerConsultaHistoricoFabricaMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getFabricaControllerConsultaHistoricoFabricaMethodUrl().toString(), params, ... requestConfig })
return res.data
}