/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  HealthControllerCheckQueryResponse,
  HealthControllerCheck503,
} from '../models/HealthControllerCheck';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getHealthControllerCheckUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/health` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/health}
 */
export async function healthControllerCheck(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthControllerCheckQueryResponse,
    ResponseErrorConfig<HealthControllerCheck503>,
    unknown
  >({
    method: 'GET',
    url: getHealthControllerCheckUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
