/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { HealthControllerCheckQueryResponse, HealthControllerCheck503 } from "../models/HealthControllerCheck";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getHealthControllerCheckUrl() {
  return `https://app.prod.ethos/api/planejador/health` as const
}

/**
 * {@link /api/planejador/health}
 */
export async function healthControllerCheck(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<HealthControllerCheckQueryResponse, ResponseErrorConfig<HealthControllerCheck503>, unknown>({ method : "GET", url : getHealthControllerCheckUrl().toString(), ... requestConfig })
return res.data
}