/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { ItemControllerGetItemCapabilildadeMethodQueryResponse } from "../models/ItemControllerGetItemCapabilildadeMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getItemControllerGetItemCapabilildadeMethodUrl() {
  return `http://192.168.99.129:30010/api/planejador/item/capabiliade` as const
}

/**
 * {@link /api/planejador/item/capabiliade}
 */
export async function itemControllerGetItemCapabilildadeMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<ItemControllerGetItemCapabilildadeMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getItemControllerGetItemCapabilildadeMethodUrl().toString(), ... requestConfig })
return res.data
}