/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { ItemControllerCadastrarItemCapabilidadeMethodMutationRequest, ItemControllerCadastrarItemCapabilidadeMethodMutationResponse } from "../models/ItemControllerCadastrarItemCapabilidadeMethod";

function getItemControllerCadastrarItemCapabilidadeMethodUrl() {
  return `https://app.prod.ethos/api/planejador/item/capabilidade` as const
}

/**
 * {@link /api/planejador/item/capabilidade}
 */
export async function itemControllerCadastrarItemCapabilidadeMethod(data: ItemControllerCadastrarItemCapabilidadeMethodMutationRequest, config: Partial<RequestConfig<ItemControllerCadastrarItemCapabilidadeMethodMutationRequest>> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<ItemControllerCadastrarItemCapabilidadeMethodMutationResponse, ResponseErrorConfig<Error>, ItemControllerCadastrarItemCapabilidadeMethodMutationRequest>({ method : "POST", url : getItemControllerCadastrarItemCapabilidadeMethodUrl().toString(), data, ... requestConfig })
return res.data
}