/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type { ItemControllerGetItemCapabilidadeMethodQueryResponse } from '../models/ItemControllerGetItemCapabilidadeMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getItemControllerGetItemCapabilidadeMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/item/capabilidade` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/item/capabilidade}
 */
export async function itemControllerGetItemCapabilidadeMethod(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ItemControllerGetItemCapabilidadeMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getItemControllerGetItemCapabilidadeMethodUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
