/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  PedidoControllerConsultaItensDoPedidoMethodQueryResponse,
  PedidoControllerConsultaItensDoPedidoMethodQueryParams,
} from '../models/PedidoControllerConsultaItensDoPedidoMethod';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getPedidoControllerConsultaItensDoPedidoMethodUrl() {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/planejador/pedido/itens` as const,
  };
  return res;
}

/**
 * {@link /api/planejador/pedido/itens}
 */
export async function pedidoControllerConsultaItensDoPedidoMethod(
  params: PedidoControllerConsultaItensDoPedidoMethodQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PedidoControllerConsultaItensDoPedidoMethodQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getPedidoControllerConsultaItensDoPedidoMethodUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
