/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PedidoControllerConsultaPedidoMethodQueryResponse, PedidoControllerConsultaPedidoMethodQueryParams } from "../models/PedidoControllerConsultaPedidoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPedidoControllerConsultaPedidoMethodUrl() {
  return `http://192.168.99.129:30010/api/planejador/pedido` as const
}

/**
 * {@link /api/planejador/pedido}
 */
export async function pedidoControllerConsultaPedidoMethod(params: PedidoControllerConsultaPedidoMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PedidoControllerConsultaPedidoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPedidoControllerConsultaPedidoMethodUrl().toString(), params, ... requestConfig })
return res.data
}