/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { PedidoControllerConsultaItensDoPedidoMethodQueryResponse, PedidoControllerConsultaItensDoPedidoMethodQueryParams } from "../models/PedidoControllerConsultaItensDoPedidoMethod";
import type { RequestConfig, ResponseErrorConfig } from "@/client";

function getPedidoControllerConsultaItensDoPedidoMethodUrl() {
  return `https://app.prod.ethos/api/planejador/pedido/itens` as const
}

/**
 * {@link /api/planejador/pedido/itens}
 */
export async function pedidoControllerConsultaItensDoPedidoMethod(params: PedidoControllerConsultaItensDoPedidoMethodQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PedidoControllerConsultaItensDoPedidoMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPedidoControllerConsultaItensDoPedidoMethodUrl().toString(), params, ... requestConfig })
return res.data
}