/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@/client";
import type { RequestConfig, ResponseErrorConfig } from "@/client";
import type { PlanejamentoControllerDatasPlanejadasMethodQueryResponse } from "../models/PlanejamentoControllerDatasPlanejadasMethod";

function getPlanejamentoControllerDatasPlanejadasMethodUrl() {
  return `https://app.ethos.ind.br/api/planejador/plan/datas` as const
}

/**
 * {@link /api/planejador/plan/datas}
 */
export async function planejamentoControllerDatasPlanejadasMethod(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client:request = client, ...requestConfig } = config

const res = await request<PlanejamentoControllerDatasPlanejadasMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPlanejamentoControllerDatasPlanejadasMethodUrl().toString(), ... requestConfig })
return res.data
}