/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BufferItemDto } from "./BufferItemDto";

export type BufferHistoricoDTO = {
    /**
     * @description ID do histórico de buffer (gerado automaticamente)
     * @type number | undefined
    */
    id?: number;
    /**
     * @description Data/Hora do registro (formato ISO 8601, ex: \"2025-06-09T10:30:00.000Z\" ou \"2025-06-09\")
     * @type string, date-time
    */
    serverTime: Date;
    /**
     * @description Dados do item associado ao histórico de buffer
    */
    item: BufferItemDto;
    /**
     * @description Valor do buffer
     * @type number
    */
    buffer: number;
};