/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Job de criação de tabela executado com sucesso
 */
export type BufferControllerJobMethod201 = any;

export type BufferControllerJobMethodMutationResponse =
  BufferControllerJobMethod201;

export type BufferControllerJobMethodMutation = {
  Response: BufferControllerJobMethod201;
  Errors: any;
};
