/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CompactBuffer = {
    /**
     * @type string
    */
    item: string;
    /**
     * @type string
    */
    serverTime: string;
    /**
     * @type string
    */
    tipo_item: string;
    /**
     * @type string
    */
    ItemFiho: string;
};