/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BufferHistoricoDTO } from './BufferHistoricoDTO';

export enum ResMercadosIntermediarioDoSetorDTOConsultaEnum {
  ResMercadosIntermediarioDoSetorDTOConsultaEnum_110 = '110',
  ResMercadosIntermediarioDoSetorDTOConsultaEnum_000 = '000',
  TODOS = 'TODOS',
}

export type ResMercadosIntermediarioDoSetorDTO = {
  /**
   * @description ID único do mercado intermediário (gerado automaticamente)
   * @type number
   */
  readonly idMercadosIntermediario: number;
  /**
   * @description Tipo de consulta associado ao mercado
   * @type string
   */
  consulta: ResMercadosIntermediarioDoSetorDTOConsultaEnum;
  /**
   * @description Nome do mercado intermediário
   * @maxLength 255
   * @type string
   */
  nome: string;
  /**
   * @description Histórico de buffers associado a este mercado.
   * @type array
   */
  histBuffer: BufferHistoricoDTO[];
};
