/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SaveBufferLogDto = {
  /**
   * @type string
   */
  item: string;
  /**
   * @type number
   */
  qtd: number;
  /**
   * @type string
   */
  mercadoName: string;
};
