/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResSetorDTO } from "./ResSetorDTO";

export type SetoresControllerGetSetoresMethod200 = ResSetorDTO[];

export type SetoresControllerGetSetoresMethodQueryResponse = SetoresControllerGetSetoresMethod200;

export type SetoresControllerGetSetoresMethodQuery = {
    Response: SetoresControllerGetSetoresMethod200;
    Errors: any;
};