/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ResMercadosIntermediarioDoSetorDTO } from "./ResMercadosIntermediarioDoSetorDTO";

export type SetoresControllerGetSetorMercadoMethodPathParams = {
    /**
     * @type number
    */
    setorId: number;
    /**
     * @type string
    */
    dia: string;
};

export type SetoresControllerGetSetorMercadoMethod200 = ResMercadosIntermediarioDoSetorDTO[];

export type SetoresControllerGetSetorMercadoMethodQueryResponse = SetoresControllerGetSetorMercadoMethod200;

export type SetoresControllerGetSetorMercadoMethodQuery = {
    Response: SetoresControllerGetSetorMercadoMethod200;
    PathParams: SetoresControllerGetSetorMercadoMethodPathParams;
    Errors: any;
};