/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CertificadosCatControllerProcessarCertificadoMutationRequest,
  CertificadosCatControllerProcessarCertificadoMutationResponse,
} from '../models/CertificadosCatControllerProcessarCertificado';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCertificadosCatControllerProcessarCertificadoUrl() {
  const res = {
    method: 'POST',
    url: `https://app.ethos.ind.br/api/certificados` as const,
  };
  return res;
}

/**
 * @summary Processa um arquivo de certificado bruto.
 * {@link /api/certificados}
 */
export async function certificadosCatControllerProcessarCertificado(
  data: CertificadosCatControllerProcessarCertificadoMutationRequest,
  config: Partial<
    RequestConfig<CertificadosCatControllerProcessarCertificadoMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CertificadosCatControllerProcessarCertificadoMutationResponse,
    ResponseErrorConfig<Error>,
    CertificadosCatControllerProcessarCertificadoMutationRequest
  >({
    method: 'POST',
    url: getCertificadosCatControllerProcessarCertificadoUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
