/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/client';
import type {
  CertificadosCatControllerRetornaArquivoCertificadoTxtQueryResponse,
  CertificadosCatControllerRetornaArquivoCertificadoTxtPathParams,
} from '../models/CertificadosCatControllerRetornaArquivoCertificadoTxt';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/client';

function getCertificadosCatControllerRetornaArquivoCertificadoTxtUrl(
  id: CertificadosCatControllerRetornaArquivoCertificadoTxtPathParams['id'],
) {
  const res = {
    method: 'GET',
    url: `https://app.ethos.ind.br/api/certificados/file/${id}` as const,
  };
  return res;
}

/**
 * @summary Stream do arquivo txt.
 * {@link /api/certificados/file/:id}
 */
export async function certificadosCatControllerRetornaArquivoCertificadoTxt(
  id: CertificadosCatControllerRetornaArquivoCertificadoTxtPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CertificadosCatControllerRetornaArquivoCertificadoTxtQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getCertificadosCatControllerRetornaArquivoCertificadoTxtUrl(
      id,
    ).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
